/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "AEACFREF")
public class AeacfrefEntity {

    @Column(name = "ID_AEACFREF", table = "AEACFREF", nullable = false)
    @Id
    private Integer idAeacfref;

    @Column(name = "ID_AEAENTRA", table = "AEACFREF")
    @Basic
    private Integer idAeaentra;

    @Column(name = "ID_AEAMODDF", table = "AEACFREF")
    @Basic
    private Integer idAeamoddf;

    @Column(name = "ID_AEANFSAI", table = "AEACFREF")
    @Basic
    private Integer idAeanfsai;

    @Column(name = "ID_AEANFSAI_CUPOM", table = "AEACFREF")
    @Basic
    private Integer idAeanfsaiCupom;

    @Column(name = "ID_CFAESTAD", table = "AEACFREF")
    @Basic
    private Integer idCfaestad;

    @Column(name = "GUID", table = "AEACFREF", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "AEACFREF", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "AEACFREF")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtCad;

    @Column(name = "DT_ALT", table = "AEACFREF")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtAlt;

    @Column(name = "CT_INTEG", table = "AEACFREF")
    @Basic
    private Integer ctInteg;

    @Column(name = "TIPO", table = "AEACFREF")
    @Basic
    private Character tipo;

    @Column(name = "ECF_CX", table = "AEACFREF")
    @Basic
    private Integer ecfCx;

    @Column(name = "SERIE", table = "AEACFREF", length = 3)
    @Basic
    private String serie;

    @Column(name = "NUM_DOC", table = "AEACFREF")
    @Basic
    private Integer numDoc;

    @Column(name = "ANO_MES", table = "AEACFREF", length = 4)
    @Basic
    private String anoMes;

    @Column(name = "DT_DOC", table = "AEACFREF")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date dtDoc;

    @Column(name = "CNPJ_EMIT", table = "AEACFREF", length = 18)
    @Basic
    private String cnpjEmit;

    @Column(name = "IE_EMIT", table = "AEACFREF", length = 18)
    @Basic
    private String ieEmit;

    @Column(name = "CHAVE", table = "AEACFREF", length = 50)
    @Basic
    private String chave;

    public Integer getIdAeacfref() {
        return this.idAeacfref;
    }

    public void setIdAeacfref(Integer idAeacfref) {
        this.idAeacfref = idAeacfref;
    }

    public Integer getIdAeaentra() {
        return this.idAeaentra;
    }

    public void setIdAeaentra(Integer idAeaentra) {
        this.idAeaentra = idAeaentra;
    }

    public Integer getIdAeamoddf() {
        return this.idAeamoddf;
    }

    public void setIdAeamoddf(Integer idAeamoddf) {
        this.idAeamoddf = idAeamoddf;
    }

    public Integer getIdAeanfsai() {
        return this.idAeanfsai;
    }

    public void setIdAeanfsai(Integer idAeanfsai) {
        this.idAeanfsai = idAeanfsai;
    }

    public Integer getIdAeanfsaiCupom() {
        return this.idAeanfsaiCupom;
    }

    public void setIdAeanfsaiCupom(Integer idAeanfsaiCupom) {
        this.idAeanfsaiCupom = idAeanfsaiCupom;
    }

    public Integer getIdCfaestad() {
        return this.idCfaestad;
    }

    public void setIdCfaestad(Integer idCfaestad) {
        this.idCfaestad = idCfaestad;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public Date getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(Date dtCad) {
        this.dtCad = dtCad;
    }

    public Date getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(Date dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public Character getTipo() {
        return this.tipo;
    }

    public void setTipo(Character tipo) {
        this.tipo = tipo;
    }

    public Integer getEcfCx() {
        return this.ecfCx;
    }

    public void setEcfCx(Integer ecfCx) {
        this.ecfCx = ecfCx;
    }

    public String getSerie() {
        return this.serie;
    }

    public void setSerie(String serie) {
        this.serie = serie;
    }

    public Integer getNumDoc() {
        return this.numDoc;
    }

    public void setNumDoc(Integer numDoc) {
        this.numDoc = numDoc;
    }

    public String getAnoMes() {
        return this.anoMes;
    }

    public void setAnoMes(String anoMes) {
        this.anoMes = anoMes;
    }

    public Date getDtDoc() {
        return this.dtDoc;
    }

    public void setDtDoc(Date dtDoc) {
        this.dtDoc = dtDoc;
    }

    public String getCnpjEmit() {
        return this.cnpjEmit;
    }

    public void setCnpjEmit(String cnpjEmit) {
        this.cnpjEmit = cnpjEmit;
    }

    public String getIeEmit() {
        return this.ieEmit;
    }

    public void setIeEmit(String ieEmit) {
        this.ieEmit = ieEmit;
    }

    public String getChave() {
        return this.chave;
    }

    public void setChave(String chave) {
        this.chave = chave;
    }

}
