/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "AEAFATOR", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"CODIGO"})})
public class AeafatorEntity {

    @Column(name = "ID_AEAFATOR", table = "AEAFATOR", nullable = false)
    @Id
    private Integer idAeafator;

    @Column(name = "GUID", table = "AEAFATOR", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "AEAFATOR", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "AEAFATOR")
    @Basic
    private String dtCad;

    @Column(name = "DT_ALT", table = "AEAFATOR")
    @Basic
    private String dtAlt;

    @Column(name = "CT_INTEG", table = "AEAFATOR")
    @Basic
    private Integer ctInteg;

    @Column(name = "CODIGO", table = "AEAFATOR", nullable = false)
    @Basic(optional = false)
    private int codigo;

    @Column(name = "DESCRICAO", table = "AEAFATOR", nullable = false, length = 40)
    @Basic(optional = false)
    private String descricao;

    @Column(name = "JURO_MEDIO_ATAC", table = "AEAFATOR", nullable = false)
    @Basic(optional = false)
    private double juroMedioAtac;

    @Column(name = "JURO_MEDIO_VARE", table = "AEAFATOR", nullable = false)
    @Basic(optional = false)
    private double juroMedioVare;

    @Column(name = "JURO_MEDIO_SERV", table = "AEAFATOR", nullable = false)
    @Basic(optional = false)
    private double juroMedioServ;

    @Column(name = "DESC_PG_ANT_ATAC", table = "AEAFATOR", nullable = false)
    @Basic(optional = false)
    private double descPgAntAtac;

    @Column(name = "DESC_PG_ANT_VARE", table = "AEAFATOR", nullable = false)
    @Basic(optional = false)
    private double descPgAntVare;

    @Column(name = "DESC_PG_ANT_SERV", table = "AEAFATOR", nullable = false)
    @Basic(optional = false)
    private double descPgAntServ;

    @Column(name = "DESC_MAX_PLANO_ATAC_VISTA", table = "AEAFATOR", nullable = false)
    @Basic(optional = false)
    private double descMaxPlanoAtacVista;

    @Column(name = "DESC_MAX_PLANO_ATAC_PRAZO", table = "AEAFATOR", nullable = false)
    @Basic(optional = false)
    private double descMaxPlanoAtacPrazo;

    @Column(name = "DESC_MAX_PLANO_VARE_VISTA", table = "AEAFATOR", nullable = false)
    @Basic(optional = false)
    private double descMaxPlanoVareVista;

    @Column(name = "DESC_MAX_PLANO_VARE_PRAZO", table = "AEAFATOR", nullable = false)
    @Basic(optional = false)
    private double descMaxPlanoVarePrazo;

    @Column(name = "DESC_MAX_PLANO_SERV_VISTA", table = "AEAFATOR", nullable = false)
    @Basic(optional = false)
    private double descMaxPlanoServVista;

    @Column(name = "DESC_MAX_PLANO_SERV_PRAZO", table = "AEAFATOR", nullable = false)
    @Basic(optional = false)
    private double descMaxPlanoServPrazo;

    @Column(name = "TIPO_BONUS", table = "AEAFATOR")
    @Basic
    private Character tipoBonus;

    @Column(name = "DIAS_BONUS", table = "AEAFATOR", nullable = false)
    @Basic(optional = false)
    private int diasBonus;

    public Integer getIdAeafator() {
        return this.idAeafator;
    }

    public void setIdAeafator(Integer idAeafator) {
        this.idAeafator = idAeafator;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public String getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(String dtCad) {
        this.dtCad = dtCad;
    }

    public String getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(String dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public double getJuroMedioAtac() {
        return this.juroMedioAtac;
    }

    public void setJuroMedioAtac(double juroMedioAtac) {
        this.juroMedioAtac = juroMedioAtac;
    }

    public double getJuroMedioVare() {
        return this.juroMedioVare;
    }

    public void setJuroMedioVare(double juroMedioVare) {
        this.juroMedioVare = juroMedioVare;
    }

    public double getJuroMedioServ() {
        return this.juroMedioServ;
    }

    public void setJuroMedioServ(double juroMedioServ) {
        this.juroMedioServ = juroMedioServ;
    }

    public double getDescPgAntAtac() {
        return this.descPgAntAtac;
    }

    public void setDescPgAntAtac(double descPgAntAtac) {
        this.descPgAntAtac = descPgAntAtac;
    }

    public double getDescPgAntVare() {
        return this.descPgAntVare;
    }

    public void setDescPgAntVare(double descPgAntVare) {
        this.descPgAntVare = descPgAntVare;
    }

    public double getDescPgAntServ() {
        return this.descPgAntServ;
    }

    public void setDescPgAntServ(double descPgAntServ) {
        this.descPgAntServ = descPgAntServ;
    }

    public double getDescMaxPlanoAtacVista() {
        return this.descMaxPlanoAtacVista;
    }

    public void setDescMaxPlanoAtacVista(double descMaxPlanoAtacVista) {
        this.descMaxPlanoAtacVista = descMaxPlanoAtacVista;
    }

    public double getDescMaxPlanoAtacPrazo() {
        return this.descMaxPlanoAtacPrazo;
    }

    public void setDescMaxPlanoAtacPrazo(double descMaxPlanoAtacPrazo) {
        this.descMaxPlanoAtacPrazo = descMaxPlanoAtacPrazo;
    }

    public double getDescMaxPlanoVareVista() {
        return this.descMaxPlanoVareVista;
    }

    public void setDescMaxPlanoVareVista(double descMaxPlanoVareVista) {
        this.descMaxPlanoVareVista = descMaxPlanoVareVista;
    }

    public double getDescMaxPlanoVarePrazo() {
        return this.descMaxPlanoVarePrazo;
    }

    public void setDescMaxPlanoVarePrazo(double descMaxPlanoVarePrazo) {
        this.descMaxPlanoVarePrazo = descMaxPlanoVarePrazo;
    }

    public double getDescMaxPlanoServVista() {
        return this.descMaxPlanoServVista;
    }

    public void setDescMaxPlanoServVista(double descMaxPlanoServVista) {
        this.descMaxPlanoServVista = descMaxPlanoServVista;
    }

    public double getDescMaxPlanoServPrazo() {
        return this.descMaxPlanoServPrazo;
    }

    public void setDescMaxPlanoServPrazo(double descMaxPlanoServPrazo) {
        this.descMaxPlanoServPrazo = descMaxPlanoServPrazo;
    }

    public Character getTipoBonus() {
        return this.tipoBonus;
    }

    public void setTipoBonus(Character tipoBonus) {
        this.tipoBonus = tipoBonus;
    }

    public int getDiasBonus() {
        return this.diasBonus;
    }

    public void setDiasBonus(int diasBonus) {
        this.diasBonus = diasBonus;
    }

}
