/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;


import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "AEAGRUPO", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"ID_AEACLASE", "CODIGO"})})
public class AeagrupoEntity {

    @Column(name = "ID_AEAGRUPO", table = "AEAGRUPO", nullable = false)
    @Id
    private Integer idAeagrupo;

    @Column(name = "ID_AEACLASE", table = "AEAGRUPO", nullable = false)
    @Basic(optional = false)
    private int idAeaclase;

    @Column(name = "GUID", table = "AEAGRUPO", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "AEAGRUPO", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "AEAGRUPO")
    @Basic
    private String dtCad;

    @Column(name = "DT_ALT", table = "AEAGRUPO")
    @Basic
    private String dtAlt;

    @Column(name = "CT_INTEG", table = "AEAGRUPO")
    @Basic
    private Integer ctInteg;

    @Column(name = "CODIGO", table = "AEAGRUPO", nullable = false)
    @Basic(optional = false)
    private int codigo;

    @Column(name = "DESCRICAO", table = "AEAGRUPO", nullable = false, length = 60)
    @Basic(optional = false)
    private String descricao;

    public Integer getIdAeagrupo() {
        return this.idAeagrupo;
    }

    public void setIdAeagrupo(Integer idAeagrupo) {
        this.idAeagrupo = idAeagrupo;
    }

    public int getIdAeaclase() {
        return this.idAeaclase;
    }

    public void setIdAeaclase(int idAeaclase) {
        this.idAeaclase = idAeaclase;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public String getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(String dtCad) {
        this.dtCad = dtCad;
    }

    public String getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(String dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

}
