/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;


import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "AEAITTRA")
public class AeaittraEntity {

    @Column(name = "ID_AEAITTRA", table = "AEAITTRA", nullable = false)
    @Id
    private Integer idAeaittra;

    @Column(name = "ID_AEATRANS", table = "AEAITTRA", nullable = false)
    @Basic(optional = false)
    private int idAeatrans;

    @Column(name = "ID_AEAESTOQ_ORIGEM", table = "AEAITTRA", nullable = false)
    @Basic(optional = false)
    private int idAeaestoqOrigem;

    @Column(name = "ID_AEAESTOQ_DESTINO", table = "AEAITTRA", nullable = false)
    @Basic(optional = false)
    private int idAeaestoqDestino;

    @Column(name = "ID_AEAUNVEN", table = "AEAITTRA", nullable = false)
    @Basic(optional = false)
    private int idAeaunven;

    @Column(name = "GUID", table = "AEAITTRA", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "AEAITTRA", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "AEAITTRA")
    @Basic
    private String dtCad;

    @Column(name = "DT_ALT", table = "AEAITTRA")
    @Basic
    private String dtAlt;

    @Column(name = "CT_INTEG", table = "AEAITTRA")
    @Basic
    private Integer ctInteg;

    @Column(name = "DT_TRANSF", table = "AEAITTRA")
    @Basic
        private String dtTransf;

    @Column(name = "QUANTIDADE", table = "AEAITTRA", nullable = false)
    @Basic(optional = false)
    private double quantidade;

    @Column(name = "FLAG", table = "AEAITTRA", nullable = false)
    @Basic(optional = false)
    private int flag;

    @Column(name = "EST_ORIGEM", table = "AEAITTRA")
    @Basic
    private Character estOrigem;

    @Column(name = "EST_DESTINO", table = "AEAITTRA")
    @Basic
    private Character estDestino;

    public Integer getIdAeaittra() {
        return this.idAeaittra;
    }

    public void setIdAeaittra(Integer idAeaittra) {
        this.idAeaittra = idAeaittra;
    }

    public int getIdAeatrans() {
        return this.idAeatrans;
    }

    public void setIdAeatrans(int idAeatrans) {
        this.idAeatrans = idAeatrans;
    }

    public int getIdAeaestoqOrigem() {
        return this.idAeaestoqOrigem;
    }

    public void setIdAeaestoqOrigem(int idAeaestoqOrigem) {
        this.idAeaestoqOrigem = idAeaestoqOrigem;
    }

    public int getIdAeaestoqDestino() {
        return this.idAeaestoqDestino;
    }

    public void setIdAeaestoqDestino(int idAeaestoqDestino) {
        this.idAeaestoqDestino = idAeaestoqDestino;
    }

    public int getIdAeaunven() {
        return this.idAeaunven;
    }

    public void setIdAeaunven(int idAeaunven) {
        this.idAeaunven = idAeaunven;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public String getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(String dtCad) {
        this.dtCad = dtCad;
    }

    public String getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(String dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public String getDtTransf() {
        return this.dtTransf;
    }

    public void setDtTransf(String dtTransf) {
        this.dtTransf = dtTransf;
    }

    public double getQuantidade() {
        return this.quantidade;
    }

    public void setQuantidade(double quantidade) {
        this.quantidade = quantidade;
    }

    public int getFlag() {
        return this.flag;
    }

    public void setFlag(int flag) {
        this.flag = flag;
    }

    public Character getEstOrigem() {
        return this.estOrigem;
    }

    public void setEstOrigem(Character estOrigem) {
        this.estOrigem = estOrigem;
    }

    public Character getEstDestino() {
        return this.estDestino;
    }

    public void setEstDestino(Character estDestino) {
        this.estDestino = estDestino;
    }

}
