/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "AEAITPED", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"ID_AEAPEDID", "SEQUENCIA"})})
public class AeaitpedEntity {

    @Column(name = "ID_AEAITPED", table = "AEAITPED", nullable = false)
    @Id
    private Integer idAeaitped;

    @Column(name = "ID_AEAPEDID", table = "AEAITPED", nullable = false)
    @Basic(optional = false)
    private int idAeapedid;

    @Column(name = "ID_AEAPLOJA", table = "AEAITPED", nullable = false)
    @Basic(optional = false)
    private int idAeaploja;

    @Column(name = "ID_AEAGRDPL", table = "AEAITPED")
    @Basic
    private Integer idAeagrdpl;

    @Column(name = "ID_AEAUNVEN", table = "AEAITPED", nullable = false)
    @Basic(optional = false)
    private int idAeaunven;

    @Column(name = "ID_AEAITENT", table = "AEAITPED")
    @Basic
    private Integer idAeaitent;

    @Column(name = "GUID", table = "AEAITPED", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "AEAITPED", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "AEAITPED")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtCad;

    @Column(name = "DT_ALT", table = "AEAITPED")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtAlt;

    @Column(name = "CT_INTEG", table = "AEAITPED")
    @Basic
    private Integer ctInteg;

    @Column(name = "DT_PEDIDO", table = "AEAITPED", nullable = false)
    @Basic(optional = false)
    @Temporal(TemporalType.DATE)
    private Date dtPedido;

    @Column(name = "SEQUENCIA", table = "AEAITPED", nullable = false)
    @Basic(optional = false)
    private int sequencia;

    @Column(name = "VL_PRODUTO", table = "AEAITPED", nullable = false)
    @Basic(optional = false)
    private double vlProduto;

    @Column(name = "QUANTIDADE", table = "AEAITPED", nullable = false)
    @Basic(optional = false)
    private double quantidade;

    @Column(name = "QUANT_CONF", table = "AEAITPED", nullable = false)
    @Basic(optional = false)
    private double quantConf;

    @Column(name = "QUANT_ATENDIDA", table = "AEAITPED", nullable = false)
    @Basic(optional = false)
    private double quantAtendida;

    @Column(name = "QUANT_CANCELADA", table = "AEAITPED", nullable = false)
    @Basic(optional = false)
    private double quantCancelada;

    @Column(name = "TIPO_PRODUTO", table = "AEAITPED")
    @Basic
    private Character tipoProduto;

    @Column(name = "OBS", table = "AEAITPED")
    @Lob
    @Basic
    private byte[] obs;

    public Integer getIdAeaitped() {
        return this.idAeaitped;
    }

    public void setIdAeaitped(Integer idAeaitped) {
        this.idAeaitped = idAeaitped;
    }

    public int getIdAeapedid() {
        return this.idAeapedid;
    }

    public void setIdAeapedid(int idAeapedid) {
        this.idAeapedid = idAeapedid;
    }

    public int getIdAeaploja() {
        return this.idAeaploja;
    }

    public void setIdAeaploja(int idAeaploja) {
        this.idAeaploja = idAeaploja;
    }

    public Integer getIdAeagrdpl() {
        return this.idAeagrdpl;
    }

    public void setIdAeagrdpl(Integer idAeagrdpl) {
        this.idAeagrdpl = idAeagrdpl;
    }

    public int getIdAeaunven() {
        return this.idAeaunven;
    }

    public void setIdAeaunven(int idAeaunven) {
        this.idAeaunven = idAeaunven;
    }

    public Integer getIdAeaitent() {
        return this.idAeaitent;
    }

    public void setIdAeaitent(Integer idAeaitent) {
        this.idAeaitent = idAeaitent;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public Date getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(Date dtCad) {
        this.dtCad = dtCad;
    }

    public Date getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(Date dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public Date getDtPedido() {
        return this.dtPedido;
    }

    public void setDtPedido(Date dtPedido) {
        this.dtPedido = dtPedido;
    }

    public int getSequencia() {
        return this.sequencia;
    }

    public void setSequencia(int sequencia) {
        this.sequencia = sequencia;
    }

    public double getVlProduto() {
        return this.vlProduto;
    }

    public void setVlProduto(double vlProduto) {
        this.vlProduto = vlProduto;
    }

    public double getQuantidade() {
        return this.quantidade;
    }

    public void setQuantidade(double quantidade) {
        this.quantidade = quantidade;
    }

    public double getQuantConf() {
        return this.quantConf;
    }

    public void setQuantConf(double quantConf) {
        this.quantConf = quantConf;
    }

    public double getQuantAtendida() {
        return this.quantAtendida;
    }

    public void setQuantAtendida(double quantAtendida) {
        this.quantAtendida = quantAtendida;
    }

    public double getQuantCancelada() {
        return this.quantCancelada;
    }

    public void setQuantCancelada(double quantCancelada) {
        this.quantCancelada = quantCancelada;
    }

    public Character getTipoProduto() {
        return this.tipoProduto;
    }

    public void setTipoProduto(Character tipoProduto) {
        this.tipoProduto = tipoProduto;
    }

    public byte[] getObs() {
        return this.obs;
    }

    public void setObs(byte[] obs) {
        this.obs = obs;
    }

}
