/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;


import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "AEAITCNF")
public class AeaitcnfEntity {

    @Column(name = "ID_AEAITCNF", table = "AEAITCNF", nullable = false)
    @Id
    private Integer idAeaitcnf;

    @Column(name = "ID_AEAITSAI", table = "AEAITCNF")
    @Basic
    private Integer idAeaitsai;

    @Column(name = "ID_AEAITROM", table = "AEAITCNF")
    @Basic
    private Integer idAeaitrom;

    @Column(name = "ID_AEAITENT", table = "AEAITCNF")
    @Basic
    private Integer idAeaitent;

    @Column(name = "GUID", table = "AEAITCNF", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "AEAITCNF", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "AEAITCNF")
    @Basic
    private String dtCad;

    @Column(name = "DT_ALT", table = "AEAITCNF")
    @Basic
    private String dtAlt;

    @Column(name = "CT_INTEG", table = "AEAITCNF")
    @Basic
    private Integer ctInteg;

    @Column(name = "DT_CONFERENCIA", table = "AEAITCNF")
    @Basic
    private String dtConferencia;

    @Column(name = "QUANTIDADE", table = "AEAITCNF", nullable = false)
    @Basic(optional = false)
    private double quantidade;

    @Column(name = "OBS", table = "AEAITCNF")
    @Lob
    @Basic
    private byte[] obs;

    @Column(name = "SITUACAO", table = "AEAITCNF")
    @Basic
    private Character situacao;

    @Column(name = "BAIXA_POR_CONF", table = "AEAITCNF")
    @Basic
    private Character baixaPorConf;

    public Integer getIdAeaitcnf() {
        return this.idAeaitcnf;
    }

    public void setIdAeaitcnf(Integer idAeaitcnf) {
        this.idAeaitcnf = idAeaitcnf;
    }

    public Integer getIdAeaitsai() {
        return this.idAeaitsai;
    }

    public void setIdAeaitsai(Integer idAeaitsai) {
        this.idAeaitsai = idAeaitsai;
    }

    public Integer getIdAeaitrom() {
        return this.idAeaitrom;
    }

    public void setIdAeaitrom(Integer idAeaitrom) {
        this.idAeaitrom = idAeaitrom;
    }

    public Integer getIdAeaitent() {
        return this.idAeaitent;
    }

    public void setIdAeaitent(Integer idAeaitent) {
        this.idAeaitent = idAeaitent;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public String getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(String dtCad) {
        this.dtCad = dtCad;
    }

    public String getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(String dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public String getDtConferencia() {
        return this.dtConferencia;
    }

    public void setDtConferencia(String dtConferencia) {
        this.dtConferencia = dtConferencia;
    }

    public double getQuantidade() {
        return this.quantidade;
    }

    public void setQuantidade(double quantidade) {
        this.quantidade = quantidade;
    }

    public byte[] getObs() {
        return this.obs;
    }

    public void setObs(byte[] obs) {
        this.obs = obs;
    }

    public Character getSituacao() {
        return this.situacao;
    }

    public void setSituacao(Character situacao) {
        this.situacao = situacao;
    }

    public Character getBaixaPorConf() {
        return this.baixaPorConf;
    }

    public void setBaixaPorConf(Character baixaPorConf) {
        this.baixaPorConf = baixaPorConf;
    }

}
