/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "AEAMAPAF")
public class AeamapafEntity {

    @Column(name = "ID_AEAMAPAF", table = "AEAMAPAF", nullable = false)
    @Id
    private Integer idAeamapaf;

    @Column(name = "ID_SMAEMPRE", table = "AEAMAPAF", nullable = false)
    @Basic(optional = false)
    private int idSmaempre;

    @Column(name = "GUID", table = "AEAMAPAF", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "AEAMAPAF", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "AEAMAPAF")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtCad;

    @Column(name = "DT_ALT", table = "AEAMAPAF")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtAlt;

    @Column(name = "CT_INTEG", table = "AEAMAPAF")
    @Basic
    private Integer ctInteg;

    @Column(name = "NUMERO_MAPA", table = "AEAMAPAF")
    @Basic
    private Integer numeroMapa;

    @Column(name = "DATA_MAPA", table = "AEAMAPAF")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date dataMapa;

    @Column(name = "VL_MOVIMENTO_DIA", table = "AEAMAPAF", nullable = false)
    @Basic(optional = false)
    private double vlMovimentoDia;

    @Column(name = "VL_BASE_CALCULO", table = "AEAMAPAF", nullable = false)
    @Basic(optional = false)
    private double vlBaseCalculo;

    @Column(name = "VL_IMPOSTO_DEBITADO", table = "AEAMAPAF", nullable = false)
    @Basic(optional = false)
    private double vlImpostoDebitado;

    @Column(name = "VL_ISENTO", table = "AEAMAPAF", nullable = false)
    @Basic(optional = false)
    private double vlIsento;

    @Column(name = "VL_NAO_INCID", table = "AEAMAPAF", nullable = false)
    @Basic(optional = false)
    private double vlNaoIncid;

    @Column(name = "VL_SUBST_TRIB", table = "AEAMAPAF", nullable = false)
    @Basic(optional = false)
    private double vlSubstTrib;

    @Column(name = "VL_DESCONTO", table = "AEAMAPAF", nullable = false)
    @Basic(optional = false)
    private double vlDesconto;

    @Column(name = "VL_CANCELAMENTO", table = "AEAMAPAF", nullable = false)
    @Basic(optional = false)
    private double vlCancelamento;

    @Column(name = "VL_OUTROS_RECEB", table = "AEAMAPAF", nullable = false)
    @Basic(optional = false)
    private double vlOutrosReceb;

    @Column(name = "VL_BASE_CALC_SERV", table = "AEAMAPAF", nullable = false)
    @Basic(optional = false)
    private double vlBaseCalcServ;

    @Column(name = "VL_IMPOSTO_DEB_SERV", table = "AEAMAPAF", nullable = false)
    @Basic(optional = false)
    private double vlImpostoDebServ;

    @Column(name = "VL_SUB_TRIB_SERV", table = "AEAMAPAF", nullable = false)
    @Basic(optional = false)
    private double vlSubTribServ;

    @Column(name = "VL_ISENCAO_SERV", table = "AEAMAPAF", nullable = false)
    @Basic(optional = false)
    private double vlIsencaoServ;

    @Column(name = "VL_NAO_INCID_SERV", table = "AEAMAPAF", nullable = false)
    @Basic(optional = false)
    private double vlNaoIncidServ;

    @Column(name = "VL_DESCONTO_SERV", table = "AEAMAPAF", nullable = false)
    @Basic(optional = false)
    private double vlDescontoServ;

    @Column(name = "VL_CANCELAMENTO_SERV", table = "AEAMAPAF", nullable = false)
    @Basic(optional = false)
    private double vlCancelamentoServ;

    @Column(name = "FC_VL_CONTABIL_ICMS", table = "AEAMAPAF", precision = 15)
    @Basic
    private Double fcVlContabilIcms;

    @Column(name = "FC_VL_CONTABIL_ISS", table = "AEAMAPAF", precision = 15)
    @Basic
    private Double fcVlContabilIss;

    @Column(name = "OBSERVACAO", table = "AEAMAPAF")
    @Lob
    @Basic
    private byte[] observacao;

    public Integer getIdAeamapaf() {
        return this.idAeamapaf;
    }

    public void setIdAeamapaf(Integer idAeamapaf) {
        this.idAeamapaf = idAeamapaf;
    }

    public int getIdSmaempre() {
        return this.idSmaempre;
    }

    public void setIdSmaempre(int idSmaempre) {
        this.idSmaempre = idSmaempre;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public Date getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(Date dtCad) {
        this.dtCad = dtCad;
    }

    public Date getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(Date dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public Integer getNumeroMapa() {
        return this.numeroMapa;
    }

    public void setNumeroMapa(Integer numeroMapa) {
        this.numeroMapa = numeroMapa;
    }

    public Date getDataMapa() {
        return this.dataMapa;
    }

    public void setDataMapa(Date dataMapa) {
        this.dataMapa = dataMapa;
    }

    public double getVlMovimentoDia() {
        return this.vlMovimentoDia;
    }

    public void setVlMovimentoDia(double vlMovimentoDia) {
        this.vlMovimentoDia = vlMovimentoDia;
    }

    public double getVlBaseCalculo() {
        return this.vlBaseCalculo;
    }

    public void setVlBaseCalculo(double vlBaseCalculo) {
        this.vlBaseCalculo = vlBaseCalculo;
    }

    public double getVlImpostoDebitado() {
        return this.vlImpostoDebitado;
    }

    public void setVlImpostoDebitado(double vlImpostoDebitado) {
        this.vlImpostoDebitado = vlImpostoDebitado;
    }

    public double getVlIsento() {
        return this.vlIsento;
    }

    public void setVlIsento(double vlIsento) {
        this.vlIsento = vlIsento;
    }

    public double getVlNaoIncid() {
        return this.vlNaoIncid;
    }

    public void setVlNaoIncid(double vlNaoIncid) {
        this.vlNaoIncid = vlNaoIncid;
    }

    public double getVlSubstTrib() {
        return this.vlSubstTrib;
    }

    public void setVlSubstTrib(double vlSubstTrib) {
        this.vlSubstTrib = vlSubstTrib;
    }

    public double getVlDesconto() {
        return this.vlDesconto;
    }

    public void setVlDesconto(double vlDesconto) {
        this.vlDesconto = vlDesconto;
    }

    public double getVlCancelamento() {
        return this.vlCancelamento;
    }

    public void setVlCancelamento(double vlCancelamento) {
        this.vlCancelamento = vlCancelamento;
    }

    public double getVlOutrosReceb() {
        return this.vlOutrosReceb;
    }

    public void setVlOutrosReceb(double vlOutrosReceb) {
        this.vlOutrosReceb = vlOutrosReceb;
    }

    public double getVlBaseCalcServ() {
        return this.vlBaseCalcServ;
    }

    public void setVlBaseCalcServ(double vlBaseCalcServ) {
        this.vlBaseCalcServ = vlBaseCalcServ;
    }

    public double getVlImpostoDebServ() {
        return this.vlImpostoDebServ;
    }

    public void setVlImpostoDebServ(double vlImpostoDebServ) {
        this.vlImpostoDebServ = vlImpostoDebServ;
    }

    public double getVlSubTribServ() {
        return this.vlSubTribServ;
    }

    public void setVlSubTribServ(double vlSubTribServ) {
        this.vlSubTribServ = vlSubTribServ;
    }

    public double getVlIsencaoServ() {
        return this.vlIsencaoServ;
    }

    public void setVlIsencaoServ(double vlIsencaoServ) {
        this.vlIsencaoServ = vlIsencaoServ;
    }

    public double getVlNaoIncidServ() {
        return this.vlNaoIncidServ;
    }

    public void setVlNaoIncidServ(double vlNaoIncidServ) {
        this.vlNaoIncidServ = vlNaoIncidServ;
    }

    public double getVlDescontoServ() {
        return this.vlDescontoServ;
    }

    public void setVlDescontoServ(double vlDescontoServ) {
        this.vlDescontoServ = vlDescontoServ;
    }

    public double getVlCancelamentoServ() {
        return this.vlCancelamentoServ;
    }

    public void setVlCancelamentoServ(double vlCancelamentoServ) {
        this.vlCancelamentoServ = vlCancelamentoServ;
    }

    public Double getFcVlContabilIcms() {
        return this.fcVlContabilIcms;
    }

    public void setFcVlContabilIcms(Double fcVlContabilIcms) {
        this.fcVlContabilIcms = fcVlContabilIcms;
    }

    public Double getFcVlContabilIss() {
        return this.fcVlContabilIss;
    }

    public void setFcVlContabilIss(Double fcVlContabilIss) {
        this.fcVlContabilIss = fcVlContabilIss;
    }

    public byte[] getObservacao() {
        return this.observacao;
    }

    public void setObservacao(byte[] observacao) {
        this.observacao = observacao;
    }

}
