/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "AEAPRODU", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"CODIGO"})})
public class AeaproduEntity {

    @Column(name = "ID_AEAPRODU", table = "AEAPRODU", nullable = false)
    @Id
    private Integer idAeaprodu;

    @Column(name = "ID_AEAFAMIL", table = "AEAPRODU")
    @Basic
    private Integer idAeafamil;

    @Column(name = "ID_AEACLASE", table = "AEAPRODU")
    @Basic
    private Integer idAeaclase;

    @Column(name = "ID_AEAGRUPO", table = "AEAPRODU")
    @Basic
    private Integer idAeagrupo;

    @Column(name = "ID_AEASGRUP", table = "AEAPRODU")
    @Basic
    private Integer idAeasgrup;

    @Column(name = "ID_AEAMARCA", table = "AEAPRODU")
    @Basic
    private Integer idAeamarca;

    @Column(name = "ID_AEAUNVEN", table = "AEAPRODU", nullable = false)
    @Basic(optional = false)
    private int idAeaunven;

    @Column(name = "ID_AEAPESOS", table = "AEAPRODU")
    @Basic
    private Integer idAeapesos;

    @Column(name = "ID_AEATPGRD", table = "AEAPRODU")
    @Basic
    private Integer idAeatpgrd;

    @Column(name = "ID_AEACODOM", table = "AEAPRODU", nullable = false)
    @Basic(optional = false)
    private int idAeacodom;

    @Column(name = "ID_CFAMODEQ", table = "AEAPRODU")
    @Basic
    private Integer idCfamodeq;

    @Column(name = "ID_AEACODGE", table = "AEAPRODU")
    @Basic
    private Integer idAeacodge;

    @Column(name = "ID_AEALISSE", table = "AEAPRODU")
    @Basic
    private Integer idAealisse;

    @Column(name = "GUID", table = "AEAPRODU", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "AEAPRODU", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "AEAPRODU")
    @Basic
    private String dtCad;

    @Column(name = "DT_ALT", table = "AEAPRODU")
    @Basic
    private String dtAlt;

    @Column(name = "CT_INTEG", table = "AEAPRODU")
    @Basic
    private Integer ctInteg;

    @Column(name = "DESCRICAO", table = "AEAPRODU", nullable = false, length = 50)
    @Basic(optional = false)
    private String descricao;

    @Column(name = "DESCRICAO_AUXILIAR", table = "AEAPRODU")
    @Basic
    private String descricaoAuxiliar;

    @Column(name = "DESCRICAO_MASCARA", table = "AEAPRODU", length = 50)
    @Basic
    private String descricaoMascara;

    @Column(name = "CODIGO", table = "AEAPRODU", nullable = false)
    @Basic(optional = false)
    private int codigo;

    @Column(name = "CODIGO_ESTRUTURAL", table = "AEAPRODU", length = 20)
    @Basic
    private String codigoEstrutural;

    @Column(name = "REFERENCIA", table = "AEAPRODU", length = 20)
    @Basic
    private String referencia;

    @Column(name = "CODIGO_BARRAS", table = "AEAPRODU", length = 20)
    @Basic
    private String codigoBarras;

    @Column(name = "ABREV_CF", table = "AEAPRODU", length = 2)
    @Basic
    private String abrevCf;

    @Column(name = "CLASSIF_FISCAL", table = "AEAPRODU")
    @Basic
    private Integer classifFiscal;

    @Column(name = "PESO_LIQUIDO", table = "AEAPRODU", nullable = false)
    @Basic(optional = false)
    private double pesoLiquido;

    @Column(name = "PESO_BRUTO", table = "AEAPRODU", nullable = false)
    @Basic(optional = false)
    private double pesoBruto;

    @Column(name = "ATIVO", table = "AEAPRODU", nullable = false)
    @Basic(optional = false)
    private Character ativo;

    @Column(name = "TIPO", table = "AEAPRODU")
    @Basic
    private Character tipo;

    @Column(name = "GENERO", table = "AEAPRODU")
    @Basic
    private Character genero;

    @Column(name = "VALIDADE", table = "AEAPRODU")
    @Basic
    private Character validade;

    @Column(name = "GARANTIA", table = "AEAPRODU")
    @Basic
    private Character garantia;

    @Column(name = "CONTROLE_SERIAL", table = "AEAPRODU")
    @Basic
    private Character controleSerial;

    @Column(name = "SAI_NA_NF", table = "AEAPRODU")
    @Basic
    private Character saiNaNf;

    @Column(name = "AGRUPADOR_PRECO", table = "AEAPRODU", length = 20)
    @Basic
    private String agrupadorPreco;

    @Column(name = "TIPO_ITEM", table = "AEAPRODU")
    @Basic
    private Character tipoItem;

    @Column(name = "EX_IPI", table = "AEAPRODU", length = 3)
    @Basic
    private String exIpi;

    @Column(name = "CODIGO_ANP", table = "AEAPRODU", length = 13)
    @Basic
    private String codigoAnp;

    @Column(name = "TIPO_ITEM_EFD", table = "AEAPRODU")
    @Basic
    private Character tipoItemEfd;

    @Column(name = "CODIGO_NCM", table = "AEAPRODU", length = 13)
    @Basic
    private String codigoNcm;

    @Column(name = "SIMILARIDADE", table = "AEAPRODU")
    @Basic
    private Integer similaridade;

    @Column(name = "ROMANEIA", table = "AEAPRODU")
    @Basic
    private Character romaneia;

    @Column(name = "FCI", table = "AEAPRODU", length = 40)
    @Basic
    private String fci;

    @Column(name = "LUCRO_VARE", table = "AEAPRODU", nullable = false)
    @Basic(optional = false)
    private double lucroVare;

    @Column(name = "LUCRO_ATAC", table = "AEAPRODU", nullable = false)
    @Basic(optional = false)
    private double lucroAtac;

    @Column(name = "MVA", table = "AEAPRODU", nullable = false)
    @Basic(optional = false)
    private double mva;

    @Column(name = "CEST", table = "AEAPRODU", length = 13)
    @Basic
    private String cest;

    public Integer getIdAeaprodu() {
        return this.idAeaprodu;
    }

    public void setIdAeaprodu(Integer idAeaprodu) {
        this.idAeaprodu = idAeaprodu;
    }

    public Integer getIdAeafamil() {
        return this.idAeafamil;
    }

    public void setIdAeafamil(Integer idAeafamil) {
        this.idAeafamil = idAeafamil;
    }

    public Integer getIdAeaclase() {
        return this.idAeaclase;
    }

    public void setIdAeaclase(Integer idAeaclase) {
        this.idAeaclase = idAeaclase;
    }

    public Integer getIdAeagrupo() {
        return this.idAeagrupo;
    }

    public void setIdAeagrupo(Integer idAeagrupo) {
        this.idAeagrupo = idAeagrupo;
    }

    public Integer getIdAeasgrup() {
        return this.idAeasgrup;
    }

    public void setIdAeasgrup(Integer idAeasgrup) {
        this.idAeasgrup = idAeasgrup;
    }

    public Integer getIdAeamarca() {
        return this.idAeamarca;
    }

    public void setIdAeamarca(Integer idAeamarca) {
        this.idAeamarca = idAeamarca;
    }

    public int getIdAeaunven() {
        return this.idAeaunven;
    }

    public void setIdAeaunven(int idAeaunven) {
        this.idAeaunven = idAeaunven;
    }

    public Integer getIdAeapesos() {
        return this.idAeapesos;
    }

    public void setIdAeapesos(Integer idAeapesos) {
        this.idAeapesos = idAeapesos;
    }

    public Integer getIdAeatpgrd() {
        return this.idAeatpgrd;
    }

    public void setIdAeatpgrd(Integer idAeatpgrd) {
        this.idAeatpgrd = idAeatpgrd;
    }

    public int getIdAeacodom() {
        return this.idAeacodom;
    }

    public void setIdAeacodom(int idAeacodom) {
        this.idAeacodom = idAeacodom;
    }

    public Integer getIdCfamodeq() {
        return this.idCfamodeq;
    }

    public void setIdCfamodeq(Integer idCfamodeq) {
        this.idCfamodeq = idCfamodeq;
    }

    public Integer getIdAeacodge() {
        return this.idAeacodge;
    }

    public void setIdAeacodge(Integer idAeacodge) {
        this.idAeacodge = idAeacodge;
    }

    public Integer getIdAealisse() {
        return this.idAealisse;
    }

    public void setIdAealisse(Integer idAealisse) {
        this.idAealisse = idAealisse;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public String getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(String dtCad) {
        this.dtCad = dtCad;
    }

    public String getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(String dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public String getDescricaoAuxiliar() {
        return this.descricaoAuxiliar;
    }

    public void setDescricaoAuxiliar(String descricaoAuxiliar) {
        this.descricaoAuxiliar = descricaoAuxiliar;
    }

    public String getDescricaoMascara() {
        return this.descricaoMascara;
    }

    public void setDescricaoMascara(String descricaoMascara) {
        this.descricaoMascara = descricaoMascara;
    }

    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public String getCodigoEstrutural() {
        return this.codigoEstrutural;
    }

    public void setCodigoEstrutural(String codigoEstrutural) {
        this.codigoEstrutural = codigoEstrutural;
    }

    public String getReferencia() {
        return this.referencia;
    }

    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }

    public String getCodigoBarras() {
        return this.codigoBarras;
    }

    public void setCodigoBarras(String codigoBarras) {
        this.codigoBarras = codigoBarras;
    }

    public String getAbrevCf() {
        return this.abrevCf;
    }

    public void setAbrevCf(String abrevCf) {
        this.abrevCf = abrevCf;
    }

    public Integer getClassifFiscal() {
        return this.classifFiscal;
    }

    public void setClassifFiscal(Integer classifFiscal) {
        this.classifFiscal = classifFiscal;
    }

    public double getPesoLiquido() {
        return this.pesoLiquido;
    }

    public void setPesoLiquido(double pesoLiquido) {
        this.pesoLiquido = pesoLiquido;
    }

    public double getPesoBruto() {
        return this.pesoBruto;
    }

    public void setPesoBruto(double pesoBruto) {
        this.pesoBruto = pesoBruto;
    }

    public Character getAtivo() {
        return this.ativo;
    }

    public void setAtivo(Character ativo) {
        this.ativo = ativo;
    }

    public Character getTipo() {
        return this.tipo;
    }

    public void setTipo(Character tipo) {
        this.tipo = tipo;
    }

    public Character getGenero() {
        return this.genero;
    }

    public void setGenero(Character genero) {
        this.genero = genero;
    }

    public Character getValidade() {
        return this.validade;
    }

    public void setValidade(Character validade) {
        this.validade = validade;
    }

    public Character getGarantia() {
        return this.garantia;
    }

    public void setGarantia(Character garantia) {
        this.garantia = garantia;
    }

    public Character getControleSerial() {
        return this.controleSerial;
    }

    public void setControleSerial(Character controleSerial) {
        this.controleSerial = controleSerial;
    }

    public Character getSaiNaNf() {
        return this.saiNaNf;
    }

    public void setSaiNaNf(Character saiNaNf) {
        this.saiNaNf = saiNaNf;
    }

    public String getAgrupadorPreco() {
        return this.agrupadorPreco;
    }

    public void setAgrupadorPreco(String agrupadorPreco) {
        this.agrupadorPreco = agrupadorPreco;
    }

    public Character getTipoItem() {
        return this.tipoItem;
    }

    public void setTipoItem(Character tipoItem) {
        this.tipoItem = tipoItem;
    }

    public String getExIpi() {
        return this.exIpi;
    }

    public void setExIpi(String exIpi) {
        this.exIpi = exIpi;
    }

    public String getCodigoAnp() {
        return this.codigoAnp;
    }

    public void setCodigoAnp(String codigoAnp) {
        this.codigoAnp = codigoAnp;
    }

    public Character getTipoItemEfd() {
        return this.tipoItemEfd;
    }

    public void setTipoItemEfd(Character tipoItemEfd) {
        this.tipoItemEfd = tipoItemEfd;
    }

    public String getCodigoNcm() {
        return this.codigoNcm;
    }

    public void setCodigoNcm(String codigoNcm) {
        this.codigoNcm = codigoNcm;
    }

    public Integer getSimilaridade() {
        return this.similaridade;
    }

    public void setSimilaridade(Integer similaridade) {
        this.similaridade = similaridade;
    }

    public Character getRomaneia() {
        return this.romaneia;
    }

    public void setRomaneia(Character romaneia) {
        this.romaneia = romaneia;
    }

    public String getFci() {
        return this.fci;
    }

    public void setFci(String fci) {
        this.fci = fci;
    }

    public double getLucroVare() {
        return this.lucroVare;
    }

    public void setLucroVare(double lucroVare) {
        this.lucroVare = lucroVare;
    }

    public double getLucroAtac() {
        return this.lucroAtac;
    }

    public void setLucroAtac(double lucroAtac) {
        this.lucroAtac = lucroAtac;
    }

    public double getMva() {
        return this.mva;
    }

    public void setMva(double mva) {
        this.mva = mva;
    }

    public String getCest() {
        return this.cest;
    }

    public void setCest(String cest) {
        this.cest = cest;
    }

}
