/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;


import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "AEAPRFOR")
public class AeaprforEntity {

    @Column(name = "ID_AEAPRFOR", table = "AEAPRFOR", nullable = false)
    @Id
    private Integer idAeaprfor;

    @Column(name = "ID_AEAPRODU", table = "AEAPRFOR")
    @Basic
    private Integer idAeaprodu;

    @Column(name = "ID_CFACLIFO", table = "AEAPRFOR")
    @Basic
    private Integer idCfaclifo;

    @Column(name = "ID_AEAUNVEN", table = "AEAPRFOR")
    @Basic
    private Integer idAeaunven;

    @Column(name = "GUID", table = "AEAPRFOR", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "AEAPRFOR", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "AEAPRFOR")
    @Basic
    private String dtCad;

    @Column(name = "DT_ALT", table = "AEAPRFOR")
    @Basic
    private String dtAlt;

    @Column(name = "CT_INTEG", table = "AEAPRFOR")
    @Basic
    private Integer ctInteg;

    @Column(name = "DT_ULT_COMPRA", table = "AEAPRFOR")
    @Basic
        private String dtUltCompra;

    @Column(name = "NUM_COMPRAS", table = "AEAPRFOR", nullable = false)
    @Basic(optional = false)
    private int numCompras;

    @Column(name = "PED_ENTREGA", table = "AEAPRFOR", nullable = false)
    @Basic(optional = false)
    private int pedEntrega;

    @Column(name = "QUANTIDADE", table = "AEAPRFOR", nullable = false)
    @Basic(optional = false)
    private double quantidade;

    @Column(name = "VALOR", table = "AEAPRFOR", nullable = false)
    @Basic(optional = false)
    private double valor;

    @Column(name = "REFERENCIA", table = "AEAPRFOR", length = 20)
    @Basic
    private String referencia;

    @Column(name = "CODIGO_BARRAS", table = "AEAPRFOR", length = 20)
    @Basic
    private String codigoBarras;

    @Column(name = "UN_IN", table = "AEAPRFOR", length = 5)
    @Basic
    private String unIn;

    @Column(name = "MODULO", table = "AEAPRFOR", nullable = false)
    @Basic(optional = false)
    private double modulo;

    @Column(name = "CODIGO", table = "AEAPRFOR")
    @Basic
    private Integer codigo;

    public Integer getIdAeaprfor() {
        return this.idAeaprfor;
    }

    public void setIdAeaprfor(Integer idAeaprfor) {
        this.idAeaprfor = idAeaprfor;
    }

    public Integer getIdAeaprodu() {
        return this.idAeaprodu;
    }

    public void setIdAeaprodu(Integer idAeaprodu) {
        this.idAeaprodu = idAeaprodu;
    }

    public Integer getIdCfaclifo() {
        return this.idCfaclifo;
    }

    public void setIdCfaclifo(Integer idCfaclifo) {
        this.idCfaclifo = idCfaclifo;
    }

    public Integer getIdAeaunven() {
        return this.idAeaunven;
    }

    public void setIdAeaunven(Integer idAeaunven) {
        this.idAeaunven = idAeaunven;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public String getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(String dtCad) {
        this.dtCad = dtCad;
    }

    public String getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(String dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public String getDtUltCompra() {
        return this.dtUltCompra;
    }

    public void setDtUltCompra(String dtUltCompra) {
        this.dtUltCompra = dtUltCompra;
    }

    public int getNumCompras() {
        return this.numCompras;
    }

    public void setNumCompras(int numCompras) {
        this.numCompras = numCompras;
    }

    public int getPedEntrega() {
        return this.pedEntrega;
    }

    public void setPedEntrega(int pedEntrega) {
        this.pedEntrega = pedEntrega;
    }

    public double getQuantidade() {
        return this.quantidade;
    }

    public void setQuantidade(double quantidade) {
        this.quantidade = quantidade;
    }

    public double getValor() {
        return this.valor;
    }

    public void setValor(double valor) {
        this.valor = valor;
    }

    public String getReferencia() {
        return this.referencia;
    }

    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }

    public String getCodigoBarras() {
        return this.codigoBarras;
    }

    public void setCodigoBarras(String codigoBarras) {
        this.codigoBarras = codigoBarras;
    }

    public String getUnIn() {
        return this.unIn;
    }

    public void setUnIn(String unIn) {
        this.unIn = unIn;
    }

    public double getModulo() {
        return this.modulo;
    }

    public void setModulo(double modulo) {
        this.modulo = modulo;
    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

}
