/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "AEASAZON", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"DESCRICAO"})})
public class AeasazonEntity {

    @Column(name = "ID_AEASAZON", table = "AEASAZON", nullable = false)
    @Id
    private Integer idAeasazon;

    @Column(name = "GUID", table = "AEASAZON", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "AEASAZON", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "AEASAZON")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtCad;

    @Column(name = "DT_ALT", table = "AEASAZON")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtAlt;

    @Column(name = "CT_INTEG", table = "AEASAZON")
    @Basic
    private Integer ctInteg;

    @Column(name = "DESCRICAO", table = "AEASAZON", nullable = false, length = 40)
    @Basic(optional = false)
    private String descricao;

    @Column(name = "DT_INICIO1", table = "AEASAZON")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date dtInicio1;

    @Column(name = "DT_INICIO2", table = "AEASAZON")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date dtInicio2;

    @Column(name = "DT_INICIO3", table = "AEASAZON")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date dtInicio3;

    @Column(name = "DT_FIM1", table = "AEASAZON")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date dtFim1;

    @Column(name = "DT_FIM2", table = "AEASAZON")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date dtFim2;

    @Column(name = "DT_FIM3", table = "AEASAZON")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date dtFim3;

    public Integer getIdAeasazon() {
        return this.idAeasazon;
    }

    public void setIdAeasazon(Integer idAeasazon) {
        this.idAeasazon = idAeasazon;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public Date getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(Date dtCad) {
        this.dtCad = dtCad;
    }

    public Date getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(Date dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Date getDtInicio1() {
        return this.dtInicio1;
    }

    public void setDtInicio1(Date dtInicio1) {
        this.dtInicio1 = dtInicio1;
    }

    public Date getDtInicio2() {
        return this.dtInicio2;
    }

    public void setDtInicio2(Date dtInicio2) {
        this.dtInicio2 = dtInicio2;
    }

    public Date getDtInicio3() {
        return this.dtInicio3;
    }

    public void setDtInicio3(Date dtInicio3) {
        this.dtInicio3 = dtInicio3;
    }

    public Date getDtFim1() {
        return this.dtFim1;
    }

    public void setDtFim1(Date dtFim1) {
        this.dtFim1 = dtFim1;
    }

    public Date getDtFim2() {
        return this.dtFim2;
    }

    public void setDtFim2(Date dtFim2) {
        this.dtFim2 = dtFim2;
    }

    public Date getDtFim3() {
        return this.dtFim3;
    }

    public void setDtFim3(Date dtFim3) {
        this.dtFim3 = dtFim3;
    }

}
