/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "AEATPGRD", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"DESCRICAO"})})
public class AeatpgrdEntity {

    @Column(name = "ID_AEATPGRD", table = "AEATPGRD", nullable = false)
    @Id
    private Integer idAeatpgrd;

    @Column(name = "GUID", table = "AEATPGRD", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "AEATPGRD", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "AEATPGRD")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtCad;

    @Column(name = "DT_ALT", table = "AEATPGRD")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtAlt;

    @Column(name = "CT_INTEG", table = "AEATPGRD")
    @Basic
    private Integer ctInteg;

    @Column(name = "DESCRICAO", table = "AEATPGRD", nullable = false, length = 40)
    @Basic(optional = false)
    private String descricao;

    public Integer getIdAeatpgrd() {
        return this.idAeatpgrd;
    }

    public void setIdAeatpgrd(Integer idAeatpgrd) {
        this.idAeatpgrd = idAeatpgrd;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public Date getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(Date dtCad) {
        this.dtCad = dtCad;
    }

    public Date getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(Date dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

}
