/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;


import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "APACONTR")
public class ApacontrEntity {

    @Column(name = "ID_APACONTR", table = "APACONTR", nullable = false)
    @Id
    private Integer idApacontr;

    @Column(name = "ID_APADIZIM", table = "APACONTR")
    @Basic
    private Integer idApadizim;

    @Column(name = "ID_CFACLIFO", table = "APACONTR")
    @Basic
    private Integer idCfaclifo;

    @Column(name = "ID_APACONTP", table = "APACONTR")
    @Basic
    private Integer idApacontp;

    @Column(name = "US_CAD", table = "APACONTR", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "APACONTR")
    @Basic
    private String dtCad;

    @Column(name = "DT_ALT", table = "APACONTR")
    @Basic
    private String dtAlt;

    @Column(name = "CT_INTEG", table = "APACONTR")
    @Basic
    private Integer ctInteg;

    @Column(name = "GUID", table = "APACONTR", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "DT_CONTRIBUICAO", table = "APACONTR", nullable = false)
    @Basic(optional = false)
        private String dtContribuicao;

    @Column(name = "ANO", table = "APACONTR", nullable = false)
    @Basic(optional = false)
    private int ano;

    @Column(name = "MES", table = "APACONTR", nullable = false)
    @Basic(optional = false)
    private int mes;

    @Column(name = "VALOR", table = "APACONTR", nullable = false)
    @Basic(optional = false)
    private double valor;

    @Column(name = "DT_PREVISAO", table = "APACONTR")
    @Basic
        private String dtPrevisao;

    @Column(name = "PERIODO", table = "APACONTR")
    @Basic
    private Character periodo;

    public Integer getIdApacontr() {
        return this.idApacontr;
    }

    public void setIdApacontr(Integer idApacontr) {
        this.idApacontr = idApacontr;
    }

    public Integer getIdApadizim() {
        return this.idApadizim;
    }

    public void setIdApadizim(Integer idApadizim) {
        this.idApadizim = idApadizim;
    }

    public Integer getIdCfaclifo() {
        return this.idCfaclifo;
    }

    public void setIdCfaclifo(Integer idCfaclifo) {
        this.idCfaclifo = idCfaclifo;
    }

    public Integer getIdApacontp() {
        return this.idApacontp;
    }

    public void setIdApacontp(Integer idApacontp) {
        this.idApacontp = idApacontp;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public String getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(String dtCad) {
        this.dtCad = dtCad;
    }

    public String getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(String dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getDtContribuicao() {
        return this.dtContribuicao;
    }

    public void setDtContribuicao(String dtContribuicao) {
        this.dtContribuicao = dtContribuicao;
    }

    public int getAno() {
        return this.ano;
    }

    public void setAno(int ano) {
        this.ano = ano;
    }

    public int getMes() {
        return this.mes;
    }

    public void setMes(int mes) {
        this.mes = mes;
    }

    public double getValor() {
        return this.valor;
    }

    public void setValor(double valor) {
        this.valor = valor;
    }

    public String getDtPrevisao() {
        return this.dtPrevisao;
    }

    public void setDtPrevisao(String dtPrevisao) {
        this.dtPrevisao = dtPrevisao;
    }

    public Character getPeriodo() {
        return this.periodo;
    }

    public void setPeriodo(Character periodo) {
        this.periodo = periodo;
    }

}
