/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;


import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "APADIPAS")
public class ApadipasEntity {

    @Column(name = "ID_APADIPAS", table = "APADIPAS", nullable = false)
    @Id
    private Integer idApadipas;

    @Column(name = "ID_APADIZIM", table = "APADIPAS")
    @Basic
    private Integer idApadizim;

    @Column(name = "ID_APAPASTO", table = "APADIPAS")
    @Basic
    private Integer idApapasto;

    @Column(name = "ID_CFACLIFO", table = "APADIPAS")
    @Basic
    private Integer idCfaclifo;

    @Column(name = "US_CAD", table = "APADIPAS", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "APADIPAS")
    @Basic
    private String dtCad;

    @Column(name = "DT_ALT", table = "APADIPAS")
    @Basic
    private String dtAlt;

    @Column(name = "CT_INTEG", table = "APADIPAS")
    @Basic
    private Integer ctInteg;

    @Column(name = "GUID", table = "APADIPAS", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "DT_INICIAL", table = "APADIPAS")
    @Basic
        private String dtInicial;

    @Column(name = "DT_FINAL", table = "APADIPAS")
    @Basic
        private String dtFinal;

    @Column(name = "TIPO_PG", table = "APADIPAS")
    @Basic
    private Character tipoPg;

    public Integer getIdApadipas() {
        return this.idApadipas;
    }

    public void setIdApadipas(Integer idApadipas) {
        this.idApadipas = idApadipas;
    }

    public Integer getIdApadizim() {
        return this.idApadizim;
    }

    public void setIdApadizim(Integer idApadizim) {
        this.idApadizim = idApadizim;
    }

    public Integer getIdApapasto() {
        return this.idApapasto;
    }

    public void setIdApapasto(Integer idApapasto) {
        this.idApapasto = idApapasto;
    }

    public Integer getIdCfaclifo() {
        return this.idCfaclifo;
    }

    public void setIdCfaclifo(Integer idCfaclifo) {
        this.idCfaclifo = idCfaclifo;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public String getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(String dtCad) {
        this.dtCad = dtCad;
    }

    public String getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(String dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getDtInicial() {
        return this.dtInicial;
    }

    public void setDtInicial(String dtInicial) {
        this.dtInicial = dtInicial;
    }

    public String getDtFinal() {
        return this.dtFinal;
    }

    public void setDtFinal(String dtFinal) {
        this.dtFinal = dtFinal;
    }

    public Character getTipoPg() {
        return this.tipoPg;
    }

    public void setTipoPg(Character tipoPg) {
        this.tipoPg = tipoPg;
    }

}
