/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "APALCASA")
public class ApalcasaEntity {

    @Column(name = "ID_APALCASA", table = "APALCASA", nullable = false)
    @Id
    private Integer idApalcasa;

    @Column(name = "ID_APAPAROQ", table = "APALCASA")
    @Basic
    private Integer idApaparoq;

    @Column(name = "ID_APACOMUN", table = "APALCASA")
    @Basic
    private Integer idApacomun;

    @Column(name = "ID_CFACIDAD_NOIVO", table = "APALCASA")
    @Basic
    private Integer idCfacidadNoivo;

    @Column(name = "ID_CFAESTAD_NOIVO", table = "APALCASA")
    @Basic
    private Integer idCfaestadNoivo;

    @Column(name = "ID_CFACIDAD_NOIVA", table = "APALCASA")
    @Basic
    private Integer idCfacidadNoiva;

    @Column(name = "ID_CFAESTAD_NOIVA", table = "APALCASA")
    @Basic
    private Integer idCfaestadNoiva;

    @Column(name = "ID_CFACIDAD_MORAR", table = "APALCASA")
    @Basic
    private Integer idCfacidadMorar;

    @Column(name = "ID_CFAESTAD_MORAR", table = "APALCASA")
    @Basic
    private Integer idCfaestadMorar;

    @Column(name = "ID_CFAESTAD_CIVIL_CARTOR", table = "APALCASA")
    @Basic
    private Integer idCfaestadCivilCartor;

    @Column(name = "ID_CFACIDAD_CIVIL_CARTOR", table = "APALCASA")
    @Basic
    private Integer idCfacidadCivilCartor;

    @Column(name = "ID_CFAESTAD_TESTEMUNHA1", table = "APALCASA")
    @Basic
    private Integer idCfaestadTestemunha1;

    @Column(name = "ID_CFACIDAD_TESTEMUNHA1", table = "APALCASA")
    @Basic
    private Integer idCfacidadTestemunha1;

    @Column(name = "ID_CFAESTAD_TESTEMUNHA2", table = "APALCASA")
    @Basic
    private Integer idCfaestadTestemunha2;

    @Column(name = "ID_CFACIDAD_TESTEMUNHA2", table = "APALCASA")
    @Basic
    private Integer idCfacidadTestemunha2;

    @Column(name = "ID_CFACLIFO_DIOCE", table = "APALCASA")
    @Basic
    private Integer idCfaclifoDioce;

    @Column(name = "ID_CFACLIFO_PAROQ", table = "APALCASA")
    @Basic
    private Integer idCfaclifoParoq;

    @Column(name = "ID_CFACLIFO_COMUN", table = "APALCASA")
    @Basic
    private Integer idCfaclifoComun;

    @Column(name = "US_CAD", table = "APALCASA", nullable = false, length = 20)
    @Basic(optional = false)
    private String usCad;

    @Column(name = "DT_CAD", table = "APALCASA", nullable = false)
    @Basic(optional = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtCad;

    @Column(name = "DT_ALT", table = "APALCASA", nullable = false)
    @Basic(optional = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtAlt;

    @Column(name = "CT_INTEG", table = "APALCASA")
    @Basic
    private Integer ctInteg;

    @Column(name = "GUID", table = "APALCASA", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "DT_HR_CASAMENTO", table = "APALCASA")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtHrCasamento;

    @Column(name = "LIVRO", table = "APALCASA")
    @Basic
    private Integer livro;

    @Column(name = "FOLHA", table = "APALCASA")
    @Basic
    private Integer folha;

    @Column(name = "TERMO", table = "APALCASA")
    @Basic
    private Integer termo;

    @Column(name = "NOIVA_NOME", table = "APALCASA", length = 40)
    @Basic
    private String noivaNome;

    @Column(name = "NOIVA_NATURAL", table = "APALCASA", length = 40)
    @Basic
    private String noivaNatural;

    @Column(name = "NOIVA_IDADE", table = "APALCASA", nullable = false)
    @Basic(optional = false)
    private int noivaIdade;

    @Column(name = "NOIVA_BATIZADA", table = "APALCASA", length = 40)
    @Basic
    private String noivaBatizada;

    @Column(name = "NOIVA_PROF", table = "APALCASA", length = 40)
    @Basic
    private String noivaProf;

    @Column(name = "NOIVA_PAI", table = "APALCASA", length = 60)
    @Basic
    private String noivaPai;

    @Column(name = "NOIVA_MAE", table = "APALCASA", length = 60)
    @Basic
    private String noivaMae;

    @Column(name = "NOIVA_RESIDENTE", table = "APALCASA", length = 40)
    @Basic
    private String noivaResidente;

    @Column(name = "NOIVA_BAIRRO", table = "APALCASA", length = 40)
    @Basic
    private String noivaBairro;

    @Column(name = "NOIVA_BATIZ_COMO", table = "APALCASA")
    @Basic
    private Character noivaBatizComo;

    @Column(name = "NOIVA_BATIZ_LIVRO", table = "APALCASA")
    @Basic
    private Integer noivaBatizLivro;

    @Column(name = "NOIVA_BATIZ_FOLHA", table = "APALCASA")
    @Basic
    private Integer noivaBatizFolha;

    @Column(name = "NOIVA_BATIZ_TERMO", table = "APALCASA")
    @Basic
    private Integer noivaBatizTermo;

    @Column(name = "NOIVA_PERGUNTA1", table = "APALCASA", length = 128)
    @Basic
    private String noivaPergunta1;

    @Column(name = "NOIVA_PERGUNTA2", table = "APALCASA", length = 128)
    @Basic
    private String noivaPergunta2;

    @Column(name = "NOIVA_PERGUNTA3", table = "APALCASA", length = 128)
    @Basic
    private String noivaPergunta3;

    @Column(name = "NOIVA_PERGUNTA4", table = "APALCASA", length = 128)
    @Basic
    private String noivaPergunta4;

    @Column(name = "NOIVA_PERGUNTA5", table = "APALCASA", length = 128)
    @Basic
    private String noivaPergunta5;

    @Column(name = "NOIVA_PERGUNTA6", table = "APALCASA", length = 128)
    @Basic
    private String noivaPergunta6;

    @Column(name = "NOIVA_SUPLETIVO", table = "APALCASA")
    @Basic
    private Character noivaSupletivo;

    @Column(name = "NOIVA_SUPLE_JURADO", table = "APALCASA", length = 60)
    @Basic
    private String noivaSupleJurado;

    @Column(name = "NOIVA_SUPLE_TESTEMUNHA1", table = "APALCASA", length = 60)
    @Basic
    private String noivaSupleTestemunha1;

    @Column(name = "NOIVA_SUPLE_TESTEMUNHA2", table = "APALCASA", length = 60)
    @Basic
    private String noivaSupleTestemunha2;

    @Column(name = "NOIVA_SUPLE_PADRE", table = "APALCASA", length = 60)
    @Basic
    private String noivaSuplePadre;

    @Column(name = "NOIVA_EST_CIVIL", table = "APALCASA")
    @Basic
    private Character noivaEstCivil;

    @Column(name = "NOIVA_DT_BATISMO", table = "APALCASA")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date noivaDtBatismo;

    @Column(name = "NOIVA_BATIZ_PAROQ", table = "APALCASA", length = 40)
    @Basic
    private String noivaBatizParoq;

    @Column(name = "NOIVA_BATIZ_DIOCESE", table = "APALCASA", length = 40)
    @Basic
    private String noivaBatizDiocese;

    @Column(name = "NOIVA_PAIS_RESIDENTES", table = "APALCASA", length = 128)
    @Basic
    private String noivaPaisResidentes;

    @Column(name = "NOIVA_MAE_NATURAL", table = "APALCASA", length = 40)
    @Basic
    private String noivaMaeNatural;

    @Column(name = "NOIVA_PAI_NATURAL", table = "APALCASA", length = 40)
    @Basic
    private String noivaPaiNatural;

    @Column(name = "NOIVA_RESIDE_PAROQ", table = "APALCASA", length = 128)
    @Basic
    private String noivaResideParoq;

    @Column(name = "NOIVO_NOME", table = "APALCASA", length = 60)
    @Basic
    private String noivoNome;

    @Column(name = "NOIVO_DT_NASCIMENTO", table = "APALCASA")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date noivoDtNascimento;

    @Column(name = "NOIVO_NATURAL", table = "APALCASA", length = 40)
    @Basic
    private String noivoNatural;

    @Column(name = "NOIVO_IDADE", table = "APALCASA", nullable = false)
    @Basic(optional = false)
    private int noivoIdade;

    @Column(name = "NOIVO_BATIZADO", table = "APALCASA", length = 40)
    @Basic
    private String noivoBatizado;

    @Column(name = "NOIVO_PROF", table = "APALCASA", length = 40)
    @Basic
    private String noivoProf;

    @Column(name = "NOIVO_PAI", table = "APALCASA", length = 60)
    @Basic
    private String noivoPai;

    @Column(name = "NOIVO_MAE", table = "APALCASA", length = 60)
    @Basic
    private String noivoMae;

    @Column(name = "NOIVO_RESIDENTE", table = "APALCASA", length = 40)
    @Basic
    private String noivoResidente;

    @Column(name = "NOIVO_BAIRRO", table = "APALCASA", length = 40)
    @Basic
    private String noivoBairro;

    @Column(name = "NOIVO_BATIZ_COMO", table = "APALCASA")
    @Basic
    private Character noivoBatizComo;

    @Column(name = "NOIVO_BATIZ_LIVRO", table = "APALCASA")
    @Basic
    private Integer noivoBatizLivro;

    @Column(name = "NOIVO_BATIZ_FOLHA", table = "APALCASA")
    @Basic
    private Integer noivoBatizFolha;

    @Column(name = "NOIVO_BATIZ_TERMO", table = "APALCASA")
    @Basic
    private Integer noivoBatizTermo;

    @Column(name = "NOIVO_PERGUNTA1", table = "APALCASA", length = 128)
    @Basic
    private String noivoPergunta1;

    @Column(name = "NOIVO_PERGUNTA2", table = "APALCASA", length = 128)
    @Basic
    private String noivoPergunta2;

    @Column(name = "NOIVO_PERGUNTA3", table = "APALCASA", length = 128)
    @Basic
    private String noivoPergunta3;

    @Column(name = "NOIVO_PERGUNTA4", table = "APALCASA", length = 128)
    @Basic
    private String noivoPergunta4;

    @Column(name = "NOIVO_PERGUNTA5", table = "APALCASA", length = 128)
    @Basic
    private String noivoPergunta5;

    @Column(name = "NOIVO_PERGUNTA6", table = "APALCASA", length = 128)
    @Basic
    private String noivoPergunta6;

    @Column(name = "NOIVO_SUPLETIVO", table = "APALCASA")
    @Basic
    private Character noivoSupletivo;

    @Column(name = "NOIVO_SUPLETIVO_JURADO", table = "APALCASA", length = 60)
    @Basic
    private String noivoSupletivoJurado;

    @Column(name = "NOIVO_SUPLE_TESTEMUNHA1", table = "APALCASA", length = 60)
    @Basic
    private String noivoSupleTestemunha1;

    @Column(name = "NOIVO_SUPLE_TESTEMUNHA2", table = "APALCASA", length = 60)
    @Basic
    private String noivoSupleTestemunha2;

    @Column(name = "NOIVO_SUPLE_PADRE", table = "APALCASA", length = 60)
    @Basic
    private String noivoSuplePadre;

    @Column(name = "NOIVO_ESTAD_CIVIL", table = "APALCASA")
    @Basic
    private Character noivoEstadCivil;

    @Column(name = "NOIVO_DT_BATIZMO", table = "APALCASA")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date noivoDtBatizmo;

    @Column(name = "NOIVO_BATIZ_PAROQ", table = "APALCASA", length = 40)
    @Basic
    private String noivoBatizParoq;

    @Column(name = "NOIVO_BATIZ_DICESE", table = "APALCASA", length = 40)
    @Basic
    private String noivoBatizDicese;

    @Column(name = "NOIVO_PAIS_RESIDENTES", table = "APALCASA", length = 128)
    @Basic
    private String noivoPaisResidentes;

    @Column(name = "NOIVO_MAE_NATURAL", table = "APALCASA", length = 40)
    @Basic
    private String noivoMaeNatural;

    @Column(name = "NOIVO_PAI_NATURAL", table = "APALCASA", length = 40)
    @Basic
    private String noivoPaiNatural;

    @Column(name = "NOIVO_RESID_PAROQ", table = "APALCASA", length = 128)
    @Basic
    private String noivoResidParoq;

    @Column(name = "PADRE_NOME", table = "APALCASA", length = 60)
    @Basic
    private String padreNome;

    @Column(name = "TESTEMUNHA1", table = "APALCASA", length = 60)
    @Basic
    private String testemunha1;

    @Column(name = "TESTEMUNHA2", table = "APALCASA", length = 60)
    @Basic
    private String testemunha2;

    @Column(name = "TESTEMUNHAS", table = "APALCASA")
    @Lob
    @Basic
    private byte[] testemunhas;

    @Column(name = "IMPRESSOES", table = "APALCASA", nullable = false)
    @Basic(optional = false)
    private int impressoes;

    @Column(name = "DT_DIALOGO", table = "APALCASA")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date dtDialogo;

    @Column(name = "COMUNIDADE_FREQ", table = "APALCASA", length = 40)
    @Basic
    private String comunidadeFreq;

    @Column(name = "BISPO_NOME", table = "APALCASA", length = 60)
    @Basic
    private String bispoNome;

    @Column(name = "SITUACAO_PROCESSO", table = "APALCASA")
    @Basic
    private Character situacaoProcesso;

    @Column(name = "OBSERVACAO", table = "APALCASA")
    @Lob
    @Basic
    private byte[] observacao;

    @Column(name = "NOTIFICOU", table = "APALCASA")
    @Basic
    private Character notificou;

    @Column(name = "CIVIL_CARTOR_NOME", table = "APALCASA", length = 60)
    @Basic
    private String civilCartorNome;

    @Column(name = "CIVIL_DT_HABILITA", table = "APALCASA")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date civilDtHabilita;

    @Column(name = "CIVIL_DT_CASAMENTO", table = "APALCASA")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date civilDtCasamento;

    @Column(name = "CIVIL_NOME_JUIZ", table = "APALCASA", length = 60)
    @Basic
    private String civilNomeJuiz;

    @Column(name = "CIVIL_TESTEMUNHA1", table = "APALCASA", length = 60)
    @Basic
    private String civilTestemunha1;

    @Column(name = "CIVIL_TESTEMUNHA1_EST_CIVIL", table = "APALCASA")
    @Basic
    private Character civilTestemunha1EstCivil;

    @Column(name = "CIVIL_TESTEMUNHA1_IDADE", table = "APALCASA", nullable = false)
    @Basic(optional = false)
    private int civilTestemunha1Idade;

    @Column(name = "CIVIL_TESTEMUNHA_PROFISSAO", table = "APALCASA", length = 40)
    @Basic
    private String civilTestemunhaProfissao;

    @Column(name = "CIVIL_TESTEMUNHA1_RESIDENCIA", table = "APALCASA", length = 128)
    @Basic
    private String civilTestemunha1Residencia;

    @Column(name = "CIVIL_TESTEMUNHA2", table = "APALCASA", length = 60)
    @Basic
    private String civilTestemunha2;

    @Column(name = "CIVIL_TESTEMUNHA2_EST_CIVIL", table = "APALCASA")
    @Basic
    private Character civilTestemunha2EstCivil;

    @Column(name = "CIVIL_TESTEMUNHA2_IDADE", table = "APALCASA", nullable = false)
    @Basic(optional = false)
    private int civilTestemunha2Idade;

    @Column(name = "CIVIL_TESTEMUNHA2_PROFISSAO", table = "APALCASA", length = 40)
    @Basic
    private String civilTestemunha2Profissao;

    @Column(name = "CIVIL_TESTEMUNHA2_RESIDENCIA", table = "APALCASA", length = 128)
    @Basic
    private String civilTestemunha2Residencia;

    @Column(name = "CIVIL_NOME_NOIVA", table = "APALCASA", length = 60)
    @Basic
    private String civilNomeNoiva;

    @Column(name = "REGIME_CASA", table = "APALCASA", length = 128)
    @Basic
    private String regimeCasa;

    @Column(name = "DISPENSA_DESPACHO", table = "APALCASA")
    @Lob
    @Basic
    private byte[] dispensaDespacho;

    @Column(name = "DISPENSA_CONSAGUIDADE_GRAU", table = "APALCASA", length = 128)
    @Basic
    private String dispensaConsaguidadeGrau;

    @Column(name = "DISPENSA_DE_ITEN_IV", table = "APALCASA", length = 128)
    @Basic
    private String dispensaDeItenIv;

    @Column(name = "DISPENSA_MOTIVO", table = "APALCASA", length = 128)
    @Basic
    private String dispensaMotivo;

    @Column(name = "NOIVA_DT_NASCIMENTO", table = "APALCASA")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date noivaDtNascimento;

    @Column(name = "DIOCESE_TRANSFERIDA", table = "APALCASA", length = 40)
    @Basic
    private String dioceseTransferida;

    @Column(name = "PAROQUIATRANSFERIDA", table = "APALCASA", length = 40)
    @Basic
    private String paroquiatransferida;

    @Column(name = "COMUNIDADE_TRANSFERIDA", table = "APALCASA", length = 40)
    @Basic
    private String comunidadeTransferida;

    @Column(name = "PAROCO", table = "APALCASA", length = 60)
    @Basic
    private String paroco;

    @Column(name = "NOIVA_PAROQ_RESID_PERIODO", table = "APALCASA", length = 40)
    @Basic
    private String noivaParoqResidPeriodo;

    @Column(name = "NOIVO_PAROQ_RESID_PERIODO", table = "APALCASA", length = 40)
    @Basic
    private String noivoParoqResidPeriodo;

    @Column(name = "NOIVO_SACRAMENTO", table = "APALCASA", length = 5)
    @Basic
    private String noivoSacramento;

    @Column(name = "NOIVA_SACRAMENTO", table = "APALCASA", length = 5)
    @Basic
    private String noivaSacramento;

    @Column(name = "EVANGELICO", table = "APALCASA", length = 6)
    @Basic
    private String evangelico;

    @Column(name = "OBS_ANULACAO", table = "APALCASA")
    @Lob
    @Basic
    private byte[] obsAnulacao;

    @Column(name = "NOIVA_CPF", table = "APALCASA", length = 18)
    @Basic
    private String noivaCpf;

    @Column(name = "NOIVA_RG", table = "APALCASA", length = 18)
    @Basic
    private String noivaRg;

    @Column(name = "NOIVO_CPF", table = "APALCASA", length = 18)
    @Basic
    private String noivoCpf;

    @Column(name = "NOIVO_RG", table = "APALCASA", length = 18)
    @Basic
    private String noivoRg;

    @Column(name = "CIVIL_TESTEMUNHA1_CPF", table = "APALCASA", length = 18)
    @Basic
    private String civilTestemunha1Cpf;

    @Column(name = "CIVIL_TESTEMUNHA1_RG", table = "APALCASA", length = 18)
    @Basic
    private String civilTestemunha1Rg;

    @Column(name = "CIVIL_TESTEMUNHA2_CPF", table = "APALCASA", length = 18)
    @Basic
    private String civilTestemunha2Cpf;

    @Column(name = "CIVIL_TESTEMUNHA2_RG", table = "APALCASA", length = 18)
    @Basic
    private String civilTestemunha2Rg;

    @Column(name = "ID_APANEGAT", table = "APALCASA")
    @Basic
    private Integer idApanegat;

    public Integer getIdApalcasa() {
        return this.idApalcasa;
    }

    public void setIdApalcasa(Integer idApalcasa) {
        this.idApalcasa = idApalcasa;
    }

    public Integer getIdApaparoq() {
        return this.idApaparoq;
    }

    public void setIdApaparoq(Integer idApaparoq) {
        this.idApaparoq = idApaparoq;
    }

    public Integer getIdApacomun() {
        return this.idApacomun;
    }

    public void setIdApacomun(Integer idApacomun) {
        this.idApacomun = idApacomun;
    }

    public Integer getIdCfacidadNoivo() {
        return this.idCfacidadNoivo;
    }

    public void setIdCfacidadNoivo(Integer idCfacidadNoivo) {
        this.idCfacidadNoivo = idCfacidadNoivo;
    }

    public Integer getIdCfaestadNoivo() {
        return this.idCfaestadNoivo;
    }

    public void setIdCfaestadNoivo(Integer idCfaestadNoivo) {
        this.idCfaestadNoivo = idCfaestadNoivo;
    }

    public Integer getIdCfacidadNoiva() {
        return this.idCfacidadNoiva;
    }

    public void setIdCfacidadNoiva(Integer idCfacidadNoiva) {
        this.idCfacidadNoiva = idCfacidadNoiva;
    }

    public Integer getIdCfaestadNoiva() {
        return this.idCfaestadNoiva;
    }

    public void setIdCfaestadNoiva(Integer idCfaestadNoiva) {
        this.idCfaestadNoiva = idCfaestadNoiva;
    }

    public Integer getIdCfacidadMorar() {
        return this.idCfacidadMorar;
    }

    public void setIdCfacidadMorar(Integer idCfacidadMorar) {
        this.idCfacidadMorar = idCfacidadMorar;
    }

    public Integer getIdCfaestadMorar() {
        return this.idCfaestadMorar;
    }

    public void setIdCfaestadMorar(Integer idCfaestadMorar) {
        this.idCfaestadMorar = idCfaestadMorar;
    }

    public Integer getIdCfaestadCivilCartor() {
        return this.idCfaestadCivilCartor;
    }

    public void setIdCfaestadCivilCartor(Integer idCfaestadCivilCartor) {
        this.idCfaestadCivilCartor = idCfaestadCivilCartor;
    }

    public Integer getIdCfacidadCivilCartor() {
        return this.idCfacidadCivilCartor;
    }

    public void setIdCfacidadCivilCartor(Integer idCfacidadCivilCartor) {
        this.idCfacidadCivilCartor = idCfacidadCivilCartor;
    }

    public Integer getIdCfaestadTestemunha1() {
        return this.idCfaestadTestemunha1;
    }

    public void setIdCfaestadTestemunha1(Integer idCfaestadTestemunha1) {
        this.idCfaestadTestemunha1 = idCfaestadTestemunha1;
    }

    public Integer getIdCfacidadTestemunha1() {
        return this.idCfacidadTestemunha1;
    }

    public void setIdCfacidadTestemunha1(Integer idCfacidadTestemunha1) {
        this.idCfacidadTestemunha1 = idCfacidadTestemunha1;
    }

    public Integer getIdCfaestadTestemunha2() {
        return this.idCfaestadTestemunha2;
    }

    public void setIdCfaestadTestemunha2(Integer idCfaestadTestemunha2) {
        this.idCfaestadTestemunha2 = idCfaestadTestemunha2;
    }

    public Integer getIdCfacidadTestemunha2() {
        return this.idCfacidadTestemunha2;
    }

    public void setIdCfacidadTestemunha2(Integer idCfacidadTestemunha2) {
        this.idCfacidadTestemunha2 = idCfacidadTestemunha2;
    }

    public Integer getIdCfaclifoDioce() {
        return this.idCfaclifoDioce;
    }

    public void setIdCfaclifoDioce(Integer idCfaclifoDioce) {
        this.idCfaclifoDioce = idCfaclifoDioce;
    }

    public Integer getIdCfaclifoParoq() {
        return this.idCfaclifoParoq;
    }

    public void setIdCfaclifoParoq(Integer idCfaclifoParoq) {
        this.idCfaclifoParoq = idCfaclifoParoq;
    }

    public Integer getIdCfaclifoComun() {
        return this.idCfaclifoComun;
    }

    public void setIdCfaclifoComun(Integer idCfaclifoComun) {
        this.idCfaclifoComun = idCfaclifoComun;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public Date getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(Date dtCad) {
        this.dtCad = dtCad;
    }

    public Date getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(Date dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public Date getDtHrCasamento() {
        return this.dtHrCasamento;
    }

    public void setDtHrCasamento(Date dtHrCasamento) {
        this.dtHrCasamento = dtHrCasamento;
    }

    public Integer getLivro() {
        return this.livro;
    }

    public void setLivro(Integer livro) {
        this.livro = livro;
    }

    public Integer getFolha() {
        return this.folha;
    }

    public void setFolha(Integer folha) {
        this.folha = folha;
    }

    public Integer getTermo() {
        return this.termo;
    }

    public void setTermo(Integer termo) {
        this.termo = termo;
    }

    public String getNoivaNome() {
        return this.noivaNome;
    }

    public void setNoivaNome(String noivaNome) {
        this.noivaNome = noivaNome;
    }

    public String getNoivaNatural() {
        return this.noivaNatural;
    }

    public void setNoivaNatural(String noivaNatural) {
        this.noivaNatural = noivaNatural;
    }

    public int getNoivaIdade() {
        return this.noivaIdade;
    }

    public void setNoivaIdade(int noivaIdade) {
        this.noivaIdade = noivaIdade;
    }

    public String getNoivaBatizada() {
        return this.noivaBatizada;
    }

    public void setNoivaBatizada(String noivaBatizada) {
        this.noivaBatizada = noivaBatizada;
    }

    public String getNoivaProf() {
        return this.noivaProf;
    }

    public void setNoivaProf(String noivaProf) {
        this.noivaProf = noivaProf;
    }

    public String getNoivaPai() {
        return this.noivaPai;
    }

    public void setNoivaPai(String noivaPai) {
        this.noivaPai = noivaPai;
    }

    public String getNoivaMae() {
        return this.noivaMae;
    }

    public void setNoivaMae(String noivaMae) {
        this.noivaMae = noivaMae;
    }

    public String getNoivaResidente() {
        return this.noivaResidente;
    }

    public void setNoivaResidente(String noivaResidente) {
        this.noivaResidente = noivaResidente;
    }

    public String getNoivaBairro() {
        return this.noivaBairro;
    }

    public void setNoivaBairro(String noivaBairro) {
        this.noivaBairro = noivaBairro;
    }

    public Character getNoivaBatizComo() {
        return this.noivaBatizComo;
    }

    public void setNoivaBatizComo(Character noivaBatizComo) {
        this.noivaBatizComo = noivaBatizComo;
    }

    public Integer getNoivaBatizLivro() {
        return this.noivaBatizLivro;
    }

    public void setNoivaBatizLivro(Integer noivaBatizLivro) {
        this.noivaBatizLivro = noivaBatizLivro;
    }

    public Integer getNoivaBatizFolha() {
        return this.noivaBatizFolha;
    }

    public void setNoivaBatizFolha(Integer noivaBatizFolha) {
        this.noivaBatizFolha = noivaBatizFolha;
    }

    public Integer getNoivaBatizTermo() {
        return this.noivaBatizTermo;
    }

    public void setNoivaBatizTermo(Integer noivaBatizTermo) {
        this.noivaBatizTermo = noivaBatizTermo;
    }

    public String getNoivaPergunta1() {
        return this.noivaPergunta1;
    }

    public void setNoivaPergunta1(String noivaPergunta1) {
        this.noivaPergunta1 = noivaPergunta1;
    }

    public String getNoivaPergunta2() {
        return this.noivaPergunta2;
    }

    public void setNoivaPergunta2(String noivaPergunta2) {
        this.noivaPergunta2 = noivaPergunta2;
    }

    public String getNoivaPergunta3() {
        return this.noivaPergunta3;
    }

    public void setNoivaPergunta3(String noivaPergunta3) {
        this.noivaPergunta3 = noivaPergunta3;
    }

    public String getNoivaPergunta4() {
        return this.noivaPergunta4;
    }

    public void setNoivaPergunta4(String noivaPergunta4) {
        this.noivaPergunta4 = noivaPergunta4;
    }

    public String getNoivaPergunta5() {
        return this.noivaPergunta5;
    }

    public void setNoivaPergunta5(String noivaPergunta5) {
        this.noivaPergunta5 = noivaPergunta5;
    }

    public String getNoivaPergunta6() {
        return this.noivaPergunta6;
    }

    public void setNoivaPergunta6(String noivaPergunta6) {
        this.noivaPergunta6 = noivaPergunta6;
    }

    public Character getNoivaSupletivo() {
        return this.noivaSupletivo;
    }

    public void setNoivaSupletivo(Character noivaSupletivo) {
        this.noivaSupletivo = noivaSupletivo;
    }

    public String getNoivaSupleJurado() {
        return this.noivaSupleJurado;
    }

    public void setNoivaSupleJurado(String noivaSupleJurado) {
        this.noivaSupleJurado = noivaSupleJurado;
    }

    public String getNoivaSupleTestemunha1() {
        return this.noivaSupleTestemunha1;
    }

    public void setNoivaSupleTestemunha1(String noivaSupleTestemunha1) {
        this.noivaSupleTestemunha1 = noivaSupleTestemunha1;
    }

    public String getNoivaSupleTestemunha2() {
        return this.noivaSupleTestemunha2;
    }

    public void setNoivaSupleTestemunha2(String noivaSupleTestemunha2) {
        this.noivaSupleTestemunha2 = noivaSupleTestemunha2;
    }

    public String getNoivaSuplePadre() {
        return this.noivaSuplePadre;
    }

    public void setNoivaSuplePadre(String noivaSuplePadre) {
        this.noivaSuplePadre = noivaSuplePadre;
    }

    public Character getNoivaEstCivil() {
        return this.noivaEstCivil;
    }

    public void setNoivaEstCivil(Character noivaEstCivil) {
        this.noivaEstCivil = noivaEstCivil;
    }

    public Date getNoivaDtBatismo() {
        return this.noivaDtBatismo;
    }

    public void setNoivaDtBatismo(Date noivaDtBatismo) {
        this.noivaDtBatismo = noivaDtBatismo;
    }

    public String getNoivaBatizParoq() {
        return this.noivaBatizParoq;
    }

    public void setNoivaBatizParoq(String noivaBatizParoq) {
        this.noivaBatizParoq = noivaBatizParoq;
    }

    public String getNoivaBatizDiocese() {
        return this.noivaBatizDiocese;
    }

    public void setNoivaBatizDiocese(String noivaBatizDiocese) {
        this.noivaBatizDiocese = noivaBatizDiocese;
    }

    public String getNoivaPaisResidentes() {
        return this.noivaPaisResidentes;
    }

    public void setNoivaPaisResidentes(String noivaPaisResidentes) {
        this.noivaPaisResidentes = noivaPaisResidentes;
    }

    public String getNoivaMaeNatural() {
        return this.noivaMaeNatural;
    }

    public void setNoivaMaeNatural(String noivaMaeNatural) {
        this.noivaMaeNatural = noivaMaeNatural;
    }

    public String getNoivaPaiNatural() {
        return this.noivaPaiNatural;
    }

    public void setNoivaPaiNatural(String noivaPaiNatural) {
        this.noivaPaiNatural = noivaPaiNatural;
    }

    public String getNoivaResideParoq() {
        return this.noivaResideParoq;
    }

    public void setNoivaResideParoq(String noivaResideParoq) {
        this.noivaResideParoq = noivaResideParoq;
    }

    public String getNoivoNome() {
        return this.noivoNome;
    }

    public void setNoivoNome(String noivoNome) {
        this.noivoNome = noivoNome;
    }

    public Date getNoivoDtNascimento() {
        return this.noivoDtNascimento;
    }

    public void setNoivoDtNascimento(Date noivoDtNascimento) {
        this.noivoDtNascimento = noivoDtNascimento;
    }

    public String getNoivoNatural() {
        return this.noivoNatural;
    }

    public void setNoivoNatural(String noivoNatural) {
        this.noivoNatural = noivoNatural;
    }

    public int getNoivoIdade() {
        return this.noivoIdade;
    }

    public void setNoivoIdade(int noivoIdade) {
        this.noivoIdade = noivoIdade;
    }

    public String getNoivoBatizado() {
        return this.noivoBatizado;
    }

    public void setNoivoBatizado(String noivoBatizado) {
        this.noivoBatizado = noivoBatizado;
    }

    public String getNoivoProf() {
        return this.noivoProf;
    }

    public void setNoivoProf(String noivoProf) {
        this.noivoProf = noivoProf;
    }

    public String getNoivoPai() {
        return this.noivoPai;
    }

    public void setNoivoPai(String noivoPai) {
        this.noivoPai = noivoPai;
    }

    public String getNoivoMae() {
        return this.noivoMae;
    }

    public void setNoivoMae(String noivoMae) {
        this.noivoMae = noivoMae;
    }

    public String getNoivoResidente() {
        return this.noivoResidente;
    }

    public void setNoivoResidente(String noivoResidente) {
        this.noivoResidente = noivoResidente;
    }

    public String getNoivoBairro() {
        return this.noivoBairro;
    }

    public void setNoivoBairro(String noivoBairro) {
        this.noivoBairro = noivoBairro;
    }

    public Character getNoivoBatizComo() {
        return this.noivoBatizComo;
    }

    public void setNoivoBatizComo(Character noivoBatizComo) {
        this.noivoBatizComo = noivoBatizComo;
    }

    public Integer getNoivoBatizLivro() {
        return this.noivoBatizLivro;
    }

    public void setNoivoBatizLivro(Integer noivoBatizLivro) {
        this.noivoBatizLivro = noivoBatizLivro;
    }

    public Integer getNoivoBatizFolha() {
        return this.noivoBatizFolha;
    }

    public void setNoivoBatizFolha(Integer noivoBatizFolha) {
        this.noivoBatizFolha = noivoBatizFolha;
    }

    public Integer getNoivoBatizTermo() {
        return this.noivoBatizTermo;
    }

    public void setNoivoBatizTermo(Integer noivoBatizTermo) {
        this.noivoBatizTermo = noivoBatizTermo;
    }

    public String getNoivoPergunta1() {
        return this.noivoPergunta1;
    }

    public void setNoivoPergunta1(String noivoPergunta1) {
        this.noivoPergunta1 = noivoPergunta1;
    }

    public String getNoivoPergunta2() {
        return this.noivoPergunta2;
    }

    public void setNoivoPergunta2(String noivoPergunta2) {
        this.noivoPergunta2 = noivoPergunta2;
    }

    public String getNoivoPergunta3() {
        return this.noivoPergunta3;
    }

    public void setNoivoPergunta3(String noivoPergunta3) {
        this.noivoPergunta3 = noivoPergunta3;
    }

    public String getNoivoPergunta4() {
        return this.noivoPergunta4;
    }

    public void setNoivoPergunta4(String noivoPergunta4) {
        this.noivoPergunta4 = noivoPergunta4;
    }

    public String getNoivoPergunta5() {
        return this.noivoPergunta5;
    }

    public void setNoivoPergunta5(String noivoPergunta5) {
        this.noivoPergunta5 = noivoPergunta5;
    }

    public String getNoivoPergunta6() {
        return this.noivoPergunta6;
    }

    public void setNoivoPergunta6(String noivoPergunta6) {
        this.noivoPergunta6 = noivoPergunta6;
    }

    public Character getNoivoSupletivo() {
        return this.noivoSupletivo;
    }

    public void setNoivoSupletivo(Character noivoSupletivo) {
        this.noivoSupletivo = noivoSupletivo;
    }

    public String getNoivoSupletivoJurado() {
        return this.noivoSupletivoJurado;
    }

    public void setNoivoSupletivoJurado(String noivoSupletivoJurado) {
        this.noivoSupletivoJurado = noivoSupletivoJurado;
    }

    public String getNoivoSupleTestemunha1() {
        return this.noivoSupleTestemunha1;
    }

    public void setNoivoSupleTestemunha1(String noivoSupleTestemunha1) {
        this.noivoSupleTestemunha1 = noivoSupleTestemunha1;
    }

    public String getNoivoSupleTestemunha2() {
        return this.noivoSupleTestemunha2;
    }

    public void setNoivoSupleTestemunha2(String noivoSupleTestemunha2) {
        this.noivoSupleTestemunha2 = noivoSupleTestemunha2;
    }

    public String getNoivoSuplePadre() {
        return this.noivoSuplePadre;
    }

    public void setNoivoSuplePadre(String noivoSuplePadre) {
        this.noivoSuplePadre = noivoSuplePadre;
    }

    public Character getNoivoEstadCivil() {
        return this.noivoEstadCivil;
    }

    public void setNoivoEstadCivil(Character noivoEstadCivil) {
        this.noivoEstadCivil = noivoEstadCivil;
    }

    public Date getNoivoDtBatizmo() {
        return this.noivoDtBatizmo;
    }

    public void setNoivoDtBatizmo(Date noivoDtBatizmo) {
        this.noivoDtBatizmo = noivoDtBatizmo;
    }

    public String getNoivoBatizParoq() {
        return this.noivoBatizParoq;
    }

    public void setNoivoBatizParoq(String noivoBatizParoq) {
        this.noivoBatizParoq = noivoBatizParoq;
    }

    public String getNoivoBatizDicese() {
        return this.noivoBatizDicese;
    }

    public void setNoivoBatizDicese(String noivoBatizDicese) {
        this.noivoBatizDicese = noivoBatizDicese;
    }

    public String getNoivoPaisResidentes() {
        return this.noivoPaisResidentes;
    }

    public void setNoivoPaisResidentes(String noivoPaisResidentes) {
        this.noivoPaisResidentes = noivoPaisResidentes;
    }

    public String getNoivoMaeNatural() {
        return this.noivoMaeNatural;
    }

    public void setNoivoMaeNatural(String noivoMaeNatural) {
        this.noivoMaeNatural = noivoMaeNatural;
    }

    public String getNoivoPaiNatural() {
        return this.noivoPaiNatural;
    }

    public void setNoivoPaiNatural(String noivoPaiNatural) {
        this.noivoPaiNatural = noivoPaiNatural;
    }

    public String getNoivoResidParoq() {
        return this.noivoResidParoq;
    }

    public void setNoivoResidParoq(String noivoResidParoq) {
        this.noivoResidParoq = noivoResidParoq;
    }

    public String getPadreNome() {
        return this.padreNome;
    }

    public void setPadreNome(String padreNome) {
        this.padreNome = padreNome;
    }

    public String getTestemunha1() {
        return this.testemunha1;
    }

    public void setTestemunha1(String testemunha1) {
        this.testemunha1 = testemunha1;
    }

    public String getTestemunha2() {
        return this.testemunha2;
    }

    public void setTestemunha2(String testemunha2) {
        this.testemunha2 = testemunha2;
    }

    public byte[] getTestemunhas() {
        return this.testemunhas;
    }

    public void setTestemunhas(byte[] testemunhas) {
        this.testemunhas = testemunhas;
    }

    public int getImpressoes() {
        return this.impressoes;
    }

    public void setImpressoes(int impressoes) {
        this.impressoes = impressoes;
    }

    public Date getDtDialogo() {
        return this.dtDialogo;
    }

    public void setDtDialogo(Date dtDialogo) {
        this.dtDialogo = dtDialogo;
    }

    public String getComunidadeFreq() {
        return this.comunidadeFreq;
    }

    public void setComunidadeFreq(String comunidadeFreq) {
        this.comunidadeFreq = comunidadeFreq;
    }

    public String getBispoNome() {
        return this.bispoNome;
    }

    public void setBispoNome(String bispoNome) {
        this.bispoNome = bispoNome;
    }

    public Character getSituacaoProcesso() {
        return this.situacaoProcesso;
    }

    public void setSituacaoProcesso(Character situacaoProcesso) {
        this.situacaoProcesso = situacaoProcesso;
    }

    public byte[] getObservacao() {
        return this.observacao;
    }

    public void setObservacao(byte[] observacao) {
        this.observacao = observacao;
    }

    public Character getNotificou() {
        return this.notificou;
    }

    public void setNotificou(Character notificou) {
        this.notificou = notificou;
    }

    public String getCivilCartorNome() {
        return this.civilCartorNome;
    }

    public void setCivilCartorNome(String civilCartorNome) {
        this.civilCartorNome = civilCartorNome;
    }

    public Date getCivilDtHabilita() {
        return this.civilDtHabilita;
    }

    public void setCivilDtHabilita(Date civilDtHabilita) {
        this.civilDtHabilita = civilDtHabilita;
    }

    public Date getCivilDtCasamento() {
        return this.civilDtCasamento;
    }

    public void setCivilDtCasamento(Date civilDtCasamento) {
        this.civilDtCasamento = civilDtCasamento;
    }

    public String getCivilNomeJuiz() {
        return this.civilNomeJuiz;
    }

    public void setCivilNomeJuiz(String civilNomeJuiz) {
        this.civilNomeJuiz = civilNomeJuiz;
    }

    public String getCivilTestemunha1() {
        return this.civilTestemunha1;
    }

    public void setCivilTestemunha1(String civilTestemunha1) {
        this.civilTestemunha1 = civilTestemunha1;
    }

    public Character getCivilTestemunha1EstCivil() {
        return this.civilTestemunha1EstCivil;
    }

    public void setCivilTestemunha1EstCivil(Character civilTestemunha1EstCivil) {
        this.civilTestemunha1EstCivil = civilTestemunha1EstCivil;
    }

    public int getCivilTestemunha1Idade() {
        return this.civilTestemunha1Idade;
    }

    public void setCivilTestemunha1Idade(int civilTestemunha1Idade) {
        this.civilTestemunha1Idade = civilTestemunha1Idade;
    }

    public String getCivilTestemunhaProfissao() {
        return this.civilTestemunhaProfissao;
    }

    public void setCivilTestemunhaProfissao(String civilTestemunhaProfissao) {
        this.civilTestemunhaProfissao = civilTestemunhaProfissao;
    }

    public String getCivilTestemunha1Residencia() {
        return this.civilTestemunha1Residencia;
    }

    public void setCivilTestemunha1Residencia(String civilTestemunha1Residencia) {
        this.civilTestemunha1Residencia = civilTestemunha1Residencia;
    }

    public String getCivilTestemunha2() {
        return this.civilTestemunha2;
    }

    public void setCivilTestemunha2(String civilTestemunha2) {
        this.civilTestemunha2 = civilTestemunha2;
    }

    public Character getCivilTestemunha2EstCivil() {
        return this.civilTestemunha2EstCivil;
    }

    public void setCivilTestemunha2EstCivil(Character civilTestemunha2EstCivil) {
        this.civilTestemunha2EstCivil = civilTestemunha2EstCivil;
    }

    public int getCivilTestemunha2Idade() {
        return this.civilTestemunha2Idade;
    }

    public void setCivilTestemunha2Idade(int civilTestemunha2Idade) {
        this.civilTestemunha2Idade = civilTestemunha2Idade;
    }

    public String getCivilTestemunha2Profissao() {
        return this.civilTestemunha2Profissao;
    }

    public void setCivilTestemunha2Profissao(String civilTestemunha2Profissao) {
        this.civilTestemunha2Profissao = civilTestemunha2Profissao;
    }

    public String getCivilTestemunha2Residencia() {
        return this.civilTestemunha2Residencia;
    }

    public void setCivilTestemunha2Residencia(String civilTestemunha2Residencia) {
        this.civilTestemunha2Residencia = civilTestemunha2Residencia;
    }

    public String getCivilNomeNoiva() {
        return this.civilNomeNoiva;
    }

    public void setCivilNomeNoiva(String civilNomeNoiva) {
        this.civilNomeNoiva = civilNomeNoiva;
    }

    public String getRegimeCasa() {
        return this.regimeCasa;
    }

    public void setRegimeCasa(String regimeCasa) {
        this.regimeCasa = regimeCasa;
    }

    public byte[] getDispensaDespacho() {
        return this.dispensaDespacho;
    }

    public void setDispensaDespacho(byte[] dispensaDespacho) {
        this.dispensaDespacho = dispensaDespacho;
    }

    public String getDispensaConsaguidadeGrau() {
        return this.dispensaConsaguidadeGrau;
    }

    public void setDispensaConsaguidadeGrau(String dispensaConsaguidadeGrau) {
        this.dispensaConsaguidadeGrau = dispensaConsaguidadeGrau;
    }

    public String getDispensaDeItenIv() {
        return this.dispensaDeItenIv;
    }

    public void setDispensaDeItenIv(String dispensaDeItenIv) {
        this.dispensaDeItenIv = dispensaDeItenIv;
    }

    public String getDispensaMotivo() {
        return this.dispensaMotivo;
    }

    public void setDispensaMotivo(String dispensaMotivo) {
        this.dispensaMotivo = dispensaMotivo;
    }

    public Date getNoivaDtNascimento() {
        return this.noivaDtNascimento;
    }

    public void setNoivaDtNascimento(Date noivaDtNascimento) {
        this.noivaDtNascimento = noivaDtNascimento;
    }

    public String getDioceseTransferida() {
        return this.dioceseTransferida;
    }

    public void setDioceseTransferida(String dioceseTransferida) {
        this.dioceseTransferida = dioceseTransferida;
    }

    public String getParoquiatransferida() {
        return this.paroquiatransferida;
    }

    public void setParoquiatransferida(String paroquiatransferida) {
        this.paroquiatransferida = paroquiatransferida;
    }

    public String getComunidadeTransferida() {
        return this.comunidadeTransferida;
    }

    public void setComunidadeTransferida(String comunidadeTransferida) {
        this.comunidadeTransferida = comunidadeTransferida;
    }

    public String getParoco() {
        return this.paroco;
    }

    public void setParoco(String paroco) {
        this.paroco = paroco;
    }

    public String getNoivaParoqResidPeriodo() {
        return this.noivaParoqResidPeriodo;
    }

    public void setNoivaParoqResidPeriodo(String noivaParoqResidPeriodo) {
        this.noivaParoqResidPeriodo = noivaParoqResidPeriodo;
    }

    public String getNoivoParoqResidPeriodo() {
        return this.noivoParoqResidPeriodo;
    }

    public void setNoivoParoqResidPeriodo(String noivoParoqResidPeriodo) {
        this.noivoParoqResidPeriodo = noivoParoqResidPeriodo;
    }

    public String getNoivoSacramento() {
        return this.noivoSacramento;
    }

    public void setNoivoSacramento(String noivoSacramento) {
        this.noivoSacramento = noivoSacramento;
    }

    public String getNoivaSacramento() {
        return this.noivaSacramento;
    }

    public void setNoivaSacramento(String noivaSacramento) {
        this.noivaSacramento = noivaSacramento;
    }

    public String getEvangelico() {
        return this.evangelico;
    }

    public void setEvangelico(String evangelico) {
        this.evangelico = evangelico;
    }

    public byte[] getObsAnulacao() {
        return this.obsAnulacao;
    }

    public void setObsAnulacao(byte[] obsAnulacao) {
        this.obsAnulacao = obsAnulacao;
    }

    public String getNoivaCpf() {
        return this.noivaCpf;
    }

    public void setNoivaCpf(String noivaCpf) {
        this.noivaCpf = noivaCpf;
    }

    public String getNoivaRg() {
        return this.noivaRg;
    }

    public void setNoivaRg(String noivaRg) {
        this.noivaRg = noivaRg;
    }

    public String getNoivoCpf() {
        return this.noivoCpf;
    }

    public void setNoivoCpf(String noivoCpf) {
        this.noivoCpf = noivoCpf;
    }

    public String getNoivoRg() {
        return this.noivoRg;
    }

    public void setNoivoRg(String noivoRg) {
        this.noivoRg = noivoRg;
    }

    public String getCivilTestemunha1Cpf() {
        return this.civilTestemunha1Cpf;
    }

    public void setCivilTestemunha1Cpf(String civilTestemunha1Cpf) {
        this.civilTestemunha1Cpf = civilTestemunha1Cpf;
    }

    public String getCivilTestemunha1Rg() {
        return this.civilTestemunha1Rg;
    }

    public void setCivilTestemunha1Rg(String civilTestemunha1Rg) {
        this.civilTestemunha1Rg = civilTestemunha1Rg;
    }

    public String getCivilTestemunha2Cpf() {
        return this.civilTestemunha2Cpf;
    }

    public void setCivilTestemunha2Cpf(String civilTestemunha2Cpf) {
        this.civilTestemunha2Cpf = civilTestemunha2Cpf;
    }

    public String getCivilTestemunha2Rg() {
        return this.civilTestemunha2Rg;
    }

    public void setCivilTestemunha2Rg(String civilTestemunha2Rg) {
        this.civilTestemunha2Rg = civilTestemunha2Rg;
    }

    public Integer getIdApanegat() {
        return this.idApanegat;
    }

    public void setIdApanegat(Integer idApanegat) {
        this.idApanegat = idApanegat;
    }

}
