/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;


import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "APALEUCA", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"ID_APAPAROQ", "ID_APACOMUN", "LIVRO", "FOLHA", "TERMO"})})
public class ApaleucaEntity {

    @Column(name = "ID_APALEUCA", table = "APALEUCA", nullable = false)
    @Id
    private Integer idApaleuca;

    @Column(name = "ID_APAPAROQ", table = "APALEUCA")
    @Basic
    private Integer idApaparoq;

    @Column(name = "ID_APACOMUN", table = "APALEUCA")
    @Basic
    private Integer idApacomun;

    @Column(name = "ID_CFACLIFO_PAROQ", table = "APALEUCA")
    @Basic
    private Integer idCfaclifoParoq;

    @Column(name = "ID_CFACLIFO_COMUN", table = "APALEUCA")
    @Basic
    private Integer idCfaclifoComun;

    @Column(name = "US_CAD", table = "APALEUCA", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "APALEUCA")
    @Basic
    private String dtCad;

    @Column(name = "DT_ALT", table = "APALEUCA")
    @Basic
    private String dtAlt;

    @Column(name = "CT_INTEG", table = "APALEUCA")
    @Basic
    private Integer ctInteg;

    @Column(name = "GUID", table = "APALEUCA", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "LIVRO", table = "APALEUCA")
    @Basic
    private Integer livro;

    @Column(name = "FOLHA", table = "APALEUCA")
    @Basic
    private Integer folha;

    @Column(name = "TERMO", table = "APALEUCA")
    @Basic
    private Integer termo;

    @Column(name = "DT_EUCARISTIA", table = "APALEUCA")
    @Basic
        private String dtEucaristia;

    @Column(name = "CELEBRANTE", table = "APALEUCA", length = 60)
    @Basic
    private String celebrante;

    @Column(name = "NOME", table = "APALEUCA", length = 60)
    @Basic
    private String nome;

    @Column(name = "MAE", table = "APALEUCA", length = 60)
    @Basic
    private String mae;

    @Column(name = "PAI", table = "APALEUCA", length = 60)
    @Basic
    private String pai;

    @Column(name = "MAD_PAD", table = "APALEUCA", length = 60)
    @Basic
    private String madPad;

    @Column(name = "OBS", table = "APALEUCA")
    @Lob
    @Basic
    private byte[] obs;

    @Column(name = "IMPRESSOES", table = "APALEUCA", nullable = false)
    @Basic(optional = false)
    private int impressoes;

    @Column(name = "PAROCO", table = "APALEUCA", length = 60)
    @Basic
    private String paroco;

    public Integer getIdApaleuca() {
        return this.idApaleuca;
    }

    public void setIdApaleuca(Integer idApaleuca) {
        this.idApaleuca = idApaleuca;
    }

    public Integer getIdApaparoq() {
        return this.idApaparoq;
    }

    public void setIdApaparoq(Integer idApaparoq) {
        this.idApaparoq = idApaparoq;
    }

    public Integer getIdApacomun() {
        return this.idApacomun;
    }

    public void setIdApacomun(Integer idApacomun) {
        this.idApacomun = idApacomun;
    }

    public Integer getIdCfaclifoParoq() {
        return this.idCfaclifoParoq;
    }

    public void setIdCfaclifoParoq(Integer idCfaclifoParoq) {
        this.idCfaclifoParoq = idCfaclifoParoq;
    }

    public Integer getIdCfaclifoComun() {
        return this.idCfaclifoComun;
    }

    public void setIdCfaclifoComun(Integer idCfaclifoComun) {
        this.idCfaclifoComun = idCfaclifoComun;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public String getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(String dtCad) {
        this.dtCad = dtCad;
    }

    public String getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(String dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public Integer getLivro() {
        return this.livro;
    }

    public void setLivro(Integer livro) {
        this.livro = livro;
    }

    public Integer getFolha() {
        return this.folha;
    }

    public void setFolha(Integer folha) {
        this.folha = folha;
    }

    public Integer getTermo() {
        return this.termo;
    }

    public void setTermo(Integer termo) {
        this.termo = termo;
    }

    public String getDtEucaristia() {
        return this.dtEucaristia;
    }

    public void setDtEucaristia(String dtEucaristia) {
        this.dtEucaristia = dtEucaristia;
    }

    public String getCelebrante() {
        return this.celebrante;
    }

    public void setCelebrante(String celebrante) {
        this.celebrante = celebrante;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getMae() {
        return this.mae;
    }

    public void setMae(String mae) {
        this.mae = mae;
    }

    public String getPai() {
        return this.pai;
    }

    public void setPai(String pai) {
        this.pai = pai;
    }

    public String getMadPad() {
        return this.madPad;
    }

    public void setMadPad(String madPad) {
        this.madPad = madPad;
    }

    public byte[] getObs() {
        return this.obs;
    }

    public void setObs(byte[] obs) {
        this.obs = obs;
    }

    public int getImpressoes() {
        return this.impressoes;
    }

    public void setImpressoes(int impressoes) {
        this.impressoes = impressoes;
    }

    public String getParoco() {
        return this.paroco;
    }

    public void setParoco(String paroco) {
        this.paroco = paroco;
    }

}
