/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;


import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "APALAVER")
public class ApalaverEntity {

    @Column(name = "ID_APALAVER", table = "APALAVER", nullable = false)
    @Id
    private Integer idApalaver;

    @Column(name = "ID_CFACLIFO_PAROQ", table = "APALAVER")
    @Basic
    private Integer idCfaclifoParoq;

    @Column(name = "ID_CFACLIFO_COMUN", table = "APALAVER")
    @Basic
    private Integer idCfaclifoComun;

    @Column(name = "US_CAD", table = "APALAVER", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "APALAVER")
    @Basic
    private String dtCad;

    @Column(name = "DT_ALT", table = "APALAVER")
    @Basic
    private String dtAlt;

    @Column(name = "CT_INTEG", table = "APALAVER")
    @Basic
    private Integer ctInteg;

    @Column(name = "GUID", table = "APALAVER", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "DT_AVERBACAO", table = "APALAVER")
    @Basic
        private String dtAverbacao;

    @Column(name = "DT_APELACAO", table = "APALAVER")
    @Basic
        private String dtApelacao;

    @Column(name = "DT_CASAMENTO", table = "APALAVER")
    @Basic
        private String dtCasamento;

    @Column(name = "NOIVA", table = "APALAVER", length = 60)
    @Basic
    private String noiva;

    @Column(name = "NOIVO", table = "APALAVER", length = 60)
    @Basic
    private String noivo;

    @Column(name = "TRIB_HOMOLOGACAO", table = "APALAVER", length = 60)
    @Basic
    private String tribHomologacao;

    @Column(name = "TRIB_APELACAO", table = "APALAVER", length = 60)
    @Basic
    private String tribApelacao;

    @Column(name = "PAROQUIA", table = "APALAVER", length = 60)
    @Basic
    private String paroquia;

    @Column(name = "CIDADE", table = "APALAVER", length = 60)
    @Basic
    private String cidade;

    @Column(name = "LIVRO_CASAMENTO", table = "APALAVER")
    @Basic
    private Integer livroCasamento;

    @Column(name = "FOLHA_CASAMENTO", table = "APALAVER")
    @Basic
    private Integer folhaCasamento;

    @Column(name = "TERMO_CASAMENTO", table = "APALAVER")
    @Basic
    private Integer termoCasamento;

    @Column(name = "LIVRO", table = "APALAVER")
    @Basic
    private Integer livro;

    @Column(name = "FOLHA", table = "APALAVER")
    @Basic
    private Integer folha;

    @Column(name = "TERMO", table = "APALAVER")
    @Basic
    private Integer termo;

    @Column(name = "SENTENCA", table = "APALAVER")
    @Lob
    @Basic
    private byte[] sentenca;

    public Integer getIdApalaver() {
        return this.idApalaver;
    }

    public void setIdApalaver(Integer idApalaver) {
        this.idApalaver = idApalaver;
    }

    public Integer getIdCfaclifoParoq() {
        return this.idCfaclifoParoq;
    }

    public void setIdCfaclifoParoq(Integer idCfaclifoParoq) {
        this.idCfaclifoParoq = idCfaclifoParoq;
    }

    public Integer getIdCfaclifoComun() {
        return this.idCfaclifoComun;
    }

    public void setIdCfaclifoComun(Integer idCfaclifoComun) {
        this.idCfaclifoComun = idCfaclifoComun;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public String getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(String dtCad) {
        this.dtCad = dtCad;
    }

    public String getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(String dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getDtAverbacao() {
        return this.dtAverbacao;
    }

    public void setDtAverbacao(String dtAverbacao) {
        this.dtAverbacao = dtAverbacao;
    }

    public String getDtApelacao() {
        return this.dtApelacao;
    }

    public void setDtApelacao(String dtApelacao) {
        this.dtApelacao = dtApelacao;
    }

    public String getDtCasamento() {
        return this.dtCasamento;
    }

    public void setDtCasamento(String dtCasamento) {
        this.dtCasamento = dtCasamento;
    }

    public String getNoiva() {
        return this.noiva;
    }

    public void setNoiva(String noiva) {
        this.noiva = noiva;
    }

    public String getNoivo() {
        return this.noivo;
    }

    public void setNoivo(String noivo) {
        this.noivo = noivo;
    }

    public String getTribHomologacao() {
        return this.tribHomologacao;
    }

    public void setTribHomologacao(String tribHomologacao) {
        this.tribHomologacao = tribHomologacao;
    }

    public String getTribApelacao() {
        return this.tribApelacao;
    }

    public void setTribApelacao(String tribApelacao) {
        this.tribApelacao = tribApelacao;
    }

    public String getParoquia() {
        return this.paroquia;
    }

    public void setParoquia(String paroquia) {
        this.paroquia = paroquia;
    }

    public String getCidade() {
        return this.cidade;
    }

    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    public Integer getLivroCasamento() {
        return this.livroCasamento;
    }

    public void setLivroCasamento(Integer livroCasamento) {
        this.livroCasamento = livroCasamento;
    }

    public Integer getFolhaCasamento() {
        return this.folhaCasamento;
    }

    public void setFolhaCasamento(Integer folhaCasamento) {
        this.folhaCasamento = folhaCasamento;
    }

    public Integer getTermoCasamento() {
        return this.termoCasamento;
    }

    public void setTermoCasamento(Integer termoCasamento) {
        this.termoCasamento = termoCasamento;
    }

    public Integer getLivro() {
        return this.livro;
    }

    public void setLivro(Integer livro) {
        this.livro = livro;
    }

    public Integer getFolha() {
        return this.folha;
    }

    public void setFolha(Integer folha) {
        this.folha = folha;
    }

    public Integer getTermo() {
        return this.termo;
    }

    public void setTermo(Integer termo) {
        this.termo = termo;
    }

    public byte[] getSentenca() {
        return this.sentenca;
    }

    public void setSentenca(byte[] sentenca) {
        this.sentenca = sentenca;
    }

}
