/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;


import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "APAPASTO")
public class ApapastoEntity {

    @Column(name = "ID_APAPASTO", table = "APAPASTO", nullable = false)
    @Id
    private Integer idApapasto;

    @Column(name = "US_CAD", table = "APAPASTO", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "APAPASTO")
    @Basic
    private String dtCad;

    @Column(name = "DT_ALT", table = "APAPASTO")
    @Basic
    private String dtAlt;

    @Column(name = "CT_INTEG", table = "APAPASTO")
    @Basic
    private Integer ctInteg;

    @Column(name = "GUID", table = "APAPASTO", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "CODIGO", table = "APAPASTO")
    @Basic
    private Integer codigo;

    @Column(name = "NOME", table = "APAPASTO", length = 40)
    @Basic
    private String nome;

    public Integer getIdApapasto() {
        return this.idApapasto;
    }

    public void setIdApapasto(Integer idApapasto) {
        this.idApapasto = idApapasto;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public String getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(String dtCad) {
        this.dtCad = dtCad;
    }

    public String getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(String dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

}
