/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;


import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "CBALOTES", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"ID_SMAEMPRE", "ANO", "NUMERO"})})
public class CbalotesEntity {

    @Column(name = "ID_CBALOTES", table = "CBALOTES", nullable = false)
    @Id
    private Integer idCbalotes;

    @Column(name = "ID_SMAEMPRE", table = "CBALOTES", nullable = false)
    @Basic(optional = false)
    private int idSmaempre;

    @Column(name = "GUID", table = "CBALOTES", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "CBALOTES", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "CBALOTES")
    @Basic
    private String dtCad;

    @Column(name = "DT_ALT", table = "CBALOTES")
    @Basic
    private String dtAlt;

    @Column(name = "CT_INTEG", table = "CBALOTES")
    @Basic
    private Integer ctInteg;

    @Column(name = "ANO", table = "CBALOTES", nullable = false)
    @Basic(optional = false)
    private int ano;

    @Column(name = "NUMERO", table = "CBALOTES", nullable = false)
    @Basic(optional = false)
    private int numero;

    @Column(name = "ORIGEM", table = "CBALOTES", nullable = false, length = 18)
    @Basic(optional = false)
    private String origem;

    @Column(name = "SITUACAO", table = "CBALOTES", nullable = false)
    @Basic(optional = false)
    private Character situacao;

    @Column(name = "DT_INICIO", table = "CBALOTES", nullable = false)
    @Basic(optional = false)
        private String dtInicio;

    @Column(name = "DT_FIM", table = "CBALOTES", nullable = false)
    @Basic(optional = false)
        private String dtFim;

    @Column(name = "VL_CAPA_LOTE", table = "CBALOTES", nullable = false)
    @Basic(optional = false)
    private double vlCapaLote;

    @Column(name = "VALOR", table = "CBALOTES", nullable = false)
    @Basic(optional = false)
    private double valor;

    @Column(name = "TAG", table = "CBALOTES")
    @Basic
    private Character tag;

    public Integer getIdCbalotes() {
        return this.idCbalotes;
    }

    public void setIdCbalotes(Integer idCbalotes) {
        this.idCbalotes = idCbalotes;
    }

    public int getIdSmaempre() {
        return this.idSmaempre;
    }

    public void setIdSmaempre(int idSmaempre) {
        this.idSmaempre = idSmaempre;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public String getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(String dtCad) {
        this.dtCad = dtCad;
    }

    public String getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(String dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public int getAno() {
        return this.ano;
    }

    public void setAno(int ano) {
        this.ano = ano;
    }

    public int getNumero() {
        return this.numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    public String getOrigem() {
        return this.origem;
    }

    public void setOrigem(String origem) {
        this.origem = origem;
    }

    public Character getSituacao() {
        return this.situacao;
    }

    public void setSituacao(Character situacao) {
        this.situacao = situacao;
    }

    public String getDtInicio() {
        return this.dtInicio;
    }

    public void setDtInicio(String dtInicio) {
        this.dtInicio = dtInicio;
    }

    public String getDtFim() {
        return this.dtFim;
    }

    public void setDtFim(String dtFim) {
        this.dtFim = dtFim;
    }

    public double getVlCapaLote() {
        return this.vlCapaLote;
    }

    public void setVlCapaLote(double vlCapaLote) {
        this.vlCapaLote = vlCapaLote;
    }

    public double getValor() {
        return this.valor;
    }

    public void setValor(double valor) {
        this.valor = valor;
    }

    public Character getTag() {
        return this.tag;
    }

    public void setTag(Character tag) {
        this.tag = tag;
    }

}
