/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "CCACANDI")
public class CcacandiEntity {

    @Column(name = "ID_CCACANDI", table = "CCACANDI", nullable = false)
    @Id
    private Integer idCcacandi;

    @Column(name = "ID_CCACONCU", table = "CCACANDI")
    @Basic
    private Integer idCcaconcu;

    @Column(name = "ID_CCACARGO", table = "CCACANDI")
    @Basic
    private Integer idCcacargo;

    @Column(name = "ID_CCASALAP", table = "CCACANDI")
    @Basic
    private Integer idCcasalap;

    @Column(name = "ID_CCAESCOL", table = "CCACANDI")
    @Basic
    private Integer idCcaescol;

    @Column(name = "US_CAD", table = "CCACANDI", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "CCACANDI")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtCad;

    @Column(name = "DT_ALT", table = "CCACANDI")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtAlt;

    @Column(name = "CT_INTEG", table = "CCACANDI")
    @Basic
    private Integer ctInteg;

    @Column(name = "GUID", table = "CCACANDI", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "CODIGO", table = "CCACANDI")
    @Basic
    private Integer codigo;

    @Column(name = "NOME", table = "CCACANDI", length = 60)
    @Basic
    private String nome;

    @Column(name = "RG", table = "CCACANDI", length = 18)
    @Basic
    private String rg;

    @Column(name = "ORGAO_RG", table = "CCACANDI", length = 40)
    @Basic
    private String orgaoRg;

    @Column(name = "SEXO", table = "CCACANDI")
    @Basic
    private Character sexo;

    @Column(name = "DATANASCIMENTO", table = "CCACANDI")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date datanascimento;

    @Column(name = "ESTADOCIVIL", table = "CCACANDI")
    @Basic
    private Character estadocivil;

    @Column(name = "NFILHOS", table = "CCACANDI")
    @Basic
    private Integer nfilhos;

    @Column(name = "NECESPECIAL", table = "CCACANDI")
    @Basic
    private Character necespecial;

    @Column(name = "CEP", table = "CCACANDI", length = 9)
    @Basic
    private String cep;

    @Column(name = "LOGRADOURO", table = "CCACANDI", length = 128)
    @Basic
    private String logradouro;

    @Column(name = "NUMERO", table = "CCACANDI")
    @Basic
    private Integer numero;

    @Column(name = "BAIRRO", table = "CCACANDI", length = 128)
    @Basic
    private String bairro;

    @Column(name = "CIDADE", table = "CCACANDI", length = 128)
    @Basic
    private String cidade;

    @Column(name = "UF", table = "CCACANDI", length = 40)
    @Basic
    private String uf;

    @Column(name = "DDD", table = "CCACANDI")
    @Basic
    private Integer ddd;

    @Column(name = "TELEFONE", table = "CCACANDI", length = 10)
    @Basic
    private String telefone;

    @Column(name = "EMAIL", table = "CCACANDI", length = 128)
    @Basic
    private String email;

    @Column(name = "PROVAESCRITA", table = "CCACANDI", nullable = false)
    @Basic(optional = false)
    private double provaescrita;

    @Column(name = "PROVAPRATICA", table = "CCACANDI", nullable = false)
    @Basic(optional = false)
    private double provapratica;

    @Column(name = "PROVATITULOS", table = "CCACANDI", nullable = false)
    @Basic(optional = false)
    private double provatitulos;

    @Column(name = "PROVARESISTENCIA", table = "CCACANDI")
    @Basic
    private Character provaresistencia;

    @Column(name = "NOSSO_NUMERO", table = "CCACANDI")
    @Basic
    private Integer nossoNumero;

    @Column(name = "DATAHORA", table = "CCACANDI", length = 40)
    @Basic
    private String datahora;

    @Column(name = "SITE", table = "CCACANDI")
    @Basic
    private Character site;

    @Column(name = "PAGO", table = "CCACANDI")
    @Basic
    private Character pago;

    @Column(name = "VL_INSCRICAO", table = "CCACANDI", nullable = false)
    @Basic(optional = false)
    private double vlInscricao;

    @Column(name = "DATA_PGTO", table = "CCACANDI")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date dataPgto;

    public Integer getIdCcacandi() {
        return this.idCcacandi;
    }

    public void setIdCcacandi(Integer idCcacandi) {
        this.idCcacandi = idCcacandi;
    }

    public Integer getIdCcaconcu() {
        return this.idCcaconcu;
    }

    public void setIdCcaconcu(Integer idCcaconcu) {
        this.idCcaconcu = idCcaconcu;
    }

    public Integer getIdCcacargo() {
        return this.idCcacargo;
    }

    public void setIdCcacargo(Integer idCcacargo) {
        this.idCcacargo = idCcacargo;
    }

    public Integer getIdCcasalap() {
        return this.idCcasalap;
    }

    public void setIdCcasalap(Integer idCcasalap) {
        this.idCcasalap = idCcasalap;
    }

    public Integer getIdCcaescol() {
        return this.idCcaescol;
    }

    public void setIdCcaescol(Integer idCcaescol) {
        this.idCcaescol = idCcaescol;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public Date getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(Date dtCad) {
        this.dtCad = dtCad;
    }

    public Date getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(Date dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getRg() {
        return this.rg;
    }

    public void setRg(String rg) {
        this.rg = rg;
    }

    public String getOrgaoRg() {
        return this.orgaoRg;
    }

    public void setOrgaoRg(String orgaoRg) {
        this.orgaoRg = orgaoRg;
    }

    public Character getSexo() {
        return this.sexo;
    }

    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }

    public Date getDatanascimento() {
        return this.datanascimento;
    }

    public void setDatanascimento(Date datanascimento) {
        this.datanascimento = datanascimento;
    }

    public Character getEstadocivil() {
        return this.estadocivil;
    }

    public void setEstadocivil(Character estadocivil) {
        this.estadocivil = estadocivil;
    }

    public Integer getNfilhos() {
        return this.nfilhos;
    }

    public void setNfilhos(Integer nfilhos) {
        this.nfilhos = nfilhos;
    }

    public Character getNecespecial() {
        return this.necespecial;
    }

    public void setNecespecial(Character necespecial) {
        this.necespecial = necespecial;
    }

    public String getCep() {
        return this.cep;
    }

    public void setCep(String cep) {
        this.cep = cep;
    }

    public String getLogradouro() {
        return this.logradouro;
    }

    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }

    public Integer getNumero() {
        return this.numero;
    }

    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    public String getBairro() {
        return this.bairro;
    }

    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    public String getCidade() {
        return this.cidade;
    }

    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    public String getUf() {
        return this.uf;
    }

    public void setUf(String uf) {
        this.uf = uf;
    }

    public Integer getDdd() {
        return this.ddd;
    }

    public void setDdd(Integer ddd) {
        this.ddd = ddd;
    }

    public String getTelefone() {
        return this.telefone;
    }

    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public double getProvaescrita() {
        return this.provaescrita;
    }

    public void setProvaescrita(double provaescrita) {
        this.provaescrita = provaescrita;
    }

    public double getProvapratica() {
        return this.provapratica;
    }

    public void setProvapratica(double provapratica) {
        this.provapratica = provapratica;
    }

    public double getProvatitulos() {
        return this.provatitulos;
    }

    public void setProvatitulos(double provatitulos) {
        this.provatitulos = provatitulos;
    }

    public Character getProvaresistencia() {
        return this.provaresistencia;
    }

    public void setProvaresistencia(Character provaresistencia) {
        this.provaresistencia = provaresistencia;
    }

    public Integer getNossoNumero() {
        return this.nossoNumero;
    }

    public void setNossoNumero(Integer nossoNumero) {
        this.nossoNumero = nossoNumero;
    }

    public String getDatahora() {
        return this.datahora;
    }

    public void setDatahora(String datahora) {
        this.datahora = datahora;
    }

    public Character getSite() {
        return this.site;
    }

    public void setSite(Character site) {
        this.site = site;
    }

    public Character getPago() {
        return this.pago;
    }

    public void setPago(Character pago) {
        this.pago = pago;
    }

    public double getVlInscricao() {
        return this.vlInscricao;
    }

    public void setVlInscricao(double vlInscricao) {
        this.vlInscricao = vlInscricao;
    }

    public Date getDataPgto() {
        return this.dataPgto;
    }

    public void setDataPgto(Date dataPgto) {
        this.dataPgto = dataPgto;
    }

}
