/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

@Entity
@Table(name = "CFACLIFO")
public class CfaclifoEntity {

    @Column(name = "ID_CFACLIFO", table = "CFACLIFO", nullable = false)
    @Id
    private Integer idCfaclifo;

    @Column(name = "ID_CFAPAISE", table = "CFACLIFO")
    @Basic
    private Integer idCfapaise;

    @Column(name = "ID_CFAPROFI", table = "CFACLIFO")
    @Basic
    private Integer idCfaprofi;

    @Column(name = "ID_CFATIMEF", table = "CFACLIFO")
    @Basic
    private Integer idCfatimef;

    @Column(name = "ID_CFAPARTI", table = "CFACLIFO")
    @Basic
    private Integer idCfaparti;

    @Column(name = "ID_CFATPFOR", table = "CFACLIFO")
    @Basic
    private Integer idCfatpfor;

    @Column(name = "ID_CFAATIVI", table = "CFACLIFO")
    @Basic
    private Integer idCfaativi;

    @Column(name = "ID_CFAAREAS", table = "CFACLIFO")
    @Basic
    private Integer idCfaareas;

    @Column(name = "ID_CFATPCLI", table = "CFACLIFO")
    @Basic
    private Integer idCfatpcli;

    @Column(name = "ID_CFASTATU", table = "CFACLIFO")
    @Basic
    private Integer idCfastatu;

    @Column(name = "ID_CFAPROFI_CONJ", table = "CFACLIFO")
    @Basic
    private Integer idCfaprofiConj;

    @Column(name = "ID_CFAPROFI_CARGO_CONJ", table = "CFACLIFO")
    @Basic
    private Integer idCfaprofiCargoConj;

    @Column(name = "ID_CFAPROFI_CARGO", table = "CFACLIFO")
    @Basic
    private Integer idCfaprofiCargo;

    @Column(name = "ID_CFAPORTA_BANCO", table = "CFACLIFO")
    @Basic
    private Integer idCfaportaBanco;

    @Column(name = "ID_CFAPORTA_BANCO_CONJ", table = "CFACLIFO")
    @Basic
    private Integer idCfaportaBancoConj;

    @Column(name = "ID_CFAESTAD_UF_ORGAO", table = "CFACLIFO")
    @Basic
    private Integer idCfaestadUfOrgao;

    @Column(name = "ID_CFAESTAD_UF_ORG_CONJ", table = "CFACLIFO")
    @Basic
    private Integer idCfaestadUfOrgConj;

    @Column(name = "ID_CFAESTAD_NATURAL", table = "CFACLIFO")
    @Basic
    private Integer idCfaestadNatural;

    @Column(name = "ID_CFACIDAD_NATURAL", table = "CFACLIFO")
    @Basic
    private Integer idCfacidadNatural;

    @Column(name = "ID_CFAESTAD_UF_HABILIT", table = "CFACLIFO")
    @Basic
    private Integer idCfaestadUfHabilit;

    @Column(name = "ID_CFACCRED_CONJ", table = "CFACLIFO")
    @Basic
    private Integer idCfaccredConj;

    @Column(name = "ID_CFACCRED", table = "CFACLIFO")
    @Basic
    private Integer idCfaccred;

    @Column(name = "ID_SMAEMPRE", table = "CFACLIFO")
    @Basic
    private Integer idSmaempre;

    @Column(name = "ID_SMADEPTO", table = "CFACLIFO")
    @Basic
    private Integer idSmadepto;

    @Column(name = "ID_CFACLIFO_DIOCE", table = "CFACLIFO")
    @Basic
    private Integer idCfaclifoDioce;

    @Column(name = "ID_CFACLIFO_PAROQ", table = "CFACLIFO")
    @Basic
    private Integer idCfaclifoParoq;

    @Column(name = "ID_CFACLIFO_COMUN", table = "CFACLIFO")
    @Basic
    private Integer idCfaclifoComun;

    @Column(name = "ID_PASTORAL_PARTICIPA", table = "CFACLIFO")
    @Basic
    private Integer idPastoralParticipa;

    @Column(name = "ID_PASTORAL_GOSTARIA", table = "CFACLIFO")
    @Basic
    private Integer idPastoralGostaria;

    @Column(name = "GUID", table = "CFACLIFO", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "CFACLIFO", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "CFACLIFO")
    @Basic
    private String dtCad;

    @Column(name = "DT_ALT", table = "CFACLIFO")
    @Basic
    private String dtAlt;

    @Column(name = "CT_INTEG", table = "CFACLIFO")
    @Basic
    private Integer ctInteg;

    @Column(name = "CPF_CGC", table = "CFACLIFO", length = 18)
    @Basic
    private String cpfCgc;

    @Column(name = "CPF_CGC_SEQ", table = "CFACLIFO", nullable = false)
    @Basic(optional = false)
    private int cpfCgcSeq;

    @Column(name = "IE_RG", table = "CFACLIFO", length = 18)
    @Basic
    private String ieRg;

    @Column(name = "ORGAO_EMISSOR", table = "CFACLIFO", length = 3)
    @Basic
    private String orgaoEmissor;

    @Column(name = "NOME_RAZAO", table = "CFACLIFO", nullable = false, length = 60)
    @Basic(optional = false)
    private String nomeRazao;

    @Column(name = "DT_NASCIMENTO", table = "CFACLIFO")
    @Basic
    private String dtNascimento;

    @Column(name = "CODIGO_CLI", table = "CFACLIFO")
    @Basic
    private Integer codigoCli;

    @Column(name = "CODIGO_FOR", table = "CFACLIFO")
    @Basic
    private Integer codigoFor;

    @Column(name = "CODIGO_FUN", table = "CFACLIFO")
    @Basic
    private Integer codigoFun;

    @Column(name = "CODIGO_USU", table = "CFACLIFO")
    @Basic
    private Integer codigoUsu;

    @Column(name = "CODIGO_REP", table = "CFACLIFO")
    @Basic
    private Integer codigoRep;

    @Column(name = "CODIGO_CON", table = "CFACLIFO")
    @Basic
    private Integer codigoCon;

    @Column(name = "CODIGO_TRA", table = "CFACLIFO")
    @Basic
    private Integer codigoTra;

    @Column(name = "CODIGO_APA", table = "CFACLIFO")
    @Basic
    private Integer codigoApa;

    @Column(name = "CLIENTE", table = "CFACLIFO")
    @Basic
    private Character cliente;

    @Column(name = "FORNECEDOR", table = "CFACLIFO")
    @Basic
    private Character fornecedor;

    @Column(name = "FUNCIONARIO", table = "CFACLIFO")
    @Basic
    private Character funcionario;

    @Column(name = "USUARIO", table = "CFACLIFO")
    @Basic
    private Character usuario;

    @Column(name = "REPRESENTANTE", table = "CFACLIFO")
    @Basic
    private Character representante;

    @Column(name = "CONCORRENTE", table = "CFACLIFO")
    @Basic
    private Character concorrente;

    @Column(name = "TRANSPORTADORA", table = "CFACLIFO")
    @Basic
    private Character transportadora;

    @Column(name = "NOME_FANTASIA", table = "CFACLIFO", length = 60)
    @Basic
    private String nomeFantasia;

    @Column(name = "SELECIONADO", table = "CFACLIFO")
    @Basic
    private Character selecionado;

    @Column(name = "SEXO", table = "CFACLIFO")
    @Basic
    private Character sexo;

    @Column(name = "INSC_JUNTA", table = "CFACLIFO", length = 18)
    @Basic
    private String inscJunta;

    @Column(name = "INSC_SUFRAMA", table = "CFACLIFO", length = 18)
    @Basic
    private String inscSuframa;

    @Column(name = "INSC_MUNICIPAL", table = "CFACLIFO", length = 18)
    @Basic
    private String inscMunicipal;

    @Column(name = "INSC_PRODUTOR", table = "CFACLIFO", length = 18)
    @Basic
    private String inscProdutor;

    @Column(name = "COMPLEMENTO_CARGO", table = "CFACLIFO")
    @Lob
    @Basic
    private byte[] complementoCargo;

    @Column(name = "RENDA_MES_GIRO", table = "CFACLIFO", nullable = false)
    @Basic(optional = false)
    private double rendaMesGiro;

    @Column(name = "CAPITAL_SOCIAL", table = "CFACLIFO", nullable = false)
    @Basic(optional = false)
    private double capitalSocial;

    @Column(name = "EST_MERCADORIAS", table = "CFACLIFO", nullable = false)
    @Basic(optional = false)
    private double estMercadorias;

    @Column(name = "EST_MAT_PRIMA", table = "CFACLIFO", nullable = false)
    @Basic(optional = false)
    private double estMatPrima;

    @Column(name = "MOVTO_VENDAS", table = "CFACLIFO", nullable = false)
    @Basic(optional = false)
    private double movtoVendas;

    @Column(name = "DESPESAS", table = "CFACLIFO", nullable = false)
    @Basic(optional = false)
    private double despesas;

    @Column(name = "EMPRESA_TRAB", table = "CFACLIFO", length = 60)
    @Basic
    private String empresaTrab;

    @Column(name = "NUM_CART_HABILIT", table = "CFACLIFO", length = 18)
    @Basic
    private String numCartHabilit;

    @Column(name = "DT_ADMISSAO", table = "CFACLIFO")
    @Basic
    private String dtAdmissao;

    @Column(name = "NUM_REG_HABILIT", table = "CFACLIFO", length = 18)
    @Basic
    private String numRegHabilit;

    @Column(name = "DT_VENCT_HABILIT", table = "CFACLIFO")
    @Basic
    private String dtVenctHabilit;

    @Column(name = "FUMANTE", table = "CFACLIFO")
    @Basic
    private Character fumante;

    @Column(name = "OBS", table = "CFACLIFO")
    @Basic
    private String obs;

    @Column(name = "MORADIA", table = "CFACLIFO")
    @Basic
    private Character moradia;

    @Column(name = "MORA_DESDE", table = "CFACLIFO")
    @Basic
    private String moraDesde;

    @Column(name = "PESSOA", table = "CFACLIFO")
    @Basic
    private Character pessoa;

    @Column(name = "CIVIL", table = "CFACLIFO")
    @Basic
    private Character civil;

    @Column(name = "CONJUGE", table = "CFACLIFO", length = 60)
    @Basic
    private String conjuge;

    @Column(name = "CPF_CONJUGE", table = "CFACLIFO", length = 18)
    @Basic
    private String cpfConjuge;

    @Column(name = "DT_NASC_CONJ", table = "CFACLIFO")
    @Basic
    private String dtNascConj;

    @Column(name = "PAI", table = "CFACLIFO", length = 60)
    @Basic
    private String pai;

    @Column(name = "CPF_PAI", table = "CFACLIFO", length = 18)
    @Basic
    private String cpfPai;

    @Column(name = "DT_NASC_PAI", table = "CFACLIFO")
    @Basic
    private String dtNascPai;

    @Column(name = "MAE", table = "CFACLIFO", length = 60)
    @Basic
    private String mae;

    @Column(name = "CPF_MAE", table = "CFACLIFO", length = 18)
    @Basic
    private String cpfMae;

    @Column(name = "DT_NASC_MAE", table = "CFACLIFO")
    @Basic
    private String dtNascMae;

    @Column(name = "ESCOLARIDADE", table = "CFACLIFO")
    @Basic
    private Character escolaridade;

    @Column(name = "FORMACAO_SUPERIOR", table = "CFACLIFO", length = 18)
    @Basic
    private String formacaoSuperior;

    @Column(name = "AREAS_INTERESSE", table = "CFACLIFO", length = 128)
    @Basic
    private String areasInteresse;

    @Column(name = "QTDE_FUNCIONARIOS", table = "CFACLIFO", nullable = false)
    @Basic(optional = false)
    private int qtdeFuncionarios;

    @Column(name = "OUTRAS_RENDAS", table = "CFACLIFO", nullable = false)
    @Basic(optional = false)
    private double outrasRendas;

    @Column(name = "LIMITE_CARTAO", table = "CFACLIFO", nullable = false)
    @Basic(optional = false)
    private double limiteCartao;

    @Column(name = "NUM_DEP_MAIOR", table = "CFACLIFO", nullable = false)
    @Basic(optional = false)
    private int numDepMaior;

    @Column(name = "NUM_DEP_MENOR", table = "CFACLIFO", nullable = false)
    @Basic(optional = false)
    private int numDepMenor;

    @Column(name = "COMPLEMENTO_CARGO_CONJ", table = "CFACLIFO")
    @Lob
    @Basic
    private byte[] complementoCargoConj;

    @Column(name = "RG_CONJUGE", table = "CFACLIFO", length = 18)
    @Basic
    private String rgConjuge;

    @Column(name = "ORGAO_EMISSOR_CONJ", table = "CFACLIFO", length = 3)
    @Basic
    private String orgaoEmissorConj;

    @Column(name = "LIMITE_CONJUGE", table = "CFACLIFO", nullable = false)
    @Basic(optional = false)
    private double limiteConjuge;

    @Column(name = "EMPRESA_CONJUGE", table = "CFACLIFO", length = 60)
    @Basic
    private String empresaConjuge;

    @Column(name = "ADMISSAO_CONJUGE", table = "CFACLIFO")
    @Basic
    private String admissaoConjuge;

    @Column(name = "RENDA_CONJUGE", table = "CFACLIFO", nullable = false)
    @Basic(optional = false)
    private double rendaConjuge;

    @Column(name = "AGENCIA_CONJ", table = "CFACLIFO")
    @Basic
    private Integer agenciaConj;

    @Column(name = "DG_AG_CONJ", table = "CFACLIFO")
    @Basic
    private Character dgAgConj;

    @Column(name = "CONTA_CONJ", table = "CFACLIFO")
    @Basic
    private Integer contaConj;

    @Column(name = "DG_CT_CONJ", table = "CFACLIFO", length = 2)
    @Basic
    private String dgCtConj;

    @Column(name = "TIPO_CONTA_CONJ", table = "CFACLIFO")
    @Basic
    private Character tipoContaConj;

    @Column(name = "DT_ABERTURA_CT_CONJ", table = "CFACLIFO")
    @Basic
    private String dtAberturaCtConj;

    @Column(name = "VALIDADE_CT_CONJ", table = "CFACLIFO")
    @Basic
    private String validadeCtConj;

    @Column(name = "CT_ESPECIAL_CONJ", table = "CFACLIFO")
    @Basic
    private Character ctEspecialConj;

    @Column(name = "AGENCIA", table = "CFACLIFO")
    @Basic
    private Integer agencia;

    @Column(name = "DG_AG", table = "CFACLIFO")
    @Basic
    private Character dgAg;

    @Column(name = "CONTA", table = "CFACLIFO")
    @Basic
    private Integer conta;

    @Column(name = "DG_CT", table = "CFACLIFO", length = 2)
    @Basic
    private String dgCt;

    @Column(name = "TIPO_CT", table = "CFACLIFO")
    @Basic
    private Character tipoCt;

    @Column(name = "VALIDADE_CARTAO", table = "CFACLIFO")
    @Basic
    private String validadeCartao;

    @Column(name = "DT_ABERTURA_CONTA", table = "CFACLIFO")
    @Basic
    private String dtAberturaConta;

    @Column(name = "CONTA_ESPECIAL", table = "CFACLIFO")
    @Basic
    private Character contaEspecial;

    @Column(name = "CONVENIO", table = "CFACLIFO")
    @Basic
    private Character convenio;

    @Column(name = "MASCARA_PRODUTO", table = "CFACLIFO")
    @Basic
    private Character mascaraProduto;

    @Column(name = "CONSUMIDOR_REVENDA", table = "CFACLIFO")
    @Basic
    private Character consumidorRevenda;

    @Column(name = "LOCAL_TRABALHO", table = "CFACLIFO", length = 60)
    @Basic
    private String localTrabalho;

    @Column(name = "MANEQUIM", table = "CFACLIFO", nullable = false)
    @Basic(optional = false)
    private int manequim;

    @Column(name = "MANEQUIM_CONJUGE", table = "CFACLIFO", nullable = false)
    @Basic(optional = false)
    private int manequimConjuge;

    @Column(name = "CALCADO", table = "CFACLIFO", nullable = false)
    @Basic(optional = false)
    private int calcado;

    @Column(name = "CALCADO_CONJUGE", table = "CFACLIFO", nullable = false)
    @Basic(optional = false)
    private int calcadoConjuge;

    @Column(name = "TIPO_FUNCIONARIO", table = "CFACLIFO", length = 18)
    @Basic
    private String tipoFuncionario;

    @Column(name = "SENHA", table = "CFACLIFO", length = 20)
    @Basic
    private String senha;

    @Column(name = "ATIVO", table = "CFACLIFO", nullable = false)
    @Basic(optional = false)
    private Character ativo;

    @Column(name = "ENVIAR_EXTRATO", table = "CFACLIFO")
    @Basic
    private Character enviarExtrato;

    @Column(name = "TIPO_EXTRATO", table = "CFACLIFO")
    @Basic
    private Character tipoExtrato;

    @Column(name = "CONJ_PODE_COMPRAR", table = "CFACLIFO")
    @Basic
    private Character conjPodeComprar;

    @Column(name = "DT_ULT_COMPRA", table = "CFACLIFO")
    @Basic
    private String dtUltCompra;

    @Column(name = "DT_RENOVACAO", table = "CFACLIFO")
    @Basic
    private String dtRenovacao;

    @Column(name = "IS_DIZIMISTA", table = "CFACLIFO")
    @Basic
    private Character isDizimista;

    @Column(name = "IS_CATEQUISTA", table = "CFACLIFO")
    @Basic
    private Character isCatequista;

    @Column(name = "IS_CATEQUIZANDO", table = "CFACLIFO")
    @Basic
    private Character isCatequizando;

    @Column(name = "IS_RELIGIOSO", table = "CFACLIFO")
    @Basic
    private Character isReligioso;

    @Column(name = "IS_PADRE", table = "CFACLIFO")
    @Basic
    private Character isPadre;

    @Column(name = "IS_LEIGO", table = "CFACLIFO")
    @Basic
    private Character isLeigo;

    @Column(name = "IS_MINISTRO", table = "CFACLIFO")
    @Basic
    private Character isMinistro;

    @Column(name = "IS_OUTROS", table = "CFACLIFO")
    @Basic
    private Character isOutros;

    @Column(name = "IS_DIOCESE", table = "CFACLIFO")
    @Basic
    private Character isDiocese;

    @Column(name = "IS_PAROQUIA", table = "CFACLIFO")
    @Basic
    private Character isParoquia;

    @Column(name = "IS_COMUNIDADE", table = "CFACLIFO")
    @Basic
    private Character isComunidade;

    @Column(name = "IS_CONTRIBUINTE", table = "CFACLIFO")
    @Basic
    private Character isContribuinte;

    @Column(name = "IS_FUNERARIA", table = "CFACLIFO")
    @Basic
    private Character isFuneraria;

    @Column(name = "PAROQUIA_ANTERIOR", table = "CFACLIFO", length = 60)
    @Basic
    private String paroquiaAnterior;

    @Column(name = "PADRE_PAROCO_VIGARIO", table = "CFACLIFO")
    @Basic
    private Character padreParocoVigario;

    @Column(name = "PADRE_TEM_PROCURACAO", table = "CFACLIFO")
    @Basic
    private Character padreTemProcuracao;

    @Column(name = "PADRE_DT_EXPEDICAO", table = "CFACLIFO")
    @Basic
    private String padreDtExpedicao;

    @Column(name = "PADRE_DT_VALIDADE", table = "CFACLIFO")
    @Basic
    private String padreDtValidade;

    @Column(name = "PADRE_LIVRO_PROCURACAO", table = "CFACLIFO")
    @Basic
    private Integer padreLivroProcuracao;

    @Column(name = "PADRE_FOLHA_PROCURACAO", table = "CFACLIFO")
    @Basic
    private Integer padreFolhaProcuracao;

    @Column(name = "PADRE_VINCULACAO_DR", table = "CFACLIFO")
    @Basic
    private Character padreVinculacaoDr;

    @Column(name = "PADRE_DT_CHEGADA_DIOCESE", table = "CFACLIFO")
    @Basic
    private String padreDtChegadaDiocese;

    @Column(name = "PADRE_DT_ORDENACAO", table = "CFACLIFO")
    @Basic
    private String padreDtOrdenacao;

    @Column(name = "PADRE_DT_PRESBITERAL", table = "CFACLIFO")
    @Basic
    private String padreDtPresbiteral;

    @Column(name = "PADRE_DT_EPISCOPAL", table = "CFACLIFO")
    @Basic
    private String padreDtEpiscopal;

    @Column(name = "PADRE_DIOCESE_ORDENACAO", table = "CFACLIFO", length = 60)
    @Basic
    private String padreDioceseOrdenacao;

    @Column(name = "PADRE_DIOCESE_INCARDINACAO", table = "CFACLIFO", length = 60)
    @Basic
    private String padreDioceseIncardinacao;

    @Column(name = "PADRE_DIOCESE_RESIDENCIA", table = "CFACLIFO", length = 60)
    @Basic
    private String padreDioceseResidencia;

    @Column(name = "PADRE_ESTUDOS_FEITOS", table = "CFACLIFO")
    @Lob
    @Basic
    private byte[] padreEstudosFeitos;

    @Column(name = "CAT_JA_FOI", table = "CFACLIFO")
    @Basic
    private Character catJaFoi;

    @Column(name = "CAT_JA_FOI_ONDE", table = "CFACLIFO", length = 60)
    @Basic
    private String catJaFoiOnde;

    @Column(name = "CAT_JA_FOI_DT_INICIO", table = "CFACLIFO")
    @Basic
    private String catJaFoiDtInicio;

    @Column(name = "CAT_JA_FOI_DT_FINAL", table = "CFACLIFO")
    @Basic
    private String catJaFoiDtFinal;

    @Column(name = "CAT_ATUAL_DT_INICIO", table = "CFACLIFO")
    @Basic
    private String catAtualDtInicio;

    @Column(name = "CAT_ATUAL_DT_FINAL", table = "CFACLIFO")
    @Basic
    private String catAtualDtFinal;

    @Column(name = "CAT_ATUAL_N_MATRICULAS", table = "CFACLIFO")
    @Basic
    private Integer catAtualNMatriculas;

    @Column(name = "CAT_ATUAL_N_FORMANDOS", table = "CFACLIFO")
    @Basic
    private Integer catAtualNFormandos;

    @Column(name = "CAT_ATUAL_USA_AGENDA", table = "CFACLIFO")
    @Basic
    private Character catAtualUsaAgenda;

    @Column(name = "DT_CASAMENTO", table = "CFACLIFO")
    @Basic
    private String dtCasamento;

    @Column(name = "TIPO_SANGUINEO", table = "CFACLIFO")
    @Basic
    private Character tipoSanguineo;

    @Column(name = "TIPO_SANG_RH", table = "CFACLIFO")
    @Basic
    private Character tipoSangRh;

    @Column(name = "IE_RG_DT_EXPEDICAO", table = "CFACLIFO")
    @Basic
    private String ieRgDtExpedicao;

    @Column(name = "TEMPO_CONTRIBUICAO", table = "CFACLIFO", length = 40)
    @Basic
    private String tempoContribuicao;

    @Column(name = "ZONA", table = "CFACLIFO")
    @Basic
    private Character zona;

    @Column(name = "GRUPO_REFLEXAO", table = "CFACLIFO")
    @Basic
    private Character grupoReflexao;

    @Column(name = "QUANT_GRUPO_REFLEXAO", table = "CFACLIFO")
    @Basic
    private Integer quantGrupoReflexao;

    @Column(name = "LEIGO_OUTROS_OBSERVACAO", table = "CFACLIFO")
    @Lob
    @Basic
    private byte[] leigoOutrosObservacao;

    @Column(name = "NUMERO_FICHA", table = "CFACLIFO")
    @Basic
    private Integer numeroFicha;

    @Column(name = "PARTICIPA_PASTORAL", table = "CFACLIFO")
    @Basic
    private Character participaPastoral;

    @Column(name = "GOSTARIA_PASTORAL", table = "CFACLIFO")
    @Basic
    private Character gostariaPastoral;

    @Column(name = "CODIGO", table = "CFACLIFO")
    @Basic
    private Integer codigo;

    @Column(name = "DT_BATIZADO", table = "CFACLIFO")
    @Basic
    private String dtBatizado;

    @Column(name = "DT_EUCARISTIA", table = "CFACLIFO")
    @Basic
    private String dtEucaristia;

    @Column(name = "PAROQ_BATIZADO", table = "CFACLIFO", length = 60)
    @Basic
    private String paroqBatizado;

    @Column(name = "PAROQ_EUCARISTIA", table = "CFACLIFO", length = 60)
    @Basic
    private String paroqEucaristia;

    @Column(name = "EMAIL_GERAL", table = "CFACLIFO", length = 128)
    @Basic
    private String emailGeral;

    @Column(name = "EMAIL_FINAN", table = "CFACLIFO", length = 128)
    @Basic
    private String emailFinan;

    @Column(name = "EMAIL_CONTABIL", table = "CFACLIFO", length = 128)
    @Basic
    private String emailContabil;

    @Column(name = "EMAIL_COMPRAS", table = "CFACLIFO", length = 128)
    @Basic
    private String emailCompras;

    @Column(name = "SITE", table = "CFACLIFO", length = 128)
    @Basic
    private String site;

    @Column(name = "CRT", table = "CFACLIFO")
    @Basic
    private Character crt;

    @Column(name = "SUFRAMA_OK", table = "CFACLIFO")
    @Basic
    private Character suframaOk;

    @Column(name = "DT_VALIDADE_SUFRAMA", table = "CFACLIFO")
    @Basic
    private String dtValidadeSuframa;

    public Integer getIdCfaclifo() {
        return this.idCfaclifo;
    }

    public void setIdCfaclifo(Integer idCfaclifo) {
        this.idCfaclifo = idCfaclifo;
    }

    public Integer getIdCfapaise() {
        return this.idCfapaise;
    }

    public void setIdCfapaise(Integer idCfapaise) {
        this.idCfapaise = idCfapaise;
    }

    public Integer getIdCfaprofi() {
        return this.idCfaprofi;
    }

    public void setIdCfaprofi(Integer idCfaprofi) {
        this.idCfaprofi = idCfaprofi;
    }

    public Integer getIdCfatimef() {
        return this.idCfatimef;
    }

    public void setIdCfatimef(Integer idCfatimef) {
        this.idCfatimef = idCfatimef;
    }

    public Integer getIdCfaparti() {
        return this.idCfaparti;
    }

    public void setIdCfaparti(Integer idCfaparti) {
        this.idCfaparti = idCfaparti;
    }

    public Integer getIdCfatpfor() {
        return this.idCfatpfor;
    }

    public void setIdCfatpfor(Integer idCfatpfor) {
        this.idCfatpfor = idCfatpfor;
    }

    public Integer getIdCfaativi() {
        return this.idCfaativi;
    }

    public void setIdCfaativi(Integer idCfaativi) {
        this.idCfaativi = idCfaativi;
    }

    public Integer getIdCfaareas() {
        return this.idCfaareas;
    }

    public void setIdCfaareas(Integer idCfaareas) {
        this.idCfaareas = idCfaareas;
    }

    public Integer getIdCfatpcli() {
        return this.idCfatpcli;
    }

    public void setIdCfatpcli(Integer idCfatpcli) {
        this.idCfatpcli = idCfatpcli;
    }

    public Integer getIdCfastatu() {
        return this.idCfastatu;
    }

    public void setIdCfastatu(Integer idCfastatu) {
        this.idCfastatu = idCfastatu;
    }

    public Integer getIdCfaprofiConj() {
        return this.idCfaprofiConj;
    }

    public void setIdCfaprofiConj(Integer idCfaprofiConj) {
        this.idCfaprofiConj = idCfaprofiConj;
    }

    public Integer getIdCfaprofiCargoConj() {
        return this.idCfaprofiCargoConj;
    }

    public void setIdCfaprofiCargoConj(Integer idCfaprofiCargoConj) {
        this.idCfaprofiCargoConj = idCfaprofiCargoConj;
    }

    public Integer getIdCfaprofiCargo() {
        return this.idCfaprofiCargo;
    }

    public void setIdCfaprofiCargo(Integer idCfaprofiCargo) {
        this.idCfaprofiCargo = idCfaprofiCargo;
    }

    public Integer getIdCfaportaBanco() {
        return this.idCfaportaBanco;
    }

    public void setIdCfaportaBanco(Integer idCfaportaBanco) {
        this.idCfaportaBanco = idCfaportaBanco;
    }

    public Integer getIdCfaportaBancoConj() {
        return this.idCfaportaBancoConj;
    }

    public void setIdCfaportaBancoConj(Integer idCfaportaBancoConj) {
        this.idCfaportaBancoConj = idCfaportaBancoConj;
    }

    public Integer getIdCfaestadUfOrgao() {
        return this.idCfaestadUfOrgao;
    }

    public void setIdCfaestadUfOrgao(Integer idCfaestadUfOrgao) {
        this.idCfaestadUfOrgao = idCfaestadUfOrgao;
    }

    public Integer getIdCfaestadUfOrgConj() {
        return this.idCfaestadUfOrgConj;
    }

    public void setIdCfaestadUfOrgConj(Integer idCfaestadUfOrgConj) {
        this.idCfaestadUfOrgConj = idCfaestadUfOrgConj;
    }

    public Integer getIdCfaestadNatural() {
        return this.idCfaestadNatural;
    }

    public void setIdCfaestadNatural(Integer idCfaestadNatural) {
        this.idCfaestadNatural = idCfaestadNatural;
    }

    public Integer getIdCfacidadNatural() {
        return this.idCfacidadNatural;
    }

    public void setIdCfacidadNatural(Integer idCfacidadNatural) {
        this.idCfacidadNatural = idCfacidadNatural;
    }

    public Integer getIdCfaestadUfHabilit() {
        return this.idCfaestadUfHabilit;
    }

    public void setIdCfaestadUfHabilit(Integer idCfaestadUfHabilit) {
        this.idCfaestadUfHabilit = idCfaestadUfHabilit;
    }

    public Integer getIdCfaccredConj() {
        return this.idCfaccredConj;
    }

    public void setIdCfaccredConj(Integer idCfaccredConj) {
        this.idCfaccredConj = idCfaccredConj;
    }

    public Integer getIdCfaccred() {
        return this.idCfaccred;
    }

    public void setIdCfaccred(Integer idCfaccred) {
        this.idCfaccred = idCfaccred;
    }

    public Integer getIdSmaempre() {
        return this.idSmaempre;
    }

    public void setIdSmaempre(Integer idSmaempre) {
        this.idSmaempre = idSmaempre;
    }

    public Integer getIdSmadepto() {
        return this.idSmadepto;
    }

    public void setIdSmadepto(Integer idSmadepto) {
        this.idSmadepto = idSmadepto;
    }

    public Integer getIdCfaclifoDioce() {
        return this.idCfaclifoDioce;
    }

    public void setIdCfaclifoDioce(Integer idCfaclifoDioce) {
        this.idCfaclifoDioce = idCfaclifoDioce;
    }

    public Integer getIdCfaclifoParoq() {
        return this.idCfaclifoParoq;
    }

    public void setIdCfaclifoParoq(Integer idCfaclifoParoq) {
        this.idCfaclifoParoq = idCfaclifoParoq;
    }

    public Integer getIdCfaclifoComun() {
        return this.idCfaclifoComun;
    }

    public void setIdCfaclifoComun(Integer idCfaclifoComun) {
        this.idCfaclifoComun = idCfaclifoComun;
    }

    public Integer getIdPastoralParticipa() {
        return this.idPastoralParticipa;
    }

    public void setIdPastoralParticipa(Integer idPastoralParticipa) {
        this.idPastoralParticipa = idPastoralParticipa;
    }

    public Integer getIdPastoralGostaria() {
        return this.idPastoralGostaria;
    }

    public void setIdPastoralGostaria(Integer idPastoralGostaria) {
        this.idPastoralGostaria = idPastoralGostaria;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public String getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(String dtCad) {
        this.dtCad = dtCad;
    }

    public String getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(String dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public String getCpfCgc() {
        return this.cpfCgc;
    }

    public void setCpfCgc(String cpfCgc) {
        this.cpfCgc = cpfCgc;
    }

    public int getCpfCgcSeq() {
        return this.cpfCgcSeq;
    }

    public void setCpfCgcSeq(int cpfCgcSeq) {
        this.cpfCgcSeq = cpfCgcSeq;
    }

    public String getIeRg() {
        return this.ieRg;
    }

    public void setIeRg(String ieRg) {
        this.ieRg = ieRg;
    }

    public String getOrgaoEmissor() {
        return this.orgaoEmissor;
    }

    public void setOrgaoEmissor(String orgaoEmissor) {
        this.orgaoEmissor = orgaoEmissor;
    }

    public String getNomeRazao() {
        return this.nomeRazao;
    }

    public void setNomeRazao(String nomeRazao) {
        this.nomeRazao = nomeRazao;
    }

    public String getDtNascimento() {
        return this.dtNascimento;
    }

    public void setDtNascimento(String dtNascimento) {
        this.dtNascimento = dtNascimento;
    }

    public Integer getCodigoCli() {
        return this.codigoCli;
    }

    public void setCodigoCli(Integer codigoCli) {
        this.codigoCli = codigoCli;
    }

    public Integer getCodigoFor() {
        return this.codigoFor;
    }

    public void setCodigoFor(Integer codigoFor) {
        this.codigoFor = codigoFor;
    }

    public Integer getCodigoFun() {
        return this.codigoFun;
    }

    public void setCodigoFun(Integer codigoFun) {
        this.codigoFun = codigoFun;
    }

    public Integer getCodigoUsu() {
        return this.codigoUsu;
    }

    public void setCodigoUsu(Integer codigoUsu) {
        this.codigoUsu = codigoUsu;
    }

    public Integer getCodigoRep() {
        return this.codigoRep;
    }

    public void setCodigoRep(Integer codigoRep) {
        this.codigoRep = codigoRep;
    }

    public Integer getCodigoCon() {
        return this.codigoCon;
    }

    public void setCodigoCon(Integer codigoCon) {
        this.codigoCon = codigoCon;
    }

    public Integer getCodigoTra() {
        return this.codigoTra;
    }

    public void setCodigoTra(Integer codigoTra) {
        this.codigoTra = codigoTra;
    }

    public Integer getCodigoApa() {
        return this.codigoApa;
    }

    public void setCodigoApa(Integer codigoApa) {
        this.codigoApa = codigoApa;
    }

    public Character getCliente() {
        return this.cliente;
    }

    public void setCliente(Character cliente) {
        this.cliente = cliente;
    }

    public Character getFornecedor() {
        return this.fornecedor;
    }

    public void setFornecedor(Character fornecedor) {
        this.fornecedor = fornecedor;
    }

    public Character getFuncionario() {
        return this.funcionario;
    }

    public void setFuncionario(Character funcionario) {
        this.funcionario = funcionario;
    }

    public Character getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Character usuario) {
        this.usuario = usuario;
    }

    public Character getRepresentante() {
        return this.representante;
    }

    public void setRepresentante(Character representante) {
        this.representante = representante;
    }

    public Character getConcorrente() {
        return this.concorrente;
    }

    public void setConcorrente(Character concorrente) {
        this.concorrente = concorrente;
    }

    public Character getTransportadora() {
        return this.transportadora;
    }

    public void setTransportadora(Character transportadora) {
        this.transportadora = transportadora;
    }

    public String getNomeFantasia() {
        return this.nomeFantasia;
    }

    public void setNomeFantasia(String nomeFantasia) {
        this.nomeFantasia = nomeFantasia;
    }

    public Character getSelecionado() {
        return this.selecionado;
    }

    public void setSelecionado(Character selecionado) {
        this.selecionado = selecionado;
    }

    public Character getSexo() {
        return this.sexo;
    }

    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }

    public String getInscJunta() {
        return this.inscJunta;
    }

    public void setInscJunta(String inscJunta) {
        this.inscJunta = inscJunta;
    }

    public String getInscSuframa() {
        return this.inscSuframa;
    }

    public void setInscSuframa(String inscSuframa) {
        this.inscSuframa = inscSuframa;
    }

    public String getInscMunicipal() {
        return this.inscMunicipal;
    }

    public void setInscMunicipal(String inscMunicipal) {
        this.inscMunicipal = inscMunicipal;
    }

    public String getInscProdutor() {
        return this.inscProdutor;
    }

    public void setInscProdutor(String inscProdutor) {
        this.inscProdutor = inscProdutor;
    }

    public byte[] getComplementoCargo() {
        return this.complementoCargo;
    }

    public void setComplementoCargo(byte[] complementoCargo) {
        this.complementoCargo = complementoCargo;
    }

    public double getRendaMesGiro() {
        return this.rendaMesGiro;
    }

    public void setRendaMesGiro(double rendaMesGiro) {
        this.rendaMesGiro = rendaMesGiro;
    }

    public double getCapitalSocial() {
        return this.capitalSocial;
    }

    public void setCapitalSocial(double capitalSocial) {
        this.capitalSocial = capitalSocial;
    }

    public double getEstMercadorias() {
        return this.estMercadorias;
    }

    public void setEstMercadorias(double estMercadorias) {
        this.estMercadorias = estMercadorias;
    }

    public double getEstMatPrima() {
        return this.estMatPrima;
    }

    public void setEstMatPrima(double estMatPrima) {
        this.estMatPrima = estMatPrima;
    }

    public double getMovtoVendas() {
        return this.movtoVendas;
    }

    public void setMovtoVendas(double movtoVendas) {
        this.movtoVendas = movtoVendas;
    }

    public double getDespesas() {
        return this.despesas;
    }

    public void setDespesas(double despesas) {
        this.despesas = despesas;
    }

    public String getEmpresaTrab() {
        return this.empresaTrab;
    }

    public void setEmpresaTrab(String empresaTrab) {
        this.empresaTrab = empresaTrab;
    }

    public String getNumCartHabilit() {
        return this.numCartHabilit;
    }

    public void setNumCartHabilit(String numCartHabilit) {
        this.numCartHabilit = numCartHabilit;
    }

    public String getDtAdmissao() {
        return this.dtAdmissao;
    }

    public void setDtAdmissao(String dtAdmissao) {
        this.dtAdmissao = dtAdmissao;
    }

    public String getNumRegHabilit() {
        return this.numRegHabilit;
    }

    public void setNumRegHabilit(String numRegHabilit) {
        this.numRegHabilit = numRegHabilit;
    }

    public String getDtVenctHabilit() {
        return this.dtVenctHabilit;
    }

    public void setDtVenctHabilit(String dtVenctHabilit) {
        this.dtVenctHabilit = dtVenctHabilit;
    }

    public Character getFumante() {
        return this.fumante;
    }

    public void setFumante(Character fumante) {
        this.fumante = fumante;
    }

    public String getObs() {
        return this.obs;
    }

    public void setObs(String obs) {
        this.obs = obs;
    }

    public Character getMoradia() {
        return this.moradia;
    }

    public void setMoradia(Character moradia) {
        this.moradia = moradia;
    }

    public String getMoraDesde() {
        return this.moraDesde;
    }

    public void setMoraDesde(String moraDesde) {
        this.moraDesde = moraDesde;
    }

    public Character getPessoa() {
        return this.pessoa;
    }

    public void setPessoa(Character pessoa) {
        this.pessoa = pessoa;
    }

    public Character getCivil() {
        return this.civil;
    }

    public void setCivil(Character civil) {
        this.civil = civil;
    }

    public String getConjuge() {
        return this.conjuge;
    }

    public void setConjuge(String conjuge) {
        this.conjuge = conjuge;
    }

    public String getCpfConjuge() {
        return this.cpfConjuge;
    }

    public void setCpfConjuge(String cpfConjuge) {
        this.cpfConjuge = cpfConjuge;
    }

    public String getDtNascConj() {
        return this.dtNascConj;
    }

    public void setDtNascConj(String dtNascConj) {
        this.dtNascConj = dtNascConj;
    }

    public String getPai() {
        return this.pai;
    }

    public void setPai(String pai) {
        this.pai = pai;
    }

    public String getCpfPai() {
        return this.cpfPai;
    }

    public void setCpfPai(String cpfPai) {
        this.cpfPai = cpfPai;
    }

    public String getDtNascPai() {
        return this.dtNascPai;
    }

    public void setDtNascPai(String dtNascPai) {
        this.dtNascPai = dtNascPai;
    }

    public String getMae() {
        return this.mae;
    }

    public void setMae(String mae) {
        this.mae = mae;
    }

    public String getCpfMae() {
        return this.cpfMae;
    }

    public void setCpfMae(String cpfMae) {
        this.cpfMae = cpfMae;
    }

    public String getDtNascMae() {
        return this.dtNascMae;
    }

    public void setDtNascMae(String dtNascMae) {
        this.dtNascMae = dtNascMae;
    }

    public Character getEscolaridade() {
        return this.escolaridade;
    }

    public void setEscolaridade(Character escolaridade) {
        this.escolaridade = escolaridade;
    }

    public String getFormacaoSuperior() {
        return this.formacaoSuperior;
    }

    public void setFormacaoSuperior(String formacaoSuperior) {
        this.formacaoSuperior = formacaoSuperior;
    }

    public String getAreasInteresse() {
        return this.areasInteresse;
    }

    public void setAreasInteresse(String areasInteresse) {
        this.areasInteresse = areasInteresse;
    }

    public int getQtdeFuncionarios() {
        return this.qtdeFuncionarios;
    }

    public void setQtdeFuncionarios(int qtdeFuncionarios) {
        this.qtdeFuncionarios = qtdeFuncionarios;
    }

    public double getOutrasRendas() {
        return this.outrasRendas;
    }

    public void setOutrasRendas(double outrasRendas) {
        this.outrasRendas = outrasRendas;
    }

    public double getLimiteCartao() {
        return this.limiteCartao;
    }

    public void setLimiteCartao(double limiteCartao) {
        this.limiteCartao = limiteCartao;
    }

    public int getNumDepMaior() {
        return this.numDepMaior;
    }

    public void setNumDepMaior(int numDepMaior) {
        this.numDepMaior = numDepMaior;
    }

    public int getNumDepMenor() {
        return this.numDepMenor;
    }

    public void setNumDepMenor(int numDepMenor) {
        this.numDepMenor = numDepMenor;
    }

    public byte[] getComplementoCargoConj() {
        return this.complementoCargoConj;
    }

    public void setComplementoCargoConj(byte[] complementoCargoConj) {
        this.complementoCargoConj = complementoCargoConj;
    }

    public String getRgConjuge() {
        return this.rgConjuge;
    }

    public void setRgConjuge(String rgConjuge) {
        this.rgConjuge = rgConjuge;
    }

    public String getOrgaoEmissorConj() {
        return this.orgaoEmissorConj;
    }

    public void setOrgaoEmissorConj(String orgaoEmissorConj) {
        this.orgaoEmissorConj = orgaoEmissorConj;
    }

    public double getLimiteConjuge() {
        return this.limiteConjuge;
    }

    public void setLimiteConjuge(double limiteConjuge) {
        this.limiteConjuge = limiteConjuge;
    }

    public String getEmpresaConjuge() {
        return this.empresaConjuge;
    }

    public void setEmpresaConjuge(String empresaConjuge) {
        this.empresaConjuge = empresaConjuge;
    }

    public String getAdmissaoConjuge() {
        return this.admissaoConjuge;
    }

    public void setAdmissaoConjuge(String admissaoConjuge) {
        this.admissaoConjuge = admissaoConjuge;
    }

    public double getRendaConjuge() {
        return this.rendaConjuge;
    }

    public void setRendaConjuge(double rendaConjuge) {
        this.rendaConjuge = rendaConjuge;
    }

    public Integer getAgenciaConj() {
        return this.agenciaConj;
    }

    public void setAgenciaConj(Integer agenciaConj) {
        this.agenciaConj = agenciaConj;
    }

    public Character getDgAgConj() {
        return this.dgAgConj;
    }

    public void setDgAgConj(Character dgAgConj) {
        this.dgAgConj = dgAgConj;
    }

    public Integer getContaConj() {
        return this.contaConj;
    }

    public void setContaConj(Integer contaConj) {
        this.contaConj = contaConj;
    }

    public String getDgCtConj() {
        return this.dgCtConj;
    }

    public void setDgCtConj(String dgCtConj) {
        this.dgCtConj = dgCtConj;
    }

    public Character getTipoContaConj() {
        return this.tipoContaConj;
    }

    public void setTipoContaConj(Character tipoContaConj) {
        this.tipoContaConj = tipoContaConj;
    }

    public String getDtAberturaCtConj() {
        return this.dtAberturaCtConj;
    }

    public void setDtAberturaCtConj(String dtAberturaCtConj) {
        this.dtAberturaCtConj = dtAberturaCtConj;
    }

    public String getValidadeCtConj() {
        return this.validadeCtConj;
    }

    public void setValidadeCtConj(String validadeCtConj) {
        this.validadeCtConj = validadeCtConj;
    }

    public Character getCtEspecialConj() {
        return this.ctEspecialConj;
    }

    public void setCtEspecialConj(Character ctEspecialConj) {
        this.ctEspecialConj = ctEspecialConj;
    }

    public Integer getAgencia() {
        return this.agencia;
    }

    public void setAgencia(Integer agencia) {
        this.agencia = agencia;
    }

    public Character getDgAg() {
        return this.dgAg;
    }

    public void setDgAg(Character dgAg) {
        this.dgAg = dgAg;
    }

    public Integer getConta() {
        return this.conta;
    }

    public void setConta(Integer conta) {
        this.conta = conta;
    }

    public String getDgCt() {
        return this.dgCt;
    }

    public void setDgCt(String dgCt) {
        this.dgCt = dgCt;
    }

    public Character getTipoCt() {
        return this.tipoCt;
    }

    public void setTipoCt(Character tipoCt) {
        this.tipoCt = tipoCt;
    }

    public String getValidadeCartao() {
        return this.validadeCartao;
    }

    public void setValidadeCartao(String validadeCartao) {
        this.validadeCartao = validadeCartao;
    }

    public String getDtAberturaConta() {
        return this.dtAberturaConta;
    }

    public void setDtAberturaConta(String dtAberturaConta) {
        this.dtAberturaConta = dtAberturaConta;
    }

    public Character getContaEspecial() {
        return this.contaEspecial;
    }

    public void setContaEspecial(Character contaEspecial) {
        this.contaEspecial = contaEspecial;
    }

    public Character getConvenio() {
        return this.convenio;
    }

    public void setConvenio(Character convenio) {
        this.convenio = convenio;
    }

    public Character getMascaraProduto() {
        return this.mascaraProduto;
    }

    public void setMascaraProduto(Character mascaraProduto) {
        this.mascaraProduto = mascaraProduto;
    }

    public Character getConsumidorRevenda() {
        return this.consumidorRevenda;
    }

    public void setConsumidorRevenda(Character consumidorRevenda) {
        this.consumidorRevenda = consumidorRevenda;
    }

    public String getLocalTrabalho() {
        return this.localTrabalho;
    }

    public void setLocalTrabalho(String localTrabalho) {
        this.localTrabalho = localTrabalho;
    }

    public int getManequim() {
        return this.manequim;
    }

    public void setManequim(int manequim) {
        this.manequim = manequim;
    }

    public int getManequimConjuge() {
        return this.manequimConjuge;
    }

    public void setManequimConjuge(int manequimConjuge) {
        this.manequimConjuge = manequimConjuge;
    }

    public int getCalcado() {
        return this.calcado;
    }

    public void setCalcado(int calcado) {
        this.calcado = calcado;
    }

    public int getCalcadoConjuge() {
        return this.calcadoConjuge;
    }

    public void setCalcadoConjuge(int calcadoConjuge) {
        this.calcadoConjuge = calcadoConjuge;
    }

    public String getTipoFuncionario() {
        return this.tipoFuncionario;
    }

    public void setTipoFuncionario(String tipoFuncionario) {
        this.tipoFuncionario = tipoFuncionario;
    }

    public String getSenha() {
        return this.senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public Character getAtivo() {
        return this.ativo;
    }

    public void setAtivo(Character ativo) {
        this.ativo = ativo;
    }

    public Character getEnviarExtrato() {
        return this.enviarExtrato;
    }

    public void setEnviarExtrato(Character enviarExtrato) {
        this.enviarExtrato = enviarExtrato;
    }

    public Character getTipoExtrato() {
        return this.tipoExtrato;
    }

    public void setTipoExtrato(Character tipoExtrato) {
        this.tipoExtrato = tipoExtrato;
    }

    public Character getConjPodeComprar() {
        return this.conjPodeComprar;
    }

    public void setConjPodeComprar(Character conjPodeComprar) {
        this.conjPodeComprar = conjPodeComprar;
    }

    public String getDtUltCompra() {
        return this.dtUltCompra;
    }

    public void setDtUltCompra(String dtUltCompra) {
        this.dtUltCompra = dtUltCompra;
    }

    public String getDtRenovacao() {
        return this.dtRenovacao;
    }

    public void setDtRenovacao(String dtRenovacao) {
        this.dtRenovacao = dtRenovacao;
    }

    public Character getIsDizimista() {
        return this.isDizimista;
    }

    public void setIsDizimista(Character isDizimista) {
        this.isDizimista = isDizimista;
    }

    public Character getIsCatequista() {
        return this.isCatequista;
    }

    public void setIsCatequista(Character isCatequista) {
        this.isCatequista = isCatequista;
    }

    public Character getIsCatequizando() {
        return this.isCatequizando;
    }

    public void setIsCatequizando(Character isCatequizando) {
        this.isCatequizando = isCatequizando;
    }

    public Character getIsReligioso() {
        return this.isReligioso;
    }

    public void setIsReligioso(Character isReligioso) {
        this.isReligioso = isReligioso;
    }

    public Character getIsPadre() {
        return this.isPadre;
    }

    public void setIsPadre(Character isPadre) {
        this.isPadre = isPadre;
    }

    public Character getIsLeigo() {
        return this.isLeigo;
    }

    public void setIsLeigo(Character isLeigo) {
        this.isLeigo = isLeigo;
    }

    public Character getIsMinistro() {
        return this.isMinistro;
    }

    public void setIsMinistro(Character isMinistro) {
        this.isMinistro = isMinistro;
    }

    public Character getIsOutros() {
        return this.isOutros;
    }

    public void setIsOutros(Character isOutros) {
        this.isOutros = isOutros;
    }

    public Character getIsDiocese() {
        return this.isDiocese;
    }

    public void setIsDiocese(Character isDiocese) {
        this.isDiocese = isDiocese;
    }

    public Character getIsParoquia() {
        return this.isParoquia;
    }

    public void setIsParoquia(Character isParoquia) {
        this.isParoquia = isParoquia;
    }

    public Character getIsComunidade() {
        return this.isComunidade;
    }

    public void setIsComunidade(Character isComunidade) {
        this.isComunidade = isComunidade;
    }

    public Character getIsContribuinte() {
        return this.isContribuinte;
    }

    public void setIsContribuinte(Character isContribuinte) {
        this.isContribuinte = isContribuinte;
    }

    public Character getIsFuneraria() {
        return this.isFuneraria;
    }

    public void setIsFuneraria(Character isFuneraria) {
        this.isFuneraria = isFuneraria;
    }

    public String getParoquiaAnterior() {
        return this.paroquiaAnterior;
    }

    public void setParoquiaAnterior(String paroquiaAnterior) {
        this.paroquiaAnterior = paroquiaAnterior;
    }

    public Character getPadreParocoVigario() {
        return this.padreParocoVigario;
    }

    public void setPadreParocoVigario(Character padreParocoVigario) {
        this.padreParocoVigario = padreParocoVigario;
    }

    public Character getPadreTemProcuracao() {
        return this.padreTemProcuracao;
    }

    public void setPadreTemProcuracao(Character padreTemProcuracao) {
        this.padreTemProcuracao = padreTemProcuracao;
    }

    public String getPadreDtExpedicao() {
        return this.padreDtExpedicao;
    }

    public void setPadreDtExpedicao(String padreDtExpedicao) {
        this.padreDtExpedicao = padreDtExpedicao;
    }

    public String getPadreDtValidade() {
        return this.padreDtValidade;
    }

    public void setPadreDtValidade(String padreDtValidade) {
        this.padreDtValidade = padreDtValidade;
    }

    public Integer getPadreLivroProcuracao() {
        return this.padreLivroProcuracao;
    }

    public void setPadreLivroProcuracao(Integer padreLivroProcuracao) {
        this.padreLivroProcuracao = padreLivroProcuracao;
    }

    public Integer getPadreFolhaProcuracao() {
        return this.padreFolhaProcuracao;
    }

    public void setPadreFolhaProcuracao(Integer padreFolhaProcuracao) {
        this.padreFolhaProcuracao = padreFolhaProcuracao;
    }

    public Character getPadreVinculacaoDr() {
        return this.padreVinculacaoDr;
    }

    public void setPadreVinculacaoDr(Character padreVinculacaoDr) {
        this.padreVinculacaoDr = padreVinculacaoDr;
    }

    public String getPadreDtChegadaDiocese() {
        return this.padreDtChegadaDiocese;
    }

    public void setPadreDtChegadaDiocese(String padreDtChegadaDiocese) {
        this.padreDtChegadaDiocese = padreDtChegadaDiocese;
    }

    public String getPadreDtOrdenacao() {
        return this.padreDtOrdenacao;
    }

    public void setPadreDtOrdenacao(String padreDtOrdenacao) {
        this.padreDtOrdenacao = padreDtOrdenacao;
    }

    public String getPadreDtPresbiteral() {
        return this.padreDtPresbiteral;
    }

    public void setPadreDtPresbiteral(String padreDtPresbiteral) {
        this.padreDtPresbiteral = padreDtPresbiteral;
    }

    public String getPadreDtEpiscopal() {
        return this.padreDtEpiscopal;
    }

    public void setPadreDtEpiscopal(String padreDtEpiscopal) {
        this.padreDtEpiscopal = padreDtEpiscopal;
    }

    public String getPadreDioceseOrdenacao() {
        return this.padreDioceseOrdenacao;
    }

    public void setPadreDioceseOrdenacao(String padreDioceseOrdenacao) {
        this.padreDioceseOrdenacao = padreDioceseOrdenacao;
    }

    public String getPadreDioceseIncardinacao() {
        return this.padreDioceseIncardinacao;
    }

    public void setPadreDioceseIncardinacao(String padreDioceseIncardinacao) {
        this.padreDioceseIncardinacao = padreDioceseIncardinacao;
    }

    public String getPadreDioceseResidencia() {
        return this.padreDioceseResidencia;
    }

    public void setPadreDioceseResidencia(String padreDioceseResidencia) {
        this.padreDioceseResidencia = padreDioceseResidencia;
    }

    public byte[] getPadreEstudosFeitos() {
        return this.padreEstudosFeitos;
    }

    public void setPadreEstudosFeitos(byte[] padreEstudosFeitos) {
        this.padreEstudosFeitos = padreEstudosFeitos;
    }

    public Character getCatJaFoi() {
        return this.catJaFoi;
    }

    public void setCatJaFoi(Character catJaFoi) {
        this.catJaFoi = catJaFoi;
    }

    public String getCatJaFoiOnde() {
        return this.catJaFoiOnde;
    }

    public void setCatJaFoiOnde(String catJaFoiOnde) {
        this.catJaFoiOnde = catJaFoiOnde;
    }

    public String getCatJaFoiDtInicio() {
        return this.catJaFoiDtInicio;
    }

    public void setCatJaFoiDtInicio(String catJaFoiDtInicio) {
        this.catJaFoiDtInicio = catJaFoiDtInicio;
    }

    public String getCatJaFoiDtFinal() {
        return this.catJaFoiDtFinal;
    }

    public void setCatJaFoiDtFinal(String catJaFoiDtFinal) {
        this.catJaFoiDtFinal = catJaFoiDtFinal;
    }

    public String getCatAtualDtInicio() {
        return this.catAtualDtInicio;
    }

    public void setCatAtualDtInicio(String catAtualDtInicio) {
        this.catAtualDtInicio = catAtualDtInicio;
    }

    public String getCatAtualDtFinal() {
        return this.catAtualDtFinal;
    }

    public void setCatAtualDtFinal(String catAtualDtFinal) {
        this.catAtualDtFinal = catAtualDtFinal;
    }

    public Integer getCatAtualNMatriculas() {
        return this.catAtualNMatriculas;
    }

    public void setCatAtualNMatriculas(Integer catAtualNMatriculas) {
        this.catAtualNMatriculas = catAtualNMatriculas;
    }

    public Integer getCatAtualNFormandos() {
        return this.catAtualNFormandos;
    }

    public void setCatAtualNFormandos(Integer catAtualNFormandos) {
        this.catAtualNFormandos = catAtualNFormandos;
    }

    public Character getCatAtualUsaAgenda() {
        return this.catAtualUsaAgenda;
    }

    public void setCatAtualUsaAgenda(Character catAtualUsaAgenda) {
        this.catAtualUsaAgenda = catAtualUsaAgenda;
    }

    public String getDtCasamento() {
        return this.dtCasamento;
    }

    public void setDtCasamento(String dtCasamento) {
        this.dtCasamento = dtCasamento;
    }

    public Character getTipoSanguineo() {
        return this.tipoSanguineo;
    }

    public void setTipoSanguineo(Character tipoSanguineo) {
        this.tipoSanguineo = tipoSanguineo;
    }

    public Character getTipoSangRh() {
        return this.tipoSangRh;
    }

    public void setTipoSangRh(Character tipoSangRh) {
        this.tipoSangRh = tipoSangRh;
    }

    public String getIeRgDtExpedicao() {
        return this.ieRgDtExpedicao;
    }

    public void setIeRgDtExpedicao(String ieRgDtExpedicao) {
        this.ieRgDtExpedicao = ieRgDtExpedicao;
    }

    public String getTempoContribuicao() {
        return this.tempoContribuicao;
    }

    public void setTempoContribuicao(String tempoContribuicao) {
        this.tempoContribuicao = tempoContribuicao;
    }

    public Character getZona() {
        return this.zona;
    }

    public void setZona(Character zona) {
        this.zona = zona;
    }

    public Character getGrupoReflexao() {
        return this.grupoReflexao;
    }

    public void setGrupoReflexao(Character grupoReflexao) {
        this.grupoReflexao = grupoReflexao;
    }

    public Integer getQuantGrupoReflexao() {
        return this.quantGrupoReflexao;
    }

    public void setQuantGrupoReflexao(Integer quantGrupoReflexao) {
        this.quantGrupoReflexao = quantGrupoReflexao;
    }

    public byte[] getLeigoOutrosObservacao() {
        return this.leigoOutrosObservacao;
    }

    public void setLeigoOutrosObservacao(byte[] leigoOutrosObservacao) {
        this.leigoOutrosObservacao = leigoOutrosObservacao;
    }

    public Integer getNumeroFicha() {
        return this.numeroFicha;
    }

    public void setNumeroFicha(Integer numeroFicha) {
        this.numeroFicha = numeroFicha;
    }

    public Character getParticipaPastoral() {
        return this.participaPastoral;
    }

    public void setParticipaPastoral(Character participaPastoral) {
        this.participaPastoral = participaPastoral;
    }

    public Character getGostariaPastoral() {
        return this.gostariaPastoral;
    }

    public void setGostariaPastoral(Character gostariaPastoral) {
        this.gostariaPastoral = gostariaPastoral;
    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getDtBatizado() {
        return this.dtBatizado;
    }

    public void setDtBatizado(String dtBatizado) {
        this.dtBatizado = dtBatizado;
    }

    public String getDtEucaristia() {
        return this.dtEucaristia;
    }

    public void setDtEucaristia(String dtEucaristia) {
        this.dtEucaristia = dtEucaristia;
    }

    public String getParoqBatizado() {
        return this.paroqBatizado;
    }

    public void setParoqBatizado(String paroqBatizado) {
        this.paroqBatizado = paroqBatizado;
    }

    public String getParoqEucaristia() {
        return this.paroqEucaristia;
    }

    public void setParoqEucaristia(String paroqEucaristia) {
        this.paroqEucaristia = paroqEucaristia;
    }

    public String getEmailGeral() {
        return this.emailGeral;
    }

    public void setEmailGeral(String emailGeral) {
        this.emailGeral = emailGeral;
    }

    public String getEmailFinan() {
        return this.emailFinan;
    }

    public void setEmailFinan(String emailFinan) {
        this.emailFinan = emailFinan;
    }

    public String getEmailContabil() {
        return this.emailContabil;
    }

    public void setEmailContabil(String emailContabil) {
        this.emailContabil = emailContabil;
    }

    public String getEmailCompras() {
        return this.emailCompras;
    }

    public void setEmailCompras(String emailCompras) {
        this.emailCompras = emailCompras;
    }

    public String getSite() {
        return this.site;
    }

    public void setSite(String site) {
        this.site = site;
    }

    public Character getCrt() {
        return this.crt;
    }

    public void setCrt(Character crt) {
        this.crt = crt;
    }

    public Character getSuframaOk() {
        return this.suframaOk;
    }

    public void setSuframaOk(Character suframaOk) {
        this.suframaOk = suframaOk;
    }

    public String getDtValidadeSuframa() {
        return this.dtValidadeSuframa;
    }

    public void setDtValidadeSuframa(String dtValidadeSuframa) {
        this.dtValidadeSuframa = dtValidadeSuframa;
    }

}
