/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "CFAENDER")
public class CfaenderCustomEntity {

    @Column(name = "ID_CFAENDER", table = "CFAENDER", nullable = false)
    @Id
    private Integer idCfaender;

    @Column(name = "ID_CFAESTAD", table = "CFAENDER")
    @Basic
    private Integer idCfaestad;

    @Column(name = "ID_CFACIDAD", table = "CFAENDER")
    @Basic
    private Integer idCfacidad;

    @Column(name = "ID_SMAEMPRE", table = "CFAENDER")
    @Basic
    private Integer idSmaempre;

    @Column(name = "ID_CFACLIFO", table = "CFAENDER")
    @Basic
    private Integer idCfaclifo;

    @Column(name = "GUID", table = "CFAENDER", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "CFAENDER", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "CFAENDER")
    @Basic
    private String dtCad;

    @Column(name = "DT_ALT", table = "CFAENDER")
    @Basic
    private String dtAlt;

    @Column(name = "CT_INTEG", table = "CFAENDER")
    @Basic
    private Integer ctInteg;

    @Column(name = "TIPO", table = "CFAENDER", nullable = false)
    @Basic(optional = false)
    private Character tipo;

    @Column(name = "NUMERO", table = "CFAENDER", length = 6)
    @Basic
    private String numero;

    @Column(name = "COMPLEMENTO", table = "CFAENDER")
    @Basic
    private String complemento;

    @Column(name = "EMAIL", table = "CFAENDER", length = 128)
    @Basic
    private String email;

    @Column(name = "LETRA_CX_POSTAL", table = "CFAENDER")
    @Basic
    private Character letraCxPostal;

    @Column(name = "CAIXA_POSTAL", table = "CFAENDER")
    @Basic
    private Integer caixaPostal;

    @Column(name = "LOGRADOURO", table = "CFAENDER", length = 60)
    @Basic
    private String logradouro;
    
    @Column(name = "BAIRRO", table = "CFAENDER", length = 60)
    @Basic
    private String bairro;

    @Column(name = "CEP", table = "CFAENDER", length = 9)
    @Basic
    private String cep;

    public Integer getIdCfaender() {
        return this.idCfaender;
    }

    public void setIdCfaender(Integer idCfaender) {
        this.idCfaender = idCfaender;
    }

    public Integer getIdCfaestad() {
        return this.idCfaestad;
    }

    public void setIdCfaestad(Integer idCfaestad) {
        this.idCfaestad = idCfaestad;
    }

    public Integer getIdCfacidad() {
        return this.idCfacidad;
    }

    public void setIdCfacidad(Integer idCfacidad) {
        this.idCfacidad = idCfacidad;
    }

    public Integer getIdSmaempre() {
        return this.idSmaempre;
    }

    public void setIdSmaempre(Integer idSmaempre) {
        this.idSmaempre = idSmaempre;
    }

    public Integer getIdCfaclifo() {
        return this.idCfaclifo;
    }

    public void setIdCfaclifo(Integer idCfaclifo) {
        this.idCfaclifo = idCfaclifo;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public String getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(String dtCad) {
        this.dtCad = dtCad;
    }

    public String getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(String dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public Character getTipo() {
        return this.tipo;
    }

    public void setTipo(Character tipo) {
        this.tipo = tipo;
    }

    public String getNumero() {
        return this.numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    public String getComplemento() {
        return this.complemento;
    }

    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Character getLetraCxPostal() {
        return this.letraCxPostal;
    }

    public void setLetraCxPostal(Character letraCxPostal) {
        this.letraCxPostal = letraCxPostal;
    }

    public Integer getCaixaPostal() {
        return this.caixaPostal;
    }

    public void setCaixaPostal(Integer caixaPostal) {
        this.caixaPostal = caixaPostal;
    }

    public String getLogradouro() {
        return this.logradouro;
    }

    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }

    public String getBairro() {
        return bairro;
    }

    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    
    public String getCep() {
        return this.cep;
    }

    public void setCep(String cep) {
        this.cep = cep;
    }

}
