/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;


import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "CFAMOTNV")
public class CfamotnvEntity {

    @Column(name = "ID_CFAMOTNV", table = "CFAMOTNV", nullable = false)
    @Id
    private Integer idCfamotnv;

    @Column(name = "ID_CFACLIFO", table = "CFAMOTNV", nullable = false)
    @Basic(optional = false)
    private int idCfaclifo;

    @Column(name = "ID_CFAMOTIV", table = "CFAMOTNV", nullable = false)
    @Basic(optional = false)
    private int idCfamotiv;

    @Column(name = "GUID", table = "CFAMOTNV", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "CFAMOTNV", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "CFAMOTNV")
    @Basic
    private String dtCad;

    @Column(name = "DT_ALT", table = "CFAMOTNV")
    @Basic
    private String dtAlt;

    @Column(name = "CT_INTEG", table = "CFAMOTNV")
    @Basic
    private Integer ctInteg;

    @Column(name = "DT_VISITA", table = "CFAMOTNV", nullable = false)
    @Basic(optional = false)
    private String dtVisita;

    public Integer getIdCfamotnv() {
        return this.idCfamotnv;
    }

    public void setIdCfamotnv(Integer idCfamotnv) {
        this.idCfamotnv = idCfamotnv;
    }

    public int getIdCfaclifo() {
        return this.idCfaclifo;
    }

    public void setIdCfaclifo(int idCfaclifo) {
        this.idCfaclifo = idCfaclifo;
    }

    public int getIdCfamotiv() {
        return this.idCfamotiv;
    }

    public void setIdCfamotiv(int idCfamotiv) {
        this.idCfamotiv = idCfamotiv;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public String getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(String dtCad) {
        this.dtCad = dtCad;
    }

    public String getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(String dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public String getDtVisita() {
        return this.dtVisita;
    }

    public void setDtVisita(String dtVisita) {
        this.dtVisita = dtVisita;
    }

}
