/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;


import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "CFAPARTI", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"CODIGO"})})
public class CfapartiEntity {

    @Column(name = "ID_CFAPARTI", table = "CFAPARTI", nullable = false)
    @Id
    private Integer idCfaparti;

    @Column(name = "GUID", table = "CFAPARTI", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "CFAPARTI", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "CFAPARTI")
    @Basic
    private String dtCad;

    @Column(name = "DT_ALT", table = "CFAPARTI")
    @Basic
    private String dtAlt;

    @Column(name = "CT_INTEG", table = "CFAPARTI")
    @Basic
    private Integer ctInteg;

    @Column(name = "CODIGO", table = "CFAPARTI", nullable = false)
    @Basic(optional = false)
    private int codigo;

    @Column(name = "DESCRICAO", table = "CFAPARTI", nullable = false, length = 60)
    @Basic(optional = false)
    private String descricao;

    @Column(name = "SIGLA", table = "CFAPARTI", nullable = false, length = 20)
    @Basic(optional = false)
    private String sigla;

    public Integer getIdCfaparti() {
        return this.idCfaparti;
    }

    public void setIdCfaparti(Integer idCfaparti) {
        this.idCfaparti = idCfaparti;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public String getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(String dtCad) {
        this.dtCad = dtCad;
    }

    public String getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(String dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public String getSigla() {
        return this.sigla;
    }

    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

}
