/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "CFAREFCL")
public class CfarefclEntity {

    @Column(name = "ID_CFAREFCL", table = "CFAREFCL", nullable = false)
    @Id
    private Integer idCfarefcl;

    @Column(name = "ID_CFACLIFO", table = "CFAREFCL", nullable = false)
    @Basic(optional = false)
    private int idCfaclifo;

    @Column(name = "ID_CFAPROFI", table = "CFAREFCL")
    @Basic
    private Integer idCfaprofi;

    @Column(name = "ID_CFAREFER", table = "CFAREFCL")
    @Basic
    private Integer idCfarefer;

    @Column(name = "ID_CFATPDEP", table = "CFAREFCL")
    @Basic
    private Integer idCfatpdep;

    @Column(name = "ID_CFAPROFI_CARGO", table = "CFAREFCL")
    @Basic
    private Integer idCfaprofiCargo;

    @Column(name = "GUID", table = "CFAREFCL", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "CFAREFCL", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "CFAREFCL")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtCad;

    @Column(name = "DT_ALT", table = "CFAREFCL")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtAlt;

    @Column(name = "CT_INTEG", table = "CFAREFCL")
    @Basic
    private Integer ctInteg;

    @Column(name = "NOME", table = "CFAREFCL", length = 60)
    @Basic
    private String nome;

    @Column(name = "TIPO", table = "CFAREFCL")
    @Basic
    private Character tipo;

    @Column(name = "SEXO", table = "CFAREFCL")
    @Basic
    private Character sexo;

    @Column(name = "EMPRESA_TRAB", table = "CFAREFCL", length = 60)
    @Basic
    private String empresaTrab;

    @Column(name = "COMPLEMENTO", table = "CFAREFCL")
    @Lob
    @Basic
    private byte[] complemento;

    public Integer getIdCfarefcl() {
        return this.idCfarefcl;
    }

    public void setIdCfarefcl(Integer idCfarefcl) {
        this.idCfarefcl = idCfarefcl;
    }

    public int getIdCfaclifo() {
        return this.idCfaclifo;
    }

    public void setIdCfaclifo(int idCfaclifo) {
        this.idCfaclifo = idCfaclifo;
    }

    public Integer getIdCfaprofi() {
        return this.idCfaprofi;
    }

    public void setIdCfaprofi(Integer idCfaprofi) {
        this.idCfaprofi = idCfaprofi;
    }

    public Integer getIdCfarefer() {
        return this.idCfarefer;
    }

    public void setIdCfarefer(Integer idCfarefer) {
        this.idCfarefer = idCfarefer;
    }

    public Integer getIdCfatpdep() {
        return this.idCfatpdep;
    }

    public void setIdCfatpdep(Integer idCfatpdep) {
        this.idCfatpdep = idCfatpdep;
    }

    public Integer getIdCfaprofiCargo() {
        return this.idCfaprofiCargo;
    }

    public void setIdCfaprofiCargo(Integer idCfaprofiCargo) {
        this.idCfaprofiCargo = idCfaprofiCargo;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public Date getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(Date dtCad) {
        this.dtCad = dtCad;
    }

    public Date getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(Date dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Character getTipo() {
        return this.tipo;
    }

    public void setTipo(Character tipo) {
        this.tipo = tipo;
    }

    public Character getSexo() {
        return this.sexo;
    }

    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }

    public String getEmpresaTrab() {
        return this.empresaTrab;
    }

    public void setEmpresaTrab(String empresaTrab) {
        this.empresaTrab = empresaTrab;
    }

    public byte[] getComplemento() {
        return this.complemento;
    }

    public void setComplemento(byte[] complemento) {
        this.complemento = complemento;
    }

}
