/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "CFATRBPR", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"ID_CFAESTAD", "SEQUENCIA"})})
public class CfatrbprEntity {

    @Column(name = "ID_CFATRBPR", table = "CFATRBPR", nullable = false)
    @Id
    private Integer idCfatrbpr;

    @Column(name = "ID_CFAESTAD", table = "CFATRBPR", nullable = false)
    @Basic(optional = false)
    private int idCfaestad;

    @Column(name = "ID_AEAAGPPR", table = "CFATRBPR")
    @Basic
    private Integer idAeaagppr;

    @Column(name = "ID_AEAMARCA", table = "CFATRBPR")
    @Basic
    private Integer idAeamarca;

    @Column(name = "ID_AEAFAMIL", table = "CFATRBPR")
    @Basic
    private Integer idAeafamil;

    @Column(name = "ID_AEACLASE", table = "CFATRBPR")
    @Basic
    private Integer idAeaclase;

    @Column(name = "ID_AEAGRUPO", table = "CFATRBPR")
    @Basic
    private Integer idAeagrupo;

    @Column(name = "ID_AEASGRUP", table = "CFATRBPR")
    @Basic
    private Integer idAeasgrup;

    @Column(name = "ID_AEAPRODU", table = "CFATRBPR")
    @Basic
    private Integer idAeaprodu;

    @Column(name = "ID_AEACODOM", table = "CFATRBPR")
    @Basic
    private Integer idAeacodom;

    @Column(name = "ID_AEATBPER", table = "CFATRBPR")
    @Basic
    private Integer idAeatbper;

    @Column(name = "ID_AEACODST", table = "CFATRBPR")
    @Basic
    private Integer idAeacodst;

    @Column(name = "GUID", table = "CFATRBPR", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "CFATRBPR", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "CFATRBPR")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtCad;

    @Column(name = "DT_ALT", table = "CFATRBPR")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtAlt;

    @Column(name = "CT_INTEG", table = "CFATRBPR")
    @Basic
    private Integer ctInteg;

    @Column(name = "SEQUENCIA", table = "CFATRBPR", nullable = false)
    @Basic(optional = false)
    private int sequencia;

    @Column(name = "TIPO_IPI", table = "CFATRBPR")
    @Basic
    private Character tipoIpi;

    @Column(name = "IPI", table = "CFATRBPR", nullable = false)
    @Basic(optional = false)
    private double ipi;

    @Column(name = "ICMS", table = "CFATRBPR", nullable = false)
    @Basic(optional = false)
    private double icms;

    @Column(name = "REDUCAO_ICMS", table = "CFATRBPR", nullable = false)
    @Basic(optional = false)
    private double reducaoIcms;

    @Column(name = "MVA", table = "CFATRBPR", nullable = false)
    @Basic(optional = false)
    private double mva;

    @Column(name = "FCP", table = "CFATRBPR", nullable = false)
    @Basic(optional = false)
    private double fcp;

    @Column(name = "EXCLUI_INCLUI", table = "CFATRBPR")
    @Basic
    private Character excluiInclui;

    public Integer getIdCfatrbpr() {
        return this.idCfatrbpr;
    }

    public void setIdCfatrbpr(Integer idCfatrbpr) {
        this.idCfatrbpr = idCfatrbpr;
    }

    public int getIdCfaestad() {
        return this.idCfaestad;
    }

    public void setIdCfaestad(int idCfaestad) {
        this.idCfaestad = idCfaestad;
    }

    public Integer getIdAeaagppr() {
        return this.idAeaagppr;
    }

    public void setIdAeaagppr(Integer idAeaagppr) {
        this.idAeaagppr = idAeaagppr;
    }

    public Integer getIdAeamarca() {
        return this.idAeamarca;
    }

    public void setIdAeamarca(Integer idAeamarca) {
        this.idAeamarca = idAeamarca;
    }

    public Integer getIdAeafamil() {
        return this.idAeafamil;
    }

    public void setIdAeafamil(Integer idAeafamil) {
        this.idAeafamil = idAeafamil;
    }

    public Integer getIdAeaclase() {
        return this.idAeaclase;
    }

    public void setIdAeaclase(Integer idAeaclase) {
        this.idAeaclase = idAeaclase;
    }

    public Integer getIdAeagrupo() {
        return this.idAeagrupo;
    }

    public void setIdAeagrupo(Integer idAeagrupo) {
        this.idAeagrupo = idAeagrupo;
    }

    public Integer getIdAeasgrup() {
        return this.idAeasgrup;
    }

    public void setIdAeasgrup(Integer idAeasgrup) {
        this.idAeasgrup = idAeasgrup;
    }

    public Integer getIdAeaprodu() {
        return this.idAeaprodu;
    }

    public void setIdAeaprodu(Integer idAeaprodu) {
        this.idAeaprodu = idAeaprodu;
    }

    public Integer getIdAeacodom() {
        return this.idAeacodom;
    }

    public void setIdAeacodom(Integer idAeacodom) {
        this.idAeacodom = idAeacodom;
    }

    public Integer getIdAeatbper() {
        return this.idAeatbper;
    }

    public void setIdAeatbper(Integer idAeatbper) {
        this.idAeatbper = idAeatbper;
    }

    public Integer getIdAeacodst() {
        return this.idAeacodst;
    }

    public void setIdAeacodst(Integer idAeacodst) {
        this.idAeacodst = idAeacodst;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public Date getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(Date dtCad) {
        this.dtCad = dtCad;
    }

    public Date getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(Date dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public int getSequencia() {
        return this.sequencia;
    }

    public void setSequencia(int sequencia) {
        this.sequencia = sequencia;
    }

    public Character getTipoIpi() {
        return this.tipoIpi;
    }

    public void setTipoIpi(Character tipoIpi) {
        this.tipoIpi = tipoIpi;
    }

    public double getIpi() {
        return this.ipi;
    }

    public void setIpi(double ipi) {
        this.ipi = ipi;
    }

    public double getIcms() {
        return this.icms;
    }

    public void setIcms(double icms) {
        this.icms = icms;
    }

    public double getReducaoIcms() {
        return this.reducaoIcms;
    }

    public void setReducaoIcms(double reducaoIcms) {
        this.reducaoIcms = reducaoIcms;
    }

    public double getMva() {
        return this.mva;
    }

    public void setMva(double mva) {
        this.mva = mva;
    }

    public double getFcp() {
        return this.fcp;
    }

    public void setFcp(double fcp) {
        this.fcp = fcp;
    }

    public Character getExcluiInclui() {
        return this.excluiInclui;
    }

    public void setExcluiInclui(Character excluiInclui) {
        this.excluiInclui = excluiInclui;
    }

}
