/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "CFATPCLI", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"CODIGO"})})
public class CfatpcliEntity {

    @Column(name = "ID_CFATPCLI", table = "CFATPCLI", nullable = false)
    @Id
    private Integer idCfatpcli;

    @Column(name = "GUID", table = "CFATPCLI", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "CFATPCLI", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "CFATPCLI")
    @Basic
    private String dtCad;

    @Column(name = "DT_ALT", table = "CFATPCLI")
    @Basic
    private String dtAlt;

    @Column(name = "CT_INTEG", table = "CFATPCLI")
    @Basic
    private Integer ctInteg;

    @Column(name = "CODIGO", table = "CFATPCLI", nullable = false)
    @Basic(optional = false)
    private int codigo;

    @Column(name = "DESCRICAO", table = "CFATPCLI", nullable = false, length = 40)
    @Basic(optional = false)
    private String descricao;

    @Column(name = "DESC_ATAC_VISTA", table = "CFATPCLI", nullable = false)
    @Basic(optional = false)
    private double descAtacVista;

    @Column(name = "DESC_ATAC_PRAZO", table = "CFATPCLI", nullable = false)
    @Basic(optional = false)
    private double descAtacPrazo;

    @Column(name = "DESC_VARE_VISTA", table = "CFATPCLI", nullable = false)
    @Basic(optional = false)
    private double descVareVista;

    @Column(name = "DESC_VARE_PRAZO", table = "CFATPCLI", nullable = false)
    @Basic(optional = false)
    private double descVarePrazo;

    @Column(name = "DESC_SERV_VISTA", table = "CFATPCLI", nullable = false)
    @Basic(optional = false)
    private double descServVista;

    @Column(name = "DESC_SERV_PRAZO", table = "CFATPCLI", nullable = false)
    @Basic(optional = false)
    private double descServPrazo;

    @Column(name = "DESC_PROMOCAO", table = "CFATPCLI")
    @Basic
    private Character descPromocao;

    @Column(name = "VENDE_ATAC_VAREJO", table = "CFATPCLI")
    @Basic
    private Character vendeAtacVarejo;

    public Integer getIdCfatpcli() {
        return this.idCfatpcli;
    }

    public void setIdCfatpcli(Integer idCfatpcli) {
        this.idCfatpcli = idCfatpcli;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public String getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(String dtCad) {
        this.dtCad = dtCad;
    }

    public String getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(String dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public double getDescAtacVista() {
        return this.descAtacVista;
    }

    public void setDescAtacVista(double descAtacVista) {
        this.descAtacVista = descAtacVista;
    }

    public double getDescAtacPrazo() {
        return this.descAtacPrazo;
    }

    public void setDescAtacPrazo(double descAtacPrazo) {
        this.descAtacPrazo = descAtacPrazo;
    }

    public double getDescVareVista() {
        return this.descVareVista;
    }

    public void setDescVareVista(double descVareVista) {
        this.descVareVista = descVareVista;
    }

    public double getDescVarePrazo() {
        return this.descVarePrazo;
    }

    public void setDescVarePrazo(double descVarePrazo) {
        this.descVarePrazo = descVarePrazo;
    }

    public double getDescServVista() {
        return this.descServVista;
    }

    public void setDescServVista(double descServVista) {
        this.descServVista = descServVista;
    }

    public double getDescServPrazo() {
        return this.descServPrazo;
    }

    public void setDescServPrazo(double descServPrazo) {
        this.descServPrazo = descServPrazo;
    }

    public Character getDescPromocao() {
        return this.descPromocao;
    }

    public void setDescPromocao(Character descPromocao) {
        this.descPromocao = descPromocao;
    }

    public Character getVendeAtacVarejo() {
        return this.vendeAtacVarejo;
    }

    public void setVendeAtacVarejo(Character vendeAtacVarejo) {
        this.vendeAtacVarejo = vendeAtacVarejo;
    }

}
