/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;


import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "CPACERTI")
public class CpacertiEntity {

    @Column(name = "ID_CPACERTI", table = "CPACERTI", nullable = false)
    @Id
    private Integer idCpacerti;

    @Column(name = "ID_CPAPESOA", table = "CPACERTI")
    @Basic
    private Integer idCpapesoa;

    @Column(name = "ID_CFAESTAD", table = "CPACERTI")
    @Basic
    private String idCfaestad;

    @Column(name = "US_CAD", table = "CPACERTI", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "CPACERTI")
    @Basic
    private String dtCad;

    @Column(name = "DT_ALT", table = "CPACERTI")
    @Basic
    private String dtAlt;

    @Column(name = "CT_INTEG", table = "CPACERTI")
    @Basic
    private Integer ctInteg;

    @Column(name = "GUID", table = "CPACERTI", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "CODIGO", table = "CPACERTI")
    @Basic
    private Integer codigo;

    @Column(name = "TIPO", table = "CPACERTI")
    @Basic
    private Character tipo;

    @Column(name = "DT_CERTIDAO", table = "CPACERTI")
    @Basic
        private String dtCertidao;

    @Column(name = "CPF_CGC", table = "CPACERTI", length = 18)
    @Basic
    private String cpfCgc;

    @Column(name = "TIPO_DOC", table = "CPACERTI")
    @Basic
    private Character tipoDoc;

    @Column(name = "DOCUMENTO", table = "CPACERTI", length = 18)
    @Basic
    private String documento;

    @Column(name = "NOME", table = "CPACERTI", length = 60)
    @Basic
    private String nome;

    @Column(name = "NACIONAL", table = "CPACERTI", length = 40)
    @Basic
    private String nacional;

    @Column(name = "ESTADO_CIVIL", table = "CPACERTI")
    @Basic
    private Character estadoCivil;

    @Column(name = "PROFISSAO", table = "CPACERTI", length = 40)
    @Basic
    private String profissao;

    @Column(name = "ENDERECO", table = "CPACERTI", length = 128)
    @Basic
    private String endereco;

    @Column(name = "NUMERO", table = "CPACERTI", length = 6)
    @Basic
    private String numero;

    @Column(name = "BAIRRO", table = "CPACERTI", length = 40)
    @Basic
    private String bairro;

    @Column(name = "CIDADE", table = "CPACERTI", length = 40)
    @Basic
    private String cidade;

    @Column(name = "CEP", table = "CPACERTI", length = 9)
    @Basic
    private String cep;

    @Column(name = "VL_EMOL", table = "CPACERTI", nullable = false)
    @Basic(optional = false)
    private double vlEmol;

    @Column(name = "VL_TRIB", table = "CPACERTI", nullable = false)
    @Basic(optional = false)
    private double vlTrib;

    @Column(name = "VL_FUJU", table = "CPACERTI", nullable = false)
    @Basic(optional = false)
    private double vlFuju;

    @Column(name = "VL_SELO", table = "CPACERTI", nullable = false)
    @Basic(optional = false)
    private double vlSelo;

    @Column(name = "FC_CUSTAS", table = "CPACERTI", precision = 15)
    @Basic
    private Double fcCustas;

    public Integer getIdCpacerti() {
        return this.idCpacerti;
    }

    public void setIdCpacerti(Integer idCpacerti) {
        this.idCpacerti = idCpacerti;
    }

    public Integer getIdCpapesoa() {
        return this.idCpapesoa;
    }

    public void setIdCpapesoa(Integer idCpapesoa) {
        this.idCpapesoa = idCpapesoa;
    }

    public String getIdCfaestad() {
        return this.idCfaestad;
    }

    public void setIdCfaestad(String idCfaestad) {
        this.idCfaestad = idCfaestad;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public String getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(String dtCad) {
        this.dtCad = dtCad;
    }

    public String getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(String dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public Character getTipo() {
        return this.tipo;
    }

    public void setTipo(Character tipo) {
        this.tipo = tipo;
    }

    public String getDtCertidao() {
        return this.dtCertidao;
    }

    public void setDtCertidao(String dtCertidao) {
        this.dtCertidao = dtCertidao;
    }

    public String getCpfCgc() {
        return this.cpfCgc;
    }

    public void setCpfCgc(String cpfCgc) {
        this.cpfCgc = cpfCgc;
    }

    public Character getTipoDoc() {
        return this.tipoDoc;
    }

    public void setTipoDoc(Character tipoDoc) {
        this.tipoDoc = tipoDoc;
    }

    public String getDocumento() {
        return this.documento;
    }

    public void setDocumento(String documento) {
        this.documento = documento;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getNacional() {
        return this.nacional;
    }

    public void setNacional(String nacional) {
        this.nacional = nacional;
    }

    public Character getEstadoCivil() {
        return this.estadoCivil;
    }

    public void setEstadoCivil(Character estadoCivil) {
        this.estadoCivil = estadoCivil;
    }

    public String getProfissao() {
        return this.profissao;
    }

    public void setProfissao(String profissao) {
        this.profissao = profissao;
    }

    public String getEndereco() {
        return this.endereco;
    }

    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    public String getNumero() {
        return this.numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    public String getBairro() {
        return this.bairro;
    }

    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    public String getCidade() {
        return this.cidade;
    }

    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    public String getCep() {
        return this.cep;
    }

    public void setCep(String cep) {
        this.cep = cep;
    }

    public double getVlEmol() {
        return this.vlEmol;
    }

    public void setVlEmol(double vlEmol) {
        this.vlEmol = vlEmol;
    }

    public double getVlTrib() {
        return this.vlTrib;
    }

    public void setVlTrib(double vlTrib) {
        this.vlTrib = vlTrib;
    }

    public double getVlFuju() {
        return this.vlFuju;
    }

    public void setVlFuju(double vlFuju) {
        this.vlFuju = vlFuju;
    }

    public double getVlSelo() {
        return this.vlSelo;
    }

    public void setVlSelo(double vlSelo) {
        this.vlSelo = vlSelo;
    }

    public Double getFcCustas() {
        return this.fcCustas;
    }

    public void setFcCustas(Double fcCustas) {
        this.fcCustas = fcCustas;
    }

}
