/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "CTAPCCTC")
public class CtapcctcEntity {

    @Column(name = "ID_CTAPCCTC", table = "CTAPCCTC", nullable = false)
    @Id
    private Integer idCtapcctc;

    @Column(name = "ID_CTAPLCTA", table = "CTAPCCTC")
    @Basic
    private Integer idCtaplcta;

    @Column(name = "ID_CTACTCUS", table = "CTAPCCTC")
    @Basic
    private Integer idCtactcus;

    @Column(name = "GUID", table = "CTAPCCTC", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "CTAPCCTC", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "CTAPCCTC")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtCad;

    @Column(name = "DT_ALT", table = "CTAPCCTC")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtAlt;

    @Column(name = "CT_INTEG", table = "CTAPCCTC")
    @Basic
    private Integer ctInteg;

    @Column(name = "DATA", table = "CTAPCCTC")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date data;

    @Column(name = "SALDO_ANT_CRE", table = "CTAPCCTC", nullable = false)
    @Basic(optional = false)
    private double saldoAntCre;

    @Column(name = "SALDO_ANT_DEB", table = "CTAPCCTC", nullable = false)
    @Basic(optional = false)
    private double saldoAntDeb;

    @Column(name = "VALOR_CRE", table = "CTAPCCTC", nullable = false)
    @Basic(optional = false)
    private double valorCre;

    @Column(name = "VALOR_DEB", table = "CTAPCCTC", nullable = false)
    @Basic(optional = false)
    private double valorDeb;

    public Integer getIdCtapcctc() {
        return this.idCtapcctc;
    }

    public void setIdCtapcctc(Integer idCtapcctc) {
        this.idCtapcctc = idCtapcctc;
    }

    public Integer getIdCtaplcta() {
        return this.idCtaplcta;
    }

    public void setIdCtaplcta(Integer idCtaplcta) {
        this.idCtaplcta = idCtaplcta;
    }

    public Integer getIdCtactcus() {
        return this.idCtactcus;
    }

    public void setIdCtactcus(Integer idCtactcus) {
        this.idCtactcus = idCtactcus;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public Date getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(Date dtCad) {
        this.dtCad = dtCad;
    }

    public Date getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(Date dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public Date getData() {
        return this.data;
    }

    public void setData(Date data) {
        this.data = data;
    }

    public double getSaldoAntCre() {
        return this.saldoAntCre;
    }

    public void setSaldoAntCre(double saldoAntCre) {
        this.saldoAntCre = saldoAntCre;
    }

    public double getSaldoAntDeb() {
        return this.saldoAntDeb;
    }

    public void setSaldoAntDeb(double saldoAntDeb) {
        this.saldoAntDeb = saldoAntDeb;
    }

    public double getValorCre() {
        return this.valorCre;
    }

    public void setValorCre(double valorCre) {
        this.valorCre = valorCre;
    }

    public double getValorDeb() {
        return this.valorDeb;
    }

    public void setValorDeb(double valorDeb) {
        this.valorDeb = valorDeb;
    }

}
