/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "RPAPARCE", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"SEQUENCIAL"})})
public class RpaparceEntity {

    @Column(name = "ID_RPAPARCE", table = "RPAPARCE", nullable = false)
    @Id
    private Integer idRpaparce;

    @Column(name = "ID_SMAEMPRE", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private int idSmaempre;

    @Column(name = "ID_RPAFATUR", table = "RPAPARCE")
    @Basic
    private Integer idRpafatur;

    @Column(name = "ID_CBAITACE", table = "RPAPARCE")
    @Basic
    private Integer idCbaitace;

    @Column(name = "ID_CFACLIFO", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private int idCfaclifo;

    @Column(name = "ID_CFATPDOC", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private int idCfatpdoc;

    @Column(name = "ID_CBAPLCTA_CTA_TRANS", table = "RPAPARCE")
    @Basic
    private Integer idCbaplctaCtaTrans;

    @Column(name = "ID_CBAPLCTA_DP", table = "RPAPARCE")
    @Basic
    private Integer idCbaplctaDp;

    @Column(name = "ID_CBAPLCTA", table = "RPAPARCE")
    @Basic
    private Integer idCbaplcta;

    @Column(name = "ID_CFATPCOB", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private int idCfatpcob;

    @Column(name = "ID_CFAMOEDA", table = "RPAPARCE")
    @Basic
    private Integer idCfamoeda;

    @Column(name = "ID_CFAPORTA", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private int idCfaporta;

    @Column(name = "ID_CFAESTAD_ORGAO", table = "RPAPARCE")
    @Basic
    private Integer idCfaestadOrgao;

    @Column(name = "ID_CBACAIXA_AUTENTIC", table = "RPAPARCE")
    @Basic
    private Integer idCbacaixaAutentic;

    @Column(name = "ID_CFACLIFO_AUTENTIC", table = "RPAPARCE")
    @Basic
    private Integer idCfaclifoAutentic;

    @Column(name = "ID_CFACCRED", table = "RPAPARCE")
    @Basic
    private Integer idCfaccred;

    @Column(name = "GUID", table = "RPAPARCE", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "RPAPARCE", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "RPAPARCE")
    @Basic
    private String dtCad;

    @Column(name = "DT_ALT", table = "RPAPARCE")
    @Basic
    private String dtAlt;

    @Column(name = "CT_INTEG", table = "RPAPARCE")
    @Basic
    private Integer ctInteg;

    @Column(name = "TIPO", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private Character tipo;

    @Column(name = "DT_IMPORTACAO", table = "RPAPARCE")
    @Basic
    private String dtImportacao;

    @Column(name = "DT_EMISSAO", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private String dtEmissao;

    @Column(name = "DT_VENCIMENTO", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private String dtVencimento;

    @Column(name = "DT_PAGAMENTO", table = "RPAPARCE")
    @Basic
    private String dtPagamento;

    @Column(name = "DT_BAIXA", table = "RPAPARCE")
    @Basic
    private String dtBaixa;

    @Column(name = "DT_TEM_DOCTO_MUDOU", table = "RPAPARCE")
    @Basic
    private String dtTemDoctoMudou;

    @Column(name = "DT_AUTENTIC", table = "RPAPARCE")
    @Basic
    private String dtAutentic;

    @Column(name = "PARCELA", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private int parcela;

    @Column(name = "VL_PARCELA", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private double vlParcela;

    @Column(name = "VL_JUROS_PRORROG", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private double vlJurosProrrog;

    @Column(name = "VL_PAGO", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private double vlPago;

    @Column(name = "VL_DESCONTO", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private double vlDesconto;

    @Column(name = "VL_JUROS", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private double vlJuros;

    @Column(name = "FC_VL_TOTAL_PAGO", table = "RPAPARCE", precision = 15)
    @Basic
    private Double fcVlTotalPago;

    @Column(name = "FC_VL_RESTANTE", table = "RPAPARCE", precision = 15)
    @Basic
    private Double fcVlRestante;

    @Column(name = "FC_VL_RESTANTE_SEM_PRORROG", table = "RPAPARCE", precision = 15)
    @Basic
    private Double fcVlRestanteSemProrrog;

    @Column(name = "VL_JUROS_DIARIO", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private double vlJurosDiario;

    @Column(name = "NUM_EMISSOES", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private int numEmissoes;

    @Column(name = "TAXA_DIARIA", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private double taxaDiaria;

    @Column(name = "CAPITALIZA", table = "RPAPARCE")
    @Basic
    private Character capitaliza;

    @Column(name = "PRORROGADO", table = "RPAPARCE")
    @Basic
    private Character prorrogado;

    @Column(name = "DIAS_PROTESTO", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private int diasProtesto;

    @Column(name = "TEM_DOCTO", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private Character temDocto;

    @Column(name = "PERC_DESCONTO", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private double percDesconto;

    @Column(name = "INDEXADO", table = "RPAPARCE")
    @Basic
    private Character indexado;

    @Column(name = "SEQUENCIAL", table = "RPAPARCE", nullable = false, length = 13)
    @Basic(optional = false)
    private String sequencial;

    @Column(name = "AGENCIA", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private int agencia;

    @Column(name = "DG_AG", table = "RPAPARCE")
    @Basic
    private Character dgAg;

    @Column(name = "CONTA", table = "RPAPARCE")
    @Basic
    private Integer conta;

    @Column(name = "DG_CT", table = "RPAPARCE", length = 2)
    @Basic
    private String dgCt;

    @Column(name = "SERIE", table = "RPAPARCE", length = 6)
    @Basic
    private String serie;

    @Column(name = "NUMERO", table = "RPAPARCE", length = 20)
    @Basic
    private String numero;

    @Column(name = "CONTROLE", table = "RPAPARCE", length = 60)
    @Basic
    private String controle;

    @Column(name = "SEQ_BOLETO", table = "RPAPARCE")
    @Basic
    private Integer seqBoleto;

    @Column(name = "NOME", table = "RPAPARCE", length = 60)
    @Basic
    private String nome;

    @Column(name = "CPF_CGC", table = "RPAPARCE", length = 18)
    @Basic
    private String cpfCgc;

    @Column(name = "IE_RG", table = "RPAPARCE", length = 18)
    @Basic
    private String ieRg;

    @Column(name = "ORGAO_EMISSOR", table = "RPAPARCE", length = 3)
    @Basic
    private String orgaoEmissor;

    @Column(name = "SITUACAO", table = "RPAPARCE", nullable = false)
    @Basic(optional = false)
    private short situacao;

    @Column(name = "OBS", table = "RPAPARCE")
    @Basic
    private String obs;

    @Column(name = "A_S", table = "RPAPARCE")
    @Basic
    private Character analiticoSintetico;

    public Integer getIdRpaparce() {
        return this.idRpaparce;
    }

    public void setIdRpaparce(Integer idRpaparce) {
        this.idRpaparce = idRpaparce;
    }

    public int getIdSmaempre() {
        return this.idSmaempre;
    }

    public void setIdSmaempre(int idSmaempre) {
        this.idSmaempre = idSmaempre;
    }

    public Integer getIdRpafatur() {
        return this.idRpafatur;
    }

    public void setIdRpafatur(Integer idRpafatur) {
        this.idRpafatur = idRpafatur;
    }

    public Integer getIdCbaitace() {
        return this.idCbaitace;
    }

    public void setIdCbaitace(Integer idCbaitace) {
        this.idCbaitace = idCbaitace;
    }

    public int getIdCfaclifo() {
        return this.idCfaclifo;
    }

    public void setIdCfaclifo(int idCfaclifo) {
        this.idCfaclifo = idCfaclifo;
    }

    public int getIdCfatpdoc() {
        return this.idCfatpdoc;
    }

    public void setIdCfatpdoc(int idCfatpdoc) {
        this.idCfatpdoc = idCfatpdoc;
    }

    public Integer getIdCbaplctaCtaTrans() {
        return this.idCbaplctaCtaTrans;
    }

    public void setIdCbaplctaCtaTrans(Integer idCbaplctaCtaTrans) {
        this.idCbaplctaCtaTrans = idCbaplctaCtaTrans;
    }

    public Integer getIdCbaplctaDp() {
        return this.idCbaplctaDp;
    }

    public void setIdCbaplctaDp(Integer idCbaplctaDp) {
        this.idCbaplctaDp = idCbaplctaDp;
    }

    public Integer getIdCbaplcta() {
        return this.idCbaplcta;
    }

    public void setIdCbaplcta(Integer idCbaplcta) {
        this.idCbaplcta = idCbaplcta;
    }

    public int getIdCfatpcob() {
        return this.idCfatpcob;
    }

    public void setIdCfatpcob(int idCfatpcob) {
        this.idCfatpcob = idCfatpcob;
    }

    public Integer getIdCfamoeda() {
        return this.idCfamoeda;
    }

    public void setIdCfamoeda(Integer idCfamoeda) {
        this.idCfamoeda = idCfamoeda;
    }

    public int getIdCfaporta() {
        return this.idCfaporta;
    }

    public void setIdCfaporta(int idCfaporta) {
        this.idCfaporta = idCfaporta;
    }

    public Integer getIdCfaestadOrgao() {
        return this.idCfaestadOrgao;
    }

    public void setIdCfaestadOrgao(Integer idCfaestadOrgao) {
        this.idCfaestadOrgao = idCfaestadOrgao;
    }

    public Integer getIdCbacaixaAutentic() {
        return this.idCbacaixaAutentic;
    }

    public void setIdCbacaixaAutentic(Integer idCbacaixaAutentic) {
        this.idCbacaixaAutentic = idCbacaixaAutentic;
    }

    public Integer getIdCfaclifoAutentic() {
        return this.idCfaclifoAutentic;
    }

    public void setIdCfaclifoAutentic(Integer idCfaclifoAutentic) {
        this.idCfaclifoAutentic = idCfaclifoAutentic;
    }

    public Integer getIdCfaccred() {
        return this.idCfaccred;
    }

    public void setIdCfaccred(Integer idCfaccred) {
        this.idCfaccred = idCfaccred;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public String getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(String dtCad) {
        this.dtCad = dtCad;
    }

    public String getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(String dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public Character getTipo() {
        return this.tipo;
    }

    public void setTipo(Character tipo) {
        this.tipo = tipo;
    }

    public String getDtImportacao() {
        return this.dtImportacao;
    }

    public void setDtImportacao(String dtImportacao) {
        this.dtImportacao = dtImportacao;
    }

    public String getDtEmissao() {
        return this.dtEmissao;
    }

    public void setDtEmissao(String dtEmissao) {
        this.dtEmissao = dtEmissao;
    }

    public String getDtVencimento() {
        return this.dtVencimento;
    }

    public void setDtVencimento(String dtVencimento) {
        this.dtVencimento = dtVencimento;
    }

    public String getDtPagamento() {
        return this.dtPagamento;
    }

    public void setDtPagamento(String dtPagamento) {
        this.dtPagamento = dtPagamento;
    }

    public String getDtBaixa() {
        return this.dtBaixa;
    }

    public void setDtBaixa(String dtBaixa) {
        this.dtBaixa = dtBaixa;
    }

    public String getDtTemDoctoMudou() {
        return this.dtTemDoctoMudou;
    }

    public void setDtTemDoctoMudou(String dtTemDoctoMudou) {
        this.dtTemDoctoMudou = dtTemDoctoMudou;
    }

    public String getDtAutentic() {
        return this.dtAutentic;
    }

    public void setDtAutentic(String dtAutentic) {
        this.dtAutentic = dtAutentic;
    }

    public int getParcela() {
        return this.parcela;
    }

    public void setParcela(int parcela) {
        this.parcela = parcela;
    }

    public double getVlParcela() {
        return this.vlParcela;
    }

    public void setVlParcela(double vlParcela) {
        this.vlParcela = vlParcela;
    }

    public double getVlJurosProrrog() {
        return this.vlJurosProrrog;
    }

    public void setVlJurosProrrog(double vlJurosProrrog) {
        this.vlJurosProrrog = vlJurosProrrog;
    }

    public double getVlPago() {
        return this.vlPago;
    }

    public void setVlPago(double vlPago) {
        this.vlPago = vlPago;
    }

    public double getVlDesconto() {
        return this.vlDesconto;
    }

    public void setVlDesconto(double vlDesconto) {
        this.vlDesconto = vlDesconto;
    }

    public double getVlJuros() {
        return this.vlJuros;
    }

    public void setVlJuros(double vlJuros) {
        this.vlJuros = vlJuros;
    }

    public Double getFcVlTotalPago() {
        return this.fcVlTotalPago;
    }

    public void setFcVlTotalPago(Double fcVlTotalPago) {
        this.fcVlTotalPago = fcVlTotalPago;
    }

    public Double getFcVlRestante() {
        return this.fcVlRestante;
    }

    public void setFcVlRestante(Double fcVlRestante) {
        this.fcVlRestante = fcVlRestante;
    }

    public Double getFcVlRestanteSemProrrog() {
        return this.fcVlRestanteSemProrrog;
    }

    public void setFcVlRestanteSemProrrog(Double fcVlRestanteSemProrrog) {
        this.fcVlRestanteSemProrrog = fcVlRestanteSemProrrog;
    }

    public double getVlJurosDiario() {
        return this.vlJurosDiario;
    }

    public void setVlJurosDiario(double vlJurosDiario) {
        this.vlJurosDiario = vlJurosDiario;
    }

    public int getNumEmissoes() {
        return this.numEmissoes;
    }

    public void setNumEmissoes(int numEmissoes) {
        this.numEmissoes = numEmissoes;
    }

    public double getTaxaDiaria() {
        return this.taxaDiaria;
    }

    public void setTaxaDiaria(double taxaDiaria) {
        this.taxaDiaria = taxaDiaria;
    }

    public Character getCapitaliza() {
        return this.capitaliza;
    }

    public void setCapitaliza(Character capitaliza) {
        this.capitaliza = capitaliza;
    }

    public Character getProrrogado() {
        return this.prorrogado;
    }

    public void setProrrogado(Character prorrogado) {
        this.prorrogado = prorrogado;
    }

    public int getDiasProtesto() {
        return this.diasProtesto;
    }

    public void setDiasProtesto(int diasProtesto) {
        this.diasProtesto = diasProtesto;
    }

    public Character getTemDocto() {
        return this.temDocto;
    }

    public void setTemDocto(Character temDocto) {
        this.temDocto = temDocto;
    }

    public double getPercDesconto() {
        return this.percDesconto;
    }

    public void setPercDesconto(double percDesconto) {
        this.percDesconto = percDesconto;
    }

    public Character getIndexado() {
        return this.indexado;
    }

    public void setIndexado(Character indexado) {
        this.indexado = indexado;
    }

    public String getSequencial() {
        return this.sequencial;
    }

    public void setSequencial(String sequencial) {
        this.sequencial = sequencial;
    }

    public int getAgencia() {
        return this.agencia;
    }

    public void setAgencia(int agencia) {
        this.agencia = agencia;
    }

    public Character getDgAg() {
        return this.dgAg;
    }

    public void setDgAg(Character dgAg) {
        this.dgAg = dgAg;
    }

    public Integer getConta() {
        return this.conta;
    }

    public void setConta(Integer conta) {
        this.conta = conta;
    }

    public String getDgCt() {
        return this.dgCt;
    }

    public void setDgCt(String dgCt) {
        this.dgCt = dgCt;
    }

    public String getSerie() {
        return this.serie;
    }

    public void setSerie(String serie) {
        this.serie = serie;
    }

    public String getNumero() {
        return this.numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    public String getControle() {
        return this.controle;
    }

    public void setControle(String controle) {
        this.controle = controle;
    }

    public Integer getSeqBoleto() {
        return this.seqBoleto;
    }

    public void setSeqBoleto(Integer seqBoleto) {
        this.seqBoleto = seqBoleto;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getCpfCgc() {
        return this.cpfCgc;
    }

    public void setCpfCgc(String cpfCgc) {
        this.cpfCgc = cpfCgc;
    }

    public String getIeRg() {
        return this.ieRg;
    }

    public void setIeRg(String ieRg) {
        this.ieRg = ieRg;
    }

    public String getOrgaoEmissor() {
        return this.orgaoEmissor;
    }

    public void setOrgaoEmissor(String orgaoEmissor) {
        this.orgaoEmissor = orgaoEmissor;
    }

    public short getSituacao() {
        return this.situacao;
    }

    public void setSituacao(short situacao) {
        this.situacao = situacao;
    }

    public String getObs() {
        return this.obs;
    }

    public void setObs(String obs) {
        this.obs = obs;
    }

    public Character getAnaliticoSintetico() {
        return this.analiticoSintetico;
    }

    public void setAnaliticoSintetico(Character analiticoSintetico) {
        this.analiticoSintetico = analiticoSintetico;
    }

}
