/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;


import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "RPATMP02", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"CHAVE_ID", "ID_CFATPDOC", "DIAS"})})
public class Rpatmp02Entity {

    @Column(name = "ID_RPATMP02", table = "RPATMP02", nullable = false)
    @Id
    private Integer idRpatmp02;

    @Column(name = "ID_CFATPDOC", table = "RPATMP02")
    @Basic
    private Integer idCfatpdoc;

    @Column(name = "ID_CFATPCOB", table = "RPATMP02")
    @Basic
    private Integer idCfatpcob;

    @Column(name = "ID_CFAPORTA", table = "RPATMP02")
    @Basic
    private Integer idCfaporta;

    @Column(name = "ID_CFACCRED", table = "RPATMP02")
    @Basic
    private Integer idCfaccred;

    @Column(name = "ID_CFAESTAD_ORGAO", table = "RPATMP02")
    @Basic
    private Integer idCfaestadOrgao;

    @Column(name = "CHAVE_ID", table = "RPATMP02")
    @Basic
    private Integer chaveId;

    @Column(name = "DIAS", table = "RPATMP02", nullable = false)
    @Basic(optional = false)
    private int dias;

    @Column(name = "VALOR", table = "RPATMP02", nullable = false)
    @Basic(optional = false)
    private double valor;

    @Column(name = "DATA", table = "RPATMP02")
    @Basic
        private String data;

    @Column(name = "ID_AUX1", table = "RPATMP02")
    @Basic
    private Integer idAux1;

    @Column(name = "AGENCIA", table = "RPATMP02")
    @Basic
    private Integer agencia;

    @Column(name = "DG_AG", table = "RPATMP02")
    @Basic
    private Character dgAg;

    @Column(name = "CONTA", table = "RPATMP02")
    @Basic
    private Integer conta;

    @Column(name = "DG_CT", table = "RPATMP02", length = 2)
    @Basic
    private String dgCt;

    @Column(name = "SERIE", table = "RPATMP02", length = 6)
    @Basic
    private String serie;

    @Column(name = "NUMERO", table = "RPATMP02", length = 20)
    @Basic
    private String numero;

    @Column(name = "CONTROLE", table = "RPATMP02", length = 40)
    @Basic
    private String controle;

    @Column(name = "NOME", table = "RPATMP02", length = 60)
    @Basic
    private String nome;

    @Column(name = "CPF_CGC", table = "RPATMP02", length = 18)
    @Basic
    private String cpfCgc;

    @Column(name = "IE_RG", table = "RPATMP02", length = 18)
    @Basic
    private String ieRg;

    @Column(name = "ORGAO_EMISSOR", table = "RPATMP02", length = 3)
    @Basic
    private String orgaoEmissor;

    @Column(name = "OBS", table = "RPATMP02")
    @Lob
    @Basic
    private byte[] obs;

    public Integer getIdRpatmp02() {
        return this.idRpatmp02;
    }

    public void setIdRpatmp02(Integer idRpatmp02) {
        this.idRpatmp02 = idRpatmp02;
    }

    public Integer getIdCfatpdoc() {
        return this.idCfatpdoc;
    }

    public void setIdCfatpdoc(Integer idCfatpdoc) {
        this.idCfatpdoc = idCfatpdoc;
    }

    public Integer getIdCfatpcob() {
        return this.idCfatpcob;
    }

    public void setIdCfatpcob(Integer idCfatpcob) {
        this.idCfatpcob = idCfatpcob;
    }

    public Integer getIdCfaporta() {
        return this.idCfaporta;
    }

    public void setIdCfaporta(Integer idCfaporta) {
        this.idCfaporta = idCfaporta;
    }

    public Integer getIdCfaccred() {
        return this.idCfaccred;
    }

    public void setIdCfaccred(Integer idCfaccred) {
        this.idCfaccred = idCfaccred;
    }

    public Integer getIdCfaestadOrgao() {
        return this.idCfaestadOrgao;
    }

    public void setIdCfaestadOrgao(Integer idCfaestadOrgao) {
        this.idCfaestadOrgao = idCfaestadOrgao;
    }

    public Integer getChaveId() {
        return this.chaveId;
    }

    public void setChaveId(Integer chaveId) {
        this.chaveId = chaveId;
    }

    public int getDias() {
        return this.dias;
    }

    public void setDias(int dias) {
        this.dias = dias;
    }

    public double getValor() {
        return this.valor;
    }

    public void setValor(double valor) {
        this.valor = valor;
    }

    public String getData() {
        return this.data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public Integer getIdAux1() {
        return this.idAux1;
    }

    public void setIdAux1(Integer idAux1) {
        this.idAux1 = idAux1;
    }

    public Integer getAgencia() {
        return this.agencia;
    }

    public void setAgencia(Integer agencia) {
        this.agencia = agencia;
    }

    public Character getDgAg() {
        return this.dgAg;
    }

    public void setDgAg(Character dgAg) {
        this.dgAg = dgAg;
    }

    public Integer getConta() {
        return this.conta;
    }

    public void setConta(Integer conta) {
        this.conta = conta;
    }

    public String getDgCt() {
        return this.dgCt;
    }

    public void setDgCt(String dgCt) {
        this.dgCt = dgCt;
    }

    public String getSerie() {
        return this.serie;
    }

    public void setSerie(String serie) {
        this.serie = serie;
    }

    public String getNumero() {
        return this.numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    public String getControle() {
        return this.controle;
    }

    public void setControle(String controle) {
        this.controle = controle;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getCpfCgc() {
        return this.cpfCgc;
    }

    public void setCpfCgc(String cpfCgc) {
        this.cpfCgc = cpfCgc;
    }

    public String getIeRg() {
        return this.ieRg;
    }

    public void setIeRg(String ieRg) {
        this.ieRg = ieRg;
    }

    public String getOrgaoEmissor() {
        return this.orgaoEmissor;
    }

    public void setOrgaoEmissor(String orgaoEmissor) {
        this.orgaoEmissor = orgaoEmissor;
    }

    public byte[] getObs() {
        return this.obs;
    }

    public void setObs(byte[] obs) {
        this.obs = obs;
    }

}
