/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;


import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "SMALIBAC")
public class SmalibacEntity {

    @Column(name = "ID_SMALIBAC", table = "SMALIBAC", nullable = false)
    @Id
    private Integer idSmalibac;

    @Column(name = "ID_SMALIBER", table = "SMALIBAC")
    @Basic
    private Integer idSmaliber;

    @Column(name = "GUID", table = "SMALIBAC", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "SMALIBAC", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "SMALIBAC")
    @Basic
    private String dtCad;

    @Column(name = "DT_ALT", table = "SMALIBAC")
    @Basic
    private String dtAlt;

    @Column(name = "CT_INTEG", table = "SMALIBAC")
    @Basic
    private Integer ctInteg;

    @Column(name = "COD_TRANSACAO", table = "SMALIBAC")
    @Basic
    private Integer codTransacao;

    @Column(name = "ACAO", table = "SMALIBAC")
    @Basic
    private Character acao;

    @Column(name = "OBS", table = "SMALIBAC", length = 128)
    @Basic
    private String obs;

    public Integer getIdSmalibac() {
        return this.idSmalibac;
    }

    public void setIdSmalibac(Integer idSmalibac) {
        this.idSmalibac = idSmalibac;
    }

    public Integer getIdSmaliber() {
        return this.idSmaliber;
    }

    public void setIdSmaliber(Integer idSmaliber) {
        this.idSmaliber = idSmaliber;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public String getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(String dtCad) {
        this.dtCad = dtCad;
    }

    public String getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(String dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public Integer getCodTransacao() {
        return this.codTransacao;
    }

    public void setCodTransacao(Integer codTransacao) {
        this.codTransacao = codTransacao;
    }

    public Character getAcao() {
        return this.acao;
    }

    public void setAcao(Character acao) {
        this.acao = acao;
    }

    public String getObs() {
        return this.obs;
    }

    public void setObs(String obs) {
        this.obs = obs;
    }

}
