/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;


import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "SMAMODUL", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"DESCRICAO"})})
public class SmamodulEntity {

    @Column(name = "ID_SMAMODUL", table = "SMAMODUL", nullable = false)
    @Id
    private Integer idSmamodul;

    @Column(name = "GUID", table = "SMAMODUL", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "SMAMODUL", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "SMAMODUL")
    @Basic
    private String dtCad;

    @Column(name = "DT_ALT", table = "SMAMODUL")
    @Basic
    private String dtAlt;

    @Column(name = "CT_INTEG", table = "SMAMODUL")
    @Basic
    private Integer ctInteg;

    @Column(name = "MODULO", table = "SMAMODUL", nullable = false, length = 12)
    @Basic(optional = false)
    private String modulo;

    @Column(name = "DESCRICAO", table = "SMAMODUL", nullable = false, length = 40)
    @Basic(optional = false)
    private String descricao;

    public Integer getIdSmamodul() {
        return this.idSmamodul;
    }

    public void setIdSmamodul(Integer idSmamodul) {
        this.idSmamodul = idSmamodul;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public String getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(String dtCad) {
        this.dtCad = dtCad;
    }

    public String getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(String dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public String getModulo() {
        return this.modulo;
    }

    public void setModulo(String modulo) {
        this.modulo = modulo;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

}
