/**
 * This file was generated by the Jeddict
 */
package br.com.sisinfoweb.entity;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "SMAMENSA")
public class SmamensaEntity {

    @Column(name = "ID_SMAMENSA", table = "SMAMENSA", nullable = false)
    @Id
    private Integer idSmamensa;

    @Column(name = "ID_SMAMENSA_ORIGINAL", table = "SMAMENSA")
    @Basic
    private Integer idSmamensaOriginal;

    @Column(name = "ID_SMAUSUAR_FROM", table = "SMAMENSA")
    @Basic
    private Integer idSmausuarFrom;

    @Column(name = "ID_SMAUSUAR_TO", table = "SMAMENSA")
    @Basic
    private Integer idSmausuarTo;

    @Column(name = "GUID", table = "SMAMENSA", nullable = false, length = 16)
    @Basic(optional = false)
    private String guid;

    @Column(name = "US_CAD", table = "SMAMENSA", length = 20)
    @Basic
    private String usCad;

    @Column(name = "DT_CAD", table = "SMAMENSA")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtCad;

    @Column(name = "DT_ALT", table = "SMAMENSA")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dtAlt;

    @Column(name = "CT_INTEG", table = "SMAMENSA")
    @Basic
    private Integer ctInteg;

    @Column(name = "DATA_GERADO", table = "SMAMENSA")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dataGerado;

    @Column(name = "DATA_ENVIO", table = "SMAMENSA")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dataEnvio;

    @Column(name = "DATA_LEITURA", table = "SMAMENSA")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date dataLeitura;

    @Column(name = "ARQUIVO", table = "SMAMENSA", length = 13)
    @Basic
    private String arquivo;

    @Column(name = "ID_ARQUIVO", table = "SMAMENSA")
    @Basic
    private Integer idArquivo;

    @Column(name = "TIPO_MENSAGEM", table = "SMAMENSA")
    @Basic
    private Integer tipoMensagem;

    @Column(name = "STATUS", table = "SMAMENSA")
    @Basic
    private Character status;

    @Column(name = "MSG_FROM", table = "SMAMENSA", length = 128)
    @Basic
    private String msgFrom;

    @Column(name = "MSG_TO", table = "SMAMENSA", length = 128)
    @Basic
    private String msgTo;

    @Column(name = "ASSUNTO", table = "SMAMENSA", length = 128)
    @Basic
    private String assunto;

    @Column(name = "MENSAGEM", table = "SMAMENSA")
    @Lob
    @Basic
    private byte[] mensagem;

    public Integer getIdSmamensa() {
        return this.idSmamensa;
    }

    public void setIdSmamensa(Integer idSmamensa) {
        this.idSmamensa = idSmamensa;
    }

    public Integer getIdSmamensaOriginal() {
        return this.idSmamensaOriginal;
    }

    public void setIdSmamensaOriginal(Integer idSmamensaOriginal) {
        this.idSmamensaOriginal = idSmamensaOriginal;
    }

    public Integer getIdSmausuarFrom() {
        return this.idSmausuarFrom;
    }

    public void setIdSmausuarFrom(Integer idSmausuarFrom) {
        this.idSmausuarFrom = idSmausuarFrom;
    }

    public Integer getIdSmausuarTo() {
        return this.idSmausuarTo;
    }

    public void setIdSmausuarTo(Integer idSmausuarTo) {
        this.idSmausuarTo = idSmausuarTo;
    }

    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUsCad() {
        return this.usCad;
    }

    public void setUsCad(String usCad) {
        this.usCad = usCad;
    }

    public Date getDtCad() {
        return this.dtCad;
    }

    public void setDtCad(Date dtCad) {
        this.dtCad = dtCad;
    }

    public Date getDtAlt() {
        return this.dtAlt;
    }

    public void setDtAlt(Date dtAlt) {
        this.dtAlt = dtAlt;
    }

    public Integer getCtInteg() {
        return this.ctInteg;
    }

    public void setCtInteg(Integer ctInteg) {
        this.ctInteg = ctInteg;
    }

    public Date getDataGerado() {
        return this.dataGerado;
    }

    public void setDataGerado(Date dataGerado) {
        this.dataGerado = dataGerado;
    }

    public Date getDataEnvio() {
        return this.dataEnvio;
    }

    public void setDataEnvio(Date dataEnvio) {
        this.dataEnvio = dataEnvio;
    }

    public Date getDataLeitura() {
        return this.dataLeitura;
    }

    public void setDataLeitura(Date dataLeitura) {
        this.dataLeitura = dataLeitura;
    }

    public String getArquivo() {
        return this.arquivo;
    }

    public void setArquivo(String arquivo) {
        this.arquivo = arquivo;
    }

    public Integer getIdArquivo() {
        return this.idArquivo;
    }

    public void setIdArquivo(Integer idArquivo) {
        this.idArquivo = idArquivo;
    }

    public Integer getTipoMensagem() {
        return this.tipoMensagem;
    }

    public void setTipoMensagem(Integer tipoMensagem) {
        this.tipoMensagem = tipoMensagem;
    }

    public Character getStatus() {
        return this.status;
    }

    public void setStatus(Character status) {
        this.status = status;
    }

    public String getMsgFrom() {
        return this.msgFrom;
    }

    public void setMsgFrom(String msgFrom) {
        this.msgFrom = msgFrom;
    }

    public String getMsgTo() {
        return this.msgTo;
    }

    public void setMsgTo(String msgTo) {
        this.msgTo = msgTo;
    }

    public String getAssunto() {
        return this.assunto;
    }

    public void setAssunto(String assunto) {
        this.assunto = assunto;
    }

    public byte[] getMensagem() {
        return this.mensagem;
    }

    public void setMensagem(byte[] mensagem) {
        this.mensagem = mensagem;
    }

}
